/**
 * Generates assets/excuses_is.json with 1001 Icelandic work excuses.
 * Run with: node scripts/generate_excuses_is.js
 */

const fs = require('fs');
const path = require('path');

const categories = {
  funny: [
    "Kötturinn minn setti sig á lyklaborðið og sendi inn uppsagnarbréfið mitt — er enn að reyna að afturkalla það.",
    "Ég hnerraði svo fast að ég togaði alla vöðva í efri hluta líkamans.",
    "Ég límdi handið mitt óvart við útidyrnahúninn.",
    "Máfur stal bílslyklunum mínum og flaug í burtu. Ég er ekki að grínast.",
    "Ég setti símann í kæli og matinn í vasann. Fann bæði mörgum klukkustundum síðar.",
    "Páfagaukurinn minn hefur lært að hringja og skrá sig veikan í mínu nafni — því miður gerði hann það aftur.",
    "Ég sat á gleraugunum mínum og get nú ekki fundið þau til að leita að þeim.",
    "Ég sofnaði á sófanum og hundurinn minn læsti hundadyrunum að utan.",
    "Ég skráði mig óvart í 5 km hlaupaviðburð sem byrjar í hverfinu mínu í morgun.",
    "Morgunmaturinn minn barðist við mig.",
    "Ég rann á eigin skóhnút og rann niður alla stiga.",
    "Fiskurinn minn er veikur og ég hef verið vakandi alla nótt að gera fisk-hjartahnoð.",
    "Ég fékk peysu mína fösta í bílhurðinni og þurfti að klippa mig laus.",
    "Ég skildi skóna mína eftir hjá vini í gær og uppgötvaði það fyrst við strætóstoppið.",
    "Vekjarinn minn sýndi PM í stað AM á mjög sannfærandi hátt.",
    "Ég reyndi að gera kaffi og gerði súpu í staðinn. Ég veit ekki hvernig.",
    "Refur hefur girt af sér í bílskúrnum mínum og neitar að semja.",
    "Ég laðst út á meðan ég var að sækja póstinn í náttfötum mínum.",
    "Hundurinn minn borðaði bílskráninguna og þjónustumiðstöðin þarf hana í dag.",
    "Ég prófaði nýja hárlit og hárin mín eru nú litur sem finnst ekki í náttúrunni.",
    "Ég svaraði tölvupósti til allra með mjög persónulegt skilaboð í morgun.",
    "Íkorni gnagaði í gegnum eina og einustu hleðslulínuna mína og síminn er dauður.",
    "Ég gekk beint í rennihlera og þarf augnablik.",
    "Blaðra grannaherbergisins flataðist og lokaði bílnum mínum.",
    "Ég rann á bananahýðis. Já, það er einmitt það sem gerðist.",
    "Börnin mín settu augnakúlur á öll vinnuföt mín og ég tók það ekki eftir fyrr en í strætó.",
    "Ég gekk óvart í flashmóbb og komst ekki út.",
    "Ég vaknaði og fann bílinn minn pakkaðan inn í salernispappír.",
    "Ég brann brauðið mitt svo slæmt að reykskynjarinn hringdi til slökkvilidsins.",
    "Bílskúrshurðin mín sjálfvirka hefur ákveðið að taka sér frídaginn í dag.",
    "Ég klæddist tveimur mismunandi skóm óvart og komst að þessu við strætóstoppið.",
    "Herbergismakkinn minn tók sér geit án þess að segja mér frá. Geitin er ekki að laga sig.",
    "Ég fékk bindi mitt fast í prentarann í gær og náði ekki í símann.",
    "Ég velti yfir alla fataskápinn minn í morgun og þarf tíma til að vinna úr þessu.",
    "Ég reyndi að taka skyndileið og endaði í annarri borg.",
    "Dyrklukkan mín tók upp eitthvað sem ég þarf að tilkynna til yfirvalda.",
    "Ég eyddi dagatalinu mínu óvart ásamt öllum fundum dagsins.",
    "Skrifstofustóllinn minn rann á brött og ég glataðist í 45 mínútur.",
    "Rennilásinn minn brotnaði algerlega og ég er enn í úlpunni.",
    "Fugl hefur byggt sér hreiður í uppgjarðarmynni bílsins míns og mér líður ekki til að trufla hann.",
    "Ég ofhluð kaffikökuna mína og hún sprakk. Þvottastarfið er enn í gangi.",
    "Ég fékk límmiða föstu við augnlinsuna.",
    "Ég svaraði dyrunum í svefni. Sendingamaðurinn skildi eftir miða.",
    "Örbylgjuofnsinn minn fell af og lenti einhvern veginn á bílslyklunum.",
    "Ég uppgötvaði í morgun að ég er ofnæmur fyrir nýja sápunni. Andlit mitt er áhugavert.",
    "Ég pantaði morgunverð á heimleið og hann kom til nágrannans — fékk hann aldrei.",
    "Ég skráði mig í líkamsræktartíma klukkan 4 á morgnana og mætti einhvern veginn.",
    "Beltið mitt brotnaði í tvennt þegar ég var að fara. Ég á ekkert varabelt.",
    "Ég settist á eitthvað dularfullt í strætónum og þarf að fara heim til að skipta um föt.",
    "Dós með tómatsósu sprakk í töskuni og eyðilagði hleðslulínuna.",
    "Ég fékk örvasa í vasann þar sem símahluthleðarinn er.",
    "Vindurinn blés frumskjalið mitt burt um leið og ég opnaði bílinn.",
    "Ég klappaði hundinum á nágrannanum og hann sleit leyfið á mér.",
    "Froðan í kaffistönginni minn rifnaði og fleygði heitu kaffi á frammáfatið mitt.",
    "Ég leigði hjól í morgun og það brotnaði á miðri leið.",
    "Ég eyðilagði skó minn þar sem þakrennan rann yfir og féll ofan á mig.",
    "Barnið mitt bjó til list á veggnum í eldhúsinu klukkan fimm í morgun og ég get ekki skilið þetta.",
    "Ég rann á ís á gangstéttinni og henti tömbu og kaffibolla.",
    "Hundurinn minn tók skóinn minn upp á þakið og ég veit ekki hvernig.",
    "Ég rak mig í nýja skrímslið af strætó vegna þess að ég var að lesa.",
    "Ég opnaði ranga hurð hjá næsta húsi og settist niður í eldhúsinu þeirra áður en ég tók eftir þessu.",
    "Einhver parkertaði of nálægt og ég get ekki opnað bílhurðina.",
    "Sveppurinn minn í gróðurhúsinu er í neyðarástandi og þarf sérstaka meðferð.",
    "Ég renndi öllum morgunkaffa mínum á skjáborðið og á lyklaborðið.",
    "Ég þumalfingur minn er fastfrosinn við póstkassann.",
    "Ég keypti ranga stærð af fötum í gær og vandinn er augljós.",
    "Klukkan í stofunni fór að slá 23 sinnum að nóttu til og vekti mig.",
    "Granninn minn er að fá þilviðarklæðningu og þilviðurinn er ansi nálægt bílnum mínum.",
    "Ég er í óvissu um hvort hundurinn minn sé að spila leik á mér eða sé í raun veikur.",
    "Ég fann jógúrtdós í stað skóanna minna í stígvélatabbasamanum.",
    "Kettlingurinn minn lærði að opna kælir og tók matinn minn til að fela.",
    "Ég hlustaði á röngum podcast og fór óvart á málþing um sjálfræðisstefnur.",
    "Ég missti lykilinn að bréfhólfinu og pósturinn minn er þar inni.",
    "Ég var að glyðra stofugluggann og féll í hann.",
    "Þvottavélin mín fór í söng um nóttina og hét sér í strætómeðvitund.",
    "Ég fell upp stigann í stað þess að ofan.",
    "Ananas í matarbúðinni stóð í vegi minn og ég datt yfir hann.",
    "Kettlingurinn minn syng hátt klukkan þrjú um nóttina og ég get ekki sofið.",
    "Ég þvottaðist í myrkrinu og klæddist fötunum í öfuga röð.",
    "Sólartöfluglerin mín brotnaði og ég er of ljósnæmur til að keyra.",
    "Ég setti brauð í brauðristilinn og gleymdist að hann var á í gær. Eldhúsið þarf loftun.",
    "Bréf frá skattyfirvöldum kom í morgun og ég þarf að svara þessu strax.",
    "Strætóbílinn mitt var án loftkælingar og ég er mjög hitasættur.",
    "Ég gleymdi hvar ég parkertaði og er enn að leita.",
    "Ég of-fyrirbúin mig fyrir fundin í dag og er þreyttir of snemma.",
    "Við fundum leygð á vegg eldhússins í morgun og þetta þarf að leysa þegar í stað.",
    "Ég rann á stiga þegar hann brotnaði undir mér.",
    "Sandviturinn minn brotnaði þegar ég tók í hann og allt fór á gólfið.",
    "Ég hef verið þveginn í miklu roki og er allur blautur og þarf að skipta um föt.",
    "Ég braut vasann minn þegar ég rann inn í bílinn.",
    "Kettlingurinn minn hoppaði á mig á meðan ég var að sofa og ég rann út úr rúminu.",
    "Kettlingurinn komst inn í vinnupokann minn og nudd upp öll gögnin.",
    "Ég gleymdi bílnum á röngu svæðinu og hann var dreginn í burtu.",
    "Stigi minn brotnaði þegar ég var að ná í eitthvað á efstu hillu.",
    "Klósettið mitt fór að flóðast í morgun og vatnið er enn í gangi.",
    "Ég er fastur við útidyrnar vegna þess að hurðarhandfangið datt af.",
    "Vindurinn blés hurðinni og hún læstist á mig þegar ég var úti.",
    "Ég er enn í náttfötum því þvottavélin hefur enn öll fötin mín.",
    "Hnoðkúlan mín var gömul og sprakk þegar ég tók í hana.",
    "Hundurinn minn er hlustandi á þjálfun og og má ekki fara eftir að hafa byrjað.",
    "Ég rauk í gegnum sundlaug en gleymdi í nætina að skipuleggja ferðalag mitt.",
    "Ég þvottaðist með klæðningunum sem ég ætlaði að vinna í og þeir eru blautir.",
    "Ég sat ofan í stólinn minn og brotnaði hann.",
    "Ég fór í rangar mætingar og er nú í öðru skrifstofuhúsinu.",
    "Skinnjakinn minn frostnaði við bílinn og má ekki spenna.",
    "Framsætisveskið mitt er fast undir annarri bílnum.",
    "Ég klæddist boltunni þeirrar nágrannans, ekki minni, og útlit þeirra er ólíkt.",
    "Ég settist niður á kaffi sem stóð á stólnum mínum.",
    "Ég tók aðeins léttara gallar en venjulega og pungurinn fall niður á gangi.",
    "Þrösturinn minn syngur svo hátt að ég get ekki hugsað.",
    "Ég missti spegillinn minn á meðan ég var að þvvo upp.",
    "Hnífurinn minn dettur og nær mér á tærnar þegar ég var að búa til morgunmat.",
    "Koffortið mitt er fast undir rúminu og ég get ekki dregið það út.",
    "Ég fell niður þegar ég var að lyfta af mér töskuna.",
    "Rúmið mitt breiddist úr og fell niður á mig þegar ég fékk mér upp.",
    "Leggöngurnar á milli gatna eru lokaðar vegna vegavinnu í dag.",
    "Hundurinn minn hlökkuður upp hjá nágrannanum og þarf mig til að fara eftir honum.",
    "Ég blandaði saman bílalyklunum mínum og nágrannans og hann er á ferðalagi.",
    "Ég þarf að bíða heima vegna pakkasendingar sem á að koma í dag.",
    "Bílhjólið mitt brotnaði þegar ég var að aka á vinnuna.",
    "Lykillinn brotnaði í bílarlásnum þegar ég var að opna hann.",
    "Ég þurfti að taka hundinn til dýralæknisins og hann er enn þar.",
    "Ég braut glerið í bílnum á meðan ég var að hreinsa hann í morgun.",
    "Smurningurinn í bílnum rann út og ég þarf að bíða eftir hjálp.",
    "Ég fór í biðröð á bensínstöðinni og biðröðin er risavaxin.",
    "Strimillinn í bílshliðinu er fastur og ég get ekki opnað gluggann til að greiða.",
    "Bílinn okkar hafnar ekki – einhvern veginn er kveikjatakkinn brotinn.",
    "Bílhjólbarinn minn spratt þegar ég parkertaði í morgun.",
    "Ég þurfti að keyra systur mína á sjúkrahúsið og er enn þar með henni.",
    "Bílinn þarf olíuskipti áður en ég get keyrt lengra.",
    "Ég missti bílalyklana mína í niðurfall á götu.",
    "Bílrúllurnar frost við meðan þær stóðu yfir nótt og þarf þíðingu.",
    "Bílhjólarnir þurftu skiptingu og þjónustumaðurinn mætir ekki fyrr en í hádeginu.",
    "Ég komst að því að bremsan á bílnum er mjög laus og þarf að fara í þjónustu.",
    "Bílstjórnin er of seig í kulda og þarf hlýrun áður en ég geti keyrt.",
    "Þakið á húsinu þurfti skyndiviðgerð vegna leka þegar ég vaknaði.",
    "Ég hef verið í símaviku með netfyrirtæki heila nótt og er enn að bíða.",
    "Loftræstingin í húsinu strindist og við verðum að bíða eftir múrara.",
    "Ég þarf að sinna rafmagnsmálunum áður en ég geti farið.",
    "Ljósaperur í stofunni sprungu allar í einu og er dökkt hér inni.",
    "Ég þarf að mæta í upplýsingafund varðandi rekstrarleyfi bíls minn.",
    "Ég fann vatnsgalli í þvottahúsinu þetta morgun og þarf löggnara.",
    "Eldavélargasinn minn þarf skipti og þjónustumaðurinn kemur á morgun.",
  ],
  believable: [
    "Ég er með læknisstefnumót sem ég gleymdi alveg fyrr en í morgun.",
    "Barnið mitt er veikt og ég fann engan til að passa það.",
    "Bíllinn minn kveikir ekki — rafgeymirinn er dauður.",
    "Ég er með verulega höfuðverk og get ekki horft í skjá.",
    "Barnfóstrið mitt afpantaði í síðustu mínútu.",
    "Fjölskyldunáðarvísi sem ég get ekki fjallað um núna.",
    "Ég er með flatan dekk á leiðinni.",
    "Aldraður foreldri minn þarf að fara á spítala í dag.",
    "Ég vaknaði með matareitrun og það er ekki fallegt.",
    "Bakið mitt fór og ég get varla hreyft mig.",
    "Ég er fastur í óvæntri umferðarteppu — þjóðvegurinn er algerlega lokaður.",
    "Lestarferðin mín var afpöntuð án fyrirvara.",
    "Skólinn hringdi — hiti, ég þarf að sækja það.",
    "Ég er með gegnumæðisbólgu og vil ekki smita aðra.",
    "Vatnslagnirnar sprungu yfir nótt og vatn er alls staðar.",
    "Það er gasslys og verktakinn er á leiðinni.",
    "Ég er í dómnefnd sem var staðfest í morgun.",
    "Ég er með mjög alvarlegan veikindi sem þarf hvíld.",
    "Húslæknirinn minn bókaði mig inn í morguninn og ég gat ekki afborið.",
    "Ég er með flogaveiki og hef verið í krampa í nótt.",
    "Líkamleg meiðsl frá í gær þarfnast eftirfylgni í dag.",
    "Ég er að fara í aðgerð sem ég þorði ekki að segja frá.",
    "Barnið mitt braut handlegginn sinn í leikskólanum í gær.",
    "Að þurfa að fara með ungabarnið í sérstakt rannsóknarferð.",
    "Ég þarf að vera heima vegna þjónustumanns sem á að koma.",
    "Húsráðandinn minn er að skoða vandann og þarf aðgang.",
    "Rafmagnsmaðurinn er á leiðinni og þetta er lýsandi neyðarviðgerð.",
    "Ég er að bíða eftir niðurstöðum rannsóknar frá sjúkrahúsinu.",
    "Alvarleg ofnæmisviðbrögð hafa haft áhrif á mig í nótt.",
    "Ég þarf að vera hjá nákomnum einstaklingi sem er í erfitt sálfræðilegt ferli.",
    "Barnið mitt var greinst með smitsjúkdóm og við þurfum að sótta í sóttkví.",
    "Sjúkrabifreiðin er komin með fjölskyldumeðlim minn og ég er enn á spítalanum.",
    "Ég þarf hjálp við að sjá um aldraðan foreldri sem féll í nótt.",
    "Leiguíbúðin mín var flutt úr án samþykkis og ég þarf að leysa lögfræðimál.",
    "Barnið mitt þarf sérstakt námsmat sem er einungis í boði í dag.",
    "Tönn mín brotnaði og er mjög sárt og þarf tannlæknismeðferð þegar í stað.",
    "Ég er með augnaverk og læknirinn gæti greint eitthvað alvarlegt.",
    "Ég þarf að fara í krabbameinsrannsókn sem ég hafði gleymt.",
    "Húsvísurinn minn þarf að undirrita eitthvað á þessum degi.",
    "Einn af vinnufélögunum mínum er alvarlega veikur og ég þarf að aðstoða fjölskyldu þeirra.",
    "Bíllinn minn var stolinn og ég þarf að tilkynna það lögreglu.",
    "Lástakinn minn bilaði og ég er læstur inni og bíð eftir yfirfara.",
    "Barnaskólinn minn er lokaður vegna óvæntra aðstæðna og börnin eru heima.",
    "Ég fékk rangar lyfjar frá lyfjabúðinni og þarf að fara aftur.",
    "Nákominn minn þarf aðstoð við meðferðarúrræðin sín.",
    "Húsráðandinn þarf aðgang í íbúðina til skoðunar vegna truflunar.",
    "Ég hef verið með hár hita í þrjá daga og er loksins að fara til læknis.",
    "Bílstjórnin mín skaðaðist í umferðarlyktum og ég þarf viðgerð.",
    "Ég sæki barnið mitt frá skóla vegna eineltis sem þarf að ræða þegar í stað.",
    "Ég er með skráðan sálfræðingsviðtal í dag sem ég get ekki frestað.",
    "Ömmu mínni liðnaði og ég þarf að vera hjá fjölskyldunni.",
    "Lyfin mín þarf endurnýjunar og lyfjafræðingurinn opnar ekki fyrr en í dag.",
    "Aðgerðin mín er frestað og nýr tími er þegar í dag.",
    "Ég er með krampaverk og þarf hvíld.",
    "Örlegar námsniðurstöður barnsins míns krefjast hlutdrægrar umfjöllunar.",
    "Ég þarf að skila gögnum til úrskurðarnefndar sem líður út í dag.",
    "Ég er veikur og læknisvottorð er nú þegar á leiðinni til ykkar.",
    "Sjúkrabíllinn var hringdur í fjölskylduna mína í nótt.",
    "Verkurinn í hné mitt er orðinn svo slæmur að ég get ekki gengið.",
    "Ég þarf að fara í segulómun vegna þess sem kom upp á skoðun í síðasta mánuði.",
    "Barnið mitt þarf sértæka undirfylgni vegna þroskalegs vandamáls.",
    "Heimilisaðili minn þarf að komast á slysadeild og ég þarf að keyra.",
    "Barnið er í hríðarveiki og þarf foreldra sína.",
    "Ég er í heimsókn á sjúkrahúsið vegna nágranna sem á engan annan.",
    "Ég þarf að mæta í neyðarfund hjá lögfræðingi um erfingjafsál.",
    "Krafan um að mæta á þingsetu barnaverndarnefndar kemur í dag.",
    "Húsakaupasamningurinn á að undirritast og kaupmaðurinn getur aðeins í dag.",
    "Ég er með lyfjaverkan sem hefur áhrif á hæfni mína til að aka.",
    "Tafarlaus þjónusta við eldhúsið vegna vatnsleka.",
    "Sjúkrahúsviðtal um ástand sem legar mér á hjarta.",
    "Bíllinn minn er á bjargarsveinn og ég bíð.",
    "Ég þarf heildareftirlit á bíl minn áður en ég get keyrt.",
    "Hálsbólgan mín er svo slæm að ég get varla gleymt.",
    "Ég þarf að sinna flóku lagalegu máli sem nær yfir daginn.",
    "Ég kom að bruna í nágrenninu og þarf að vera til staðar.",
    "Lágþrýstingur minn hefur verið vandamál og ég þarf hvíld.",
    "Þögnin og erfiðleikinn á eftir dauða nákominn krefjast heimvistar.",
    "Ég þarf að taka að mér börnin bróður míns vegna neyðarástands.",
    "Lög krefjast þess að ég mæti á dómþing þennan dag.",
    "Ég er með öndunarvandamál sem þarf sérstaka athugun.",
    "Klíník sem ég er skráður í er opin aðeins þennan dag.",
    "Ég þarf að mæta á skurðlæknismat vegna þegar greindra einkenna.",
    "Tannpínan mín er orðin svo alvarleg að ég þarf neyðartannlæknisþjónustu.",
    "Ég er fastsettur í ráðstöfunum fyrir foreldradag á skólanum.",
    "Ég þarf að sinna samþykktarferli fyrir húsnæðis- og þjónustuaðgang.",
    "Lögmenn mínir þurfa undirskrift mína á mikilvægum skjölum í dag.",
    "Ég þarf sérstöðu fyrir þunglyndi sem þarf að taka til meðferðar þegar í stað.",
    "Viðhaldsvandinn á húsinu krefst tafarlausrar athygli.",
    "Ég fann vatnsgalla af rásum í íbúðinni í morgun.",
    "Eldavélin mín kviknaði til og ég þarfnast aðstoðar.",
    "Ég þarf að sinna öldruðum foreldrum um lengri tíma þessa vikuna.",
    "Bjargráðasveitin er að koma eftir slys barnsins míns.",
    "Ég þarf að taka þátt í skólaráðsfundi sem er einungis í dag.",
    "Barnið mitt er útilokað frá skólanum vegna líkamlegu vandamálsins.",
    "Ég er með þyngd á hjartanu og þarf hvíld til bata.",
    "Ég þarf hvíld vegna flókins meðferðarferlis sem er enn í gangi.",
    "Ég þarf að taka þátt í neyðarfundi um fjárhagsmál hér heima.",
    "Sjúkrahúsið þarf nánara mat á ástand mínu í morgun.",
    "Lyfið mitt þarf endurskoðun af sérfræðingi og hann er aðeins tiltækur í dag.",
    "Skurðlækningaviðtalið mitt er fluttur á þennan dag.",
    "Ég þarf hvíld eftir neyðartannaðgerð sem fór fram í gær.",
    "Barnið mitt er með hitasótt og þarf mig heima.",
    "Ég þarf tafarlaust að sinna fjölskyldumáli sem kemur upp á.",
    "Lyfið mitt þarf sérniðurstöður sem lega eru tilbúnar í dag.",
    "Ég þarf sérstaka aðstoð við fatlað fjölskyldumeðlim.",
    "Fæðingardagur nákominn gerir það að verkum að ég þarf að vera heima.",
    "Ég þarf að vera á ljósmóðurviðtali með maka mínum.",
    "Sérstök fjárhagsneyð þarf að leysa strax.",
    "Ég þarf að fara í geðheilsumat í dag sem ég get ekki frestað.",
    "Ég þarf hvíld vegna augnlæknisaðgerðar sem fór fram í gær.",
    "Ég þarf að sjá um barn sem er með sóttkví.",
    "Ég þarf tafarlaust að taka þátt í skýrslugerð þar sem ég er vitni.",
    "Lögráðamaður barnsins míns þarf mig á fundi í dag.",
    "Ég þarf sérstaka hvíld vegna sykursýkismeðferðar sem þarfnast eftirlits.",
    "Barn mitt þarf bólusetningarsafn sem þarf að vera tilbúið áður en skóli byrjar.",
    "Ég þarf að sinna foreldraleyfi í tengslum við fæðingarorlofsúrræði.",
    "Ég þarf að mæta á sérstaka námsráðgjöf vegna skólavals barnsins míns.",
    "Hér heima þarf húsmeistara til að skoða raka í múr.",
    "Ég er veikur með tengdar kvilla sem krefjast hvíldar.",
    "Barnið mitt fékk einkunn sem þarf aðstoð lögfræðings við að vinna.",
    "Ég þarf að sitja við hlið foreldris míns á skurðlæknisviðtali.",
    "Ég fór í rangar lyfjablöndur og þarfnast eftirlits.",
    "Smiðurinn er á leiðinni til að laga hurðina sem gekk í sundur.",
    "Ég er með sterka verk í kvið og þarf að fara á bráðamóttöku.",
    "Ég þarf endurnýjun á sérlyfjum sem er aðeins í boði í dag.",
    "Ég þarf að mæta á skólaráðsfund vegna breytt skólanámsáætlunar.",
    "Barnlæknirinn minn þarf eftirlit á barnið mitt vegna þroskavandans.",
    "Skyndileg sóttkví heima þýðir að ég get ekki komið inn á vinnustaðinn.",
    "Ég þarf viðgerð á hjálparstigi þar sem það brotnaði þennan morgun.",
    "Ég þarf að vera á löggæslu vegna innbrot í bílgeymsluna mína.",
    "Ég þarf sjúklingaviðtal sem er skráð einungis í dag.",
    "Fjölskyldumeðlimurinn minn þarf hvata og stuðning í dag.",
    "Ég þarf hvíld vegna augnkrampans í nótt.",
    "Húshitakerfi sprakk og við erum án hitunar.",
    "Lögmaðurinn minn þarf undirskrift mína á mikilvægum skjölum í dag.",
    "Ég þarf sérstaka hvíld vegna meðhöndlunar þreytu.",
    "Þjónustan á gasstöðinni þarf að koma og laga lekann sem við uppgötvuðum.",
    "Ég er veikur af smitsjúkdóm og vill ekki smita samstarfsmenn.",
    "Stigi minn á heimili brotnaði og þarf endurnýjun.",
    "Ég þarf hvíld eftir lyfjameðferð sem hefur sterk aukaverkanir.",
    "Ég þarf sérstaka sálfræðihjálp í dag vegna bresti sem kom upp.",
    "Barnið mitt fékk veiki sem þarf sérstaka einangrun.",
    "Ég þarf hvíld vegna svimmings og óglæðu.",
    "Ég þarf sérstaka hvíld vegna meiðsla sem ég hlaut í liðnum mánuði.",
    "Ég þarf lykil til að opna nýjar lásur eftir að gamla leyðirinn brotnaði.",
    "Leyndarskjöl þarfnast tilkynningar til yfirvalda þennan dag.",
  ],
  chaotic: [
    "Ég vaknaði í öðrum bæ án þess að muna eftir að hafa farið þangað.",
    "Granninn minn er að flytja og hefur þurft á hjálp minni að halda síðan klukkan fimm í morgun.",
    "Björgunarlið er utan við húsið mitt og ég veit ekki af hverju.",
    "Ég er á leiðinni en klettur er á þjóðveginum.",
    "Refurinn minn er fastur í þakrennu nágrannans og ég þarf að bjarga honum.",
    "Lögreglan bað mig að vera heima meðan þeir rannsaka eitthvað.",
    "Hundurinn minn rann í burtu og er núna hjá lögreglunni á öðrum bæ.",
    "Ég finn ekki bílinn minn. Líklega parkertaði ég hann einhvers staðar í gær.",
    "Ég er að reyna að bjarga fugli sem skall á glugganum og er að svima.",
    "Matarbúðin var tekin í gíslingu rétt þegar ég var að kaupa morgunverð.",
    "Ég er í miðjum eldsneytisstrika og bensíninu er næstum þrotið.",
    "Tímafarar tækið mitt brotnaði og ég er ekki viss um hvaða dag það er.",
    "Ég er fastur á milli hæða í lyftu.",
    "Vegurinn frá húsinu mínu er þakinn af kindakjöti.",
    "Kisan mín fjær af stigi og þarf björgun.",
    "Ég fékk óvænta heimsókn frá fjarlægum ættingja sem kom úr öðru landi.",
    "Bær minn er fluttur og ég get ekki fundið húsið mitt.",
    "Handahóflæg frétt fékk mig til að hlaupa úr húsinu og ég er enn að reyna að ná aftur.",
    "Stórfelld umræða um nágrannakappaksturs flutti heildarlokun á götunni.",
    "Sjálfskeyrandi bíllinn minn fór í frítíma og er nú í öðru borgarhlutanum.",
    "Lest sem ég er í stöðvast í göngli og við erum þar enn.",
    "Hótelherbergið mitt var tvíbókað og ég er enn á skrifstofunni að reyna að leysa þetta.",
    "Flugið mitt var flutt og ég er nú á röngum flugvelli.",
    "Þjálfari hundinn minn hefur þjálfað hann til að rífa upp skipulagsáætlanir.",
    "Ég var tekinn sem gíslingur á leikfimi og er nýlega sleppt.",
    "Leikur á bakaríinu tók mig að óvörum og ég tapaði biðröðinni.",
    "Öryggisgæslan á vinnustaðnum vildi ekki láta mig inn án auðkenniskortsins.",
    "Ég missti veskið á leiðinni og þarf að afturkalla allar kreditkort.",
    "Mannfjöldinn utan við kaffihúsið minn er svo stór að ég komst ekki út.",
    "Öryggissett mín á heimili gaf út ranga viðvörun og lögreglan er hér.",
    "Ég er á leiðinni en ég er fastur í snúningstré.",
    "Snjóflóð lokar götunni minni og ég get ekki komist á vinnuna.",
    "Streymi af vatnsdýrum rann yfir bílinn minn á meðan hann stóð.",
    "Lestartaka með nágrannann fór úrskeiðis og landi við gjá.",
    "Gamaður maðurinn á horninu bauð mér í stór verkefni og ég þorðist ekki að neita.",
    "Ég er í miðju af snjóhengju á fjallbraut.",
    "Borgarmestari báðst um aðstoð mína við sérstakt verkefni.",
    "Bærinn tók útivinnudag og ég þurfti að taka þátt.",
    "Útvarpsstöðin fékk mig til að taka þátt í þátttaka í beinni útsendingu.",
    "Fornleifagröftur fannst í garðinum mínum og þeir þurfa á mér að halda.",
    "Ég er á bjargfarartæki á Hraunfossum.",
    "Góssafarar bráðnuðu þrír vegna þess að ég gleymdi þeim í bílnum.",
    "Hundar á götu lokaðu yfirferð.",
    "Skólaborðið fellur í þakrennu.",
    "Mikið af frönskum steiktum kartöflum á þjóðveginum skapar hætta.",
    "Öll lestarstöðin er með einangrað fólk vegna meiriháttar leka.",
    "Frá morgunmál til kvöldmál: leita af hlaupabíl sem var stolinn í góðgildi.",
    "Grannarnir héldu upp á nýttárskvöld á röngum degi.",
    "Lágflugur voru yfir bílnum mínum og voru hindrandi.",
    "Ég er fastur í stórum rústum við gömlum sandskóla.",
    "Ég tók á leiðina og fór alla leið til Akureyrar í stað Reykjavíkur.",
    "Stór flugskaðaviðvörun á loftbrautinni kom þvert á ferðalag mitt.",
    "Gaslys í þjóðvegi krefst lokunar alls svæðisins.",
    "Ég missti herbergislyklana mína og er enn að leita.",
    "Sjóferð mín tafðist vegna reykinga á öldrandi skipi.",
    "Heimsminni jarðskjálfta var skráð þennan morgun og ég er vitni.",
    "Öll gata lokuð vegna leka á meginlögn.",
    "Ég sat yfir jafngildisráðstefna sem tók heilan dag.",
    "Ég er fastur í sérverkefni fyrir sveitarfélagið sem þeir þegjast yfir.",
    "Stór eldur í nágrenninu kerfst af björgunarlið og ég kem ekki fram.",
    "Ég er fastur í vegagerð sem tafðist vegna slyssins sem gerðist í gær.",
    "Mannfjöldi í kringum götu minn leyft ekki yfirferð.",
    "Þjóðlegar hátíð er á þessari götu í dag og umferð er lokuð.",
    "Ég er boðinn á sérstaka heimsókn á opinberri stofnun.",
    "Húslágt er á þessum stað og þarf viðgerð þegar í stað.",
    "Stór kreppuverkefni hjá nágrannanum þarfnast aðstoðar.",
    "Ég er á leið en gangbrúin er lokuð vegna umsamskomsins.",
    "Ég er fastsettur í uppeldishætti sem krefjast heilveru dagsins.",
    "Slysið á þjóðveginum þarf vitni og ég var á vettvangi.",
    "Ég er meðal björgunarlags sem þarf aðstoð við erfiðar aðstæður.",
    "Geimskipið lenti á svæðinu mínu og þeir þurfa á mér að halda.",
    "Ég var valinn sem dómsmaður í stóru keppni og get ekki neitað.",
    "Ráðgjafarþjónustan mín við nágranna tók heilan dag.",
    "Ég þarf að vera við hlið nákomins í sérstöku persónulegu ferli.",
    "Lögmaðurinn minn krefst þess að ég mæti á fund þennan dag.",
    "Framkvæmdastjóri félagsins þarfnast sérstakrar aðstoðar minnar.",
    "Ég er fastur á milli ferja.",
    "Öll leiðakerfi eru vistað utan starfssvæðisins.",
    "Bíóið mitt var að keyra og kom í biðröð á heimleið.",
    "Ég er boðinn í sérfundar sem ég þori ekki að hafna.",
    "Nákvæmni í uppgjöri þarfnast þátttöku minnar.",
    "Barnið mitt var tekið í rangar skóla og þarf uppgjör.",
    "Grannarnir mínir halda ótrúlega stóra veislu og hún brotnar út á gangstéttina.",
    "Ég er á biðröð á þjónustu sem mun aðeins taka 5 mínútur þegar ég komst að.",
    "Ég þarf að taka þátt í nákvæmum skrásettum umræðum.",
    "Þversagnakennd vandinn við fjarskiptanet þarfnast aðstoðar minnar.",
    "Ég er fastsettur á fundi sem var kallaður saman í síðustu mínútu.",
    "Flottahundar hlupu yfir bílinn minn á leið til vinnu.",
    "Ég er enn á heimleið frá miðnætti vegna skemmtiferðar sem fór úr böndunum.",
    "Strætóstjórnandinn var mér þekktur og við fórum á aukaferðalag.",
    "Ég reyndi að gera gott og það dróst út í heilan dag.",
    "Þjóðleg keppni hófst á götu minni þegar ég var á leið.",
    "Ég fór á rangar síður á netinu og þarf tæknilegar leiðbeiningar.",
    "Rúsínu-uppákomur tóku allan morguninn.",
    "Ég þarf að ljúka neyðarverkefni sem er ekki unnt að fresta.",
    "Ég er víðs fjarri vegna þess að hringurinn minn vildi mig sjá.",
    "Ég þarfnaðist sérstaks útbúnaðar sem var aðeins tiltækur fjarri.",
    "Mikilvægt verkefni heimsótti mig á vinnustaðinn og tók heilan dag.",
    "Ég er að þóknast sérstöku innskoti í þjóðfélagsstarfi.",
    "Bíóstjórinn minn þarfnaðist ráðgjafar og við ræddum á langri hringferð.",
    "Ég er á sérleið til að skoða náttúrufyrirbæri.",
    "Ég þarf að vera til staðar á sérstöku tilviki í nágrenninu.",
    "Ég er staddur í svæðislokun vegna öryggismála.",
    "Ég var beðinn um sérfræðilegar upplýsingar við sérfræðingsfund.",
    "Ég er fastur í bílalest sem nær yfir allt svæðið.",
    "Keppni þjóðlags fékk mig til að sjúkdegur.",
    "Ég þarf að leysa flókin kerfisvandamál sem komu upp í nótt.",
    "Sérstök athugun á nágrennið krefst viðveru minnar.",
    "Ég er á rangarleið á grund hjól hraðaks.",
    "Heimilissalan mín krefst meiri skoðunar en gert var ráð fyrir.",
    "Ég er á leið í sérstakt nákvæmniviðtal.",
    "Þjóðlegur viðburður á opnum svæðum þarfnast þátttöku minnar.",
    "Ég er að skoða eitt sem á sér samhljóðlega þátttöku.",
    "Útvarpsnálgunin mín þarfnast sérstakrar þátttöku.",
    "Ég er á rangarleið við flæðibraut.",
    "Ný íbúðar þarfnast sérskoðunar í dag.",
    "Ég er á leiðarenda með sérstaka verkefni.",
    "Ég er aðdragandi að sérstakri þjóðlegri atburð.",
    "Nýtt skipulag þarfnast sérstakrar þátttöku minnar.",
    "Ég er á sérstöku verkefni sem þarfnast heilveru dagsins.",
    "Frí heimsókn frá sérstakra einstaklings þarfnast heilveru.",
    "Ég þarf að mæta á flókin kynningarfund.",
    "Ég er á leið í sérstaka hringrásarannsókn.",
    "Ég þarf sérstaka hvíld vegna meiðsla.",
    "Ég er á söfnuðum til sérstakra rannsókna.",
    "Sérstök þjálfunarlota þarfnast heilveru minnar.",
    "Ég er á sérstaka þátttöku á þessum degi.",
    "Nýtt félagsverkefni þarfnast sérstakrar þátttöku minnar.",
    "Ég er á leið til sérstaks ráðstefnu.",
    "Sérstök mæting þarfnast minnar viðveru.",
    "Ég er á sérstaka öldrungarannsókn.",
    "Nýtt samstarf þarfnast sérstakrar þátttöku í dag.",
  ],
  dark: [
    "Ég fann mig ekki fær um að mæta í dag. Þarf smá tíma.",
    "Ég er að glíma við persónuleg mál sem þarf að leysa áður en ég get einbeitt mér að vinnu.",
    "Andleg heilsa mín þarf á hvíld að halda í dag.",
    "Ég er mjög þreyttur og þarf á endurnýjun að halda.",
    "Ég er að takast á við eitthvað erfitt og þarf daginn til þess.",
    "Mér líður ekki vel í dag og þarf á hvíld að halda.",
    "Ég þarf sálfræðilegan rúm til að takast á við eitthvað sem gerðist.",
    "Ég er að fara í gegnum erfiðan tíma og þarf á stuðningi að halda.",
    "Líkamleg og andleg þreyta hefur safnast upp og ég þarf hvíld.",
    "Ég er að reyna að ráða við söknuð eftir nákominn.",
    "Ég þarf daginn til að vinna úr erfiðum tilfinningum.",
    "Ég er ekki í ástandi til að vinna í dag og þarf að hlúa að mér sjálfum.",
    "Ég er að kljást við kvíða sem þarfnast athugunar.",
    "Þetta er erfiður dagur fyrir mig og ég þarf að vera heima.",
    "Ég er að reyna að komast í gegnum persónulega erfiðleika.",
    "Ég hef verið með svefntruflanir og er mjög þreyttur.",
    "Ég þarf einveru og stillingu til að vinna úr eitthvað.",
    "Ég er að fá stuðning við eitthvað persónulegt og get ekki mætt.",
    "Ég þarf daginn til að skipuleggja líf mitt á nýjan leik.",
    "Ég er að glíma við sorg eftir tap.",
    "Ég er að læra að lifa með nýja raunveruleika.",
    "Ég þarf sálfræðilega hvíld frá streitu dagsins.",
    "Ég er að kljást við átök og þarf rúm til að hugsa.",
    "Ég þarf á stuðnings að halda á þessum tíma.",
    "Andlegar áskoranir krefjast þess að ég sé heima.",
    "Ég er ekki fær um að einbeita mér í dag vegna persónulegra mála.",
    "Ég þarf hvíld vegna tilfinningalegrar þreytu.",
    "Ég er að takast á við eitthvað sem er meira en vinna getur leyst.",
    "Ég er í meðferð sem krefst hvíldar í dag.",
    "Ég þarf tíma til að endurreisa jafnvægi mitt.",
    "Ég er að glíma við eitthvað sem þarf persónulega athygli.",
    "Ég þarf hvíld til að koma í veg fyrir versnun á heilsumálum.",
    "Ég er þreyttur á þreytuna og þarf daginn.",
    "Ég er búinn að gefa svo mikið og þarf á gæslu að halda.",
    "Ég er að vinna úr eitthvað sem gerðist nýlega og er hlustandi á líkama minn.",
    "Ég þarf tíma til að gera upp við sjálfan mig.",
    "Ég er að glíma við kvíða og þunglyndi og þarf á hlúð að halda.",
    "Ég er í sálfræðilegri meðferð og þarf dag til þess.",
    "Ég þarf á hvíld að halda vegna þreytu sem er tilfinningaleg.",
    "Ég er að vinna úr trauma og þarf rúm til þess.",
    "Ég er að takast á við einsemd og þarf tíma til að gera eitthvað við það.",
    "Ég þarf á stuðnings við geðheilsu að halda í dag.",
    "Ég er þreyttur af að þykjast og þarf daginn til að vera mér sjálfum.",
    "Ég er að vinna úr erfiðum áhrifum af nýlegum atburðum.",
    "Ég þarf tíma til að endurkoma í jafnvægi.",
    "Ég er að glíma við streitu sem hefur safnast upp í langa tíma.",
    "Ég þarf daginn til að nota meðferðarúrræði.",
    "Ég er að reyna að finna leið til að vinna úr eitthvað erfitt.",
    "Ég þarf rúm til að hugsa og hvíla.",
    "Ég er að takast á við erfiðar aðstæður sem krefjast þess að ég sé heima.",
    "Ég þarf á léttri hvíld að halda eftir langan tíma.",
    "Ég er að glíma við sorg sem þarf á tíma að halda.",
    "Ég þarf stillingu til að vinna úr eitthvað sem er erfitt.",
    "Ég er að kljást við geðheilsuáskoranir sem þarf á huga að halda.",
    "Ég þarf á hvíld frá þreytu allrar vinnu að halda.",
    "Ég er mjög þreyttur og þarf á hvíld að halda.",
    "Ég er að glíma við eitthvað persónulegt sem þarf á tíma að halda.",
    "Ég þarf á meðferð að halda vegna þessa sem er að gerast.",
    "Ég er að vinna úr erfiðum tilfinningum sem þarf tíma til.",
    "Ég þarf tíma til að hlúa að mér og vera heima.",
    "Ég er að takast á við erfiðan tíma og þarf rúm til þess.",
    "Ég þarf á stuðnings af nánum að halda í dag.",
    "Ég er að kljást við innri átök sem þarf á hlustun að halda.",
    "Ég þarf dag til þess að endurlíta allt og ná jafnvægi.",
    "Ég er mjög þreyttur af löngu ferli og þarf hvíld.",
    "Ég þarf tíma til að vinna úr erfiðum áhrifum.",
    "Ég er að fara í gegnum miklar breytingar og þarf hvíld.",
    "Ég þarf á dag til þess að vera með sjálfan mig.",
    "Ég er búinn að gleyma mér sjálfum og þarf dag til að endurfinna mig.",
    "Ég þarf á hlutlægri hvíld að halda vegna streitu.",
    "Ég er að glíma við tilfinningalegar áskoranir sem þarf á umhyggju að halda.",
    "Ég þarf hvíld vegna þreytu sem hefur safnast upp.",
    "Ég er að fara í gegnum erfitt og þarf tíma til að gera uppgjör.",
    "Ég þarf dag til að einbeita mér að geðheilsu minni.",
    "Ég er að þola eitthvað sem þarf á hvíld að halda.",
    "Ég þarf tíma til að fara í gegnum eitthvað persónulegt.",
    "Ég er þreyttur af hlutverki mínu og þarf hvíld.",
    "Ég þarf dag til að hvíla mig vegna streitu.",
    "Ég er að glíma við kvíða og þarf á hvíld að halda.",
    "Ég þarf tíma til að finna hvar ég er staddur.",
    "Ég er að vinna úr erfiðum lífsatburðum.",
    "Ég þarf á hlustun og hlutfallslegri hvíld að halda.",
    "Ég er að takast á við persónuleg vandamál sem þarf á tíma að halda.",
    "Ég þarf dag til að endurkoma mér sjálfum.",
    "Ég er þreyttur og þarf á hvíld að halda vegna þessa sem er í gangi.",
    "Ég er að glíma við erfið lífsþraut og þarf á tíma að halda.",
    "Ég þarf hvíld til að verða betri.",
    "Ég er að fá hjálp við andlegar áskoranir og þarf dag til þess.",
    "Ég þarf tíma til að fara í gegnum eitthvað erfitt.",
    "Ég er að kljást við eitthvað sem þarf á meðferð að halda.",
    "Ég þarf dag til að staldra við og hvíla.",
    "Ég er á leið í sérstaka meðferð fyrir kvíða.",
    "Ég þarf á hlustun og hvíld að halda í dag.",
    "Ég er að glíma við eitthvað sem þarfnast einbeitingar og hvíldar.",
    "Ég þarf dag til þess að fara yfir þetta sem er að gerast.",
    "Ég er þreyttur og óskaplegur og þarf hvíld.",
    "Ég er að fara í gegnum erfiðleika sem þarf á tíma að halda.",
    "Ég þarf að vera heima til að hlúa að sál minni.",
    "Ég er að takast á við eitthvað persónulegt sem þarf á hvíld að halda.",
    "Ég þarf dag til þess að finna friðinn.",
    "Ég er að kljást við erfiðar aðstæður og þarf rúm til að gera eitthvað við það.",
    "Ég þarf hvíld vegna þreytu af streitu.",
    "Ég er að vinna úr eitthvað sem gerðist og þarf á tíma að halda.",
    "Ég þarf dag til þess að endurgera hug minn og sál.",
    "Ég er þreyttur af líf sem er of fast og þarf hvíld.",
    "Ég er að glíma við eitthvað sem þarf á hvíld og stillingunni að halda.",
    "Ég þarf dag til þess að endurkoma sem maður.",
    "Ég er að fara í gegnum erfiðan samhengistíma og þarf á tíma að halda.",
    "Ég er þreyttur og þarf daginn til að vera mér sjálfum.",
    "Ég þarf á hvíld og ró að halda í dag.",
    "Ég er að vinna úr eitthvað erfitt og þarf rúm til þess.",
    "Ég þarf dag til þess að vera heima og hlúa að mér.",
    "Ég er að takast á við eitthvað sem þarf á hvíld og hlustun að halda.",
    "Ég þarf tíma til að endurhlaða mig og fá kraft.",
    "Ég er þreyttur og þarf dag til þess að vera mér sjálfum.",
    "Ég er að glíma við eitthvað persónulegt og þarf á hvíld að halda.",
    "Ég þarf dag til þess að fara í gegnum erfiðar tilfinningar.",
    "Ég er að kljást við lífsástæður sem krefst þess að ég sé heima.",
    "Ég þarf hvíld vegna álags sem hefur safnast upp.",
    "Ég er að takast á við eitthvað sem þarf á einveru og hvíld að halda.",
    "Ég þarf dag til þess að fara í gegnum þetta.",
    "Ég er þreyttur af daglegum skyldum og þarf hvíld.",
    "Ég er að glíma við eitthvað sem krefjast þess að ég sé heima.",
    "Ég þarf dag til þess að hlusta á líkama minn og sál.",
    "Ég er að fara í gegnum eitthvað sem þarf á tíma og hlutlægni að halda.",
    "Ég þarf hvíld til þess að vera betri maður á morgun.",
    "Ég er þreyttur og þarf á hvíld og friðsömu að halda.",
    "Ég er að vinna úr erfiðum hlutum og þarf rúm til þess.",
    "Ég þarf dag til þess að standa upp og vera í friðsemi.",
    "Ég er að kljást við eitthvað sem þarf á tíma og hvíld að halda.",
    "Ég þarf dag til þess að endurkoma mér sem heildarmanneskju.",
    "Ég er að fara í gegnum eitthvað erfitt og þarf á tíma að halda.",
    "Ég þarf hvíld til þess að koma mér aftur í gott ástand.",
    "Ég er þreyttur og þarf daginn til þess að vera heima og hvíla.",
    "Ég er að glíma við eitthvað sem þarf á hvíld og einveru að halda.",
    "Ég þarf dag til þess að fara yfir þetta allt og hvíla.",
    "Ég er að takast á við erfiðar aðstæður og þarf rúm til þess.",
    "Ég þarf hvíld vegna andlegrar þreytu.",
    "Ég er þreyttur og þarf dag til þess að vera mér sjálfum.",
  ],
  office: [
    "Ég gleymdi aðgangsorðinu mínu og get ekki skráð mig inn á neitt.",
    "Prentarinn minn er enn niðri og ég þarf að prenta skjöl.",
    "Samstarfsmaðurinn minn er veikur og ég verð að taka yfir verkefni hans að heiman.",
    "Hljóðsinnið okkar er biluð og ég get ekki mætt á fundi.",
    "Nettengingin mín er orðin svo lítil að ég get ekki unnið.",
    "Ég þarf að klára skýrslu áður en ég get mætt á fundinn.",
    "Sýnatökubeiðnin mín þarf afgreiðslu áður en ég get farið.",
    "Ég gleymdi mikilvægu skjali heima.",
    "Fundurinn minn var fluttur og ég þarf að endurskipuleggja daginn.",
    "Ég þarf tíma til að undirbúa mig fyrir kynningu sem er á morgun.",
    "Ég get ekki mætt fyrr en hljóðkerfi á heimilisskrifstofu er lagað.",
    "Ég er í langvarandi símtali með mikilvægan viðskiptavin.",
    "Stöðvunin sem kemur krefst þess að ég vinn heima.",
    "Ég þarf að ná í pöntun sem berst einungis í dag.",
    "Samantekt mín á gögnum er ekki lokið og mun taka lengri tíma.",
    "Kerfisvandamál í fyrirtækinu krefst þess að ég vinn heima.",
    "Ég er að bíða eftir samstillingu á mikilvægum skrám.",
    "Tæknilegar breytingar á kerfinu krefst þess að ég vinn heima í dag.",
    "Ég þarf að ljúka við endurskoðun skjala áður en ég get mætt.",
    "Fundurinn minn í morgun var afpantaður og ég þarf að endurskipuleggja.",
    "Ég þarf að vinna frá heima vegna kerfisuppfærslu.",
    "Reglubundnar úttektir þarfnast þess að ég sé heima í dag.",
    "Ég þarf tíma til að setja upp nýja hugbúnaðinn sem var sendur mér.",
    "Skráningarskjölin þarfnast sérstakrar úrvinnslu heima.",
    "Ég þarf að ganga frá mikilvægum samningum áður en ég fer.",
    "Lykilgögnin eru á heimastöðina og ég þarf að ganga frá þeim.",
    "Kerfisvandamál þarf tafarlausar lagfæringar.",
    "Ég er á sérstöku fjarfundi sem krefst heilveru dagsins.",
    "Ég þarf tíma til að fara í gegnum flókin gögn.",
    "Samstarfsmaðurinn minn þarf aðstoð við verkefni sem aðeins ég get aðstoðað við.",
    "Ég þarf að vinna á sérstaka skýrslu sem krefst einbeitingar.",
    "Ég er að bíða eftir mikilvægu samþykki áður en ég get haldið áfram.",
    "Kerfisvandamál þarf tafarlausar lagfæringar á heimilisskrifstofu.",
    "Ég þarf tíma til að undirbúa gögn fyrir fundinn á morgun.",
    "Ég er á sérstaka fjarfundi um mikilvægar breytingar.",
    "Ég þarf tíma til að setja upp nýtt tæki sem barst í dag.",
    "Skjöl sem þarf að undirrita eru einungis tiltæk heima.",
    "Ég þarf tíma til að fara í gegnum flókar kröfur.",
    "Kerfisvandamál þarfnast sérstakrar úrvinnslu.",
    "Ég þarf að vera á fjarfundi sem var kallaður saman í síðustu mínútu.",
    "Ég þarf tíma til að klára gögn sem eru nauðsynleg.",
    "Skýrslan mín þarf sérstaka endurskoðun áður en hún er send.",
    "Kerfisvandamál krefst þess að ég vinn heima í dag.",
    "Ég þarf að bíða eftir samstillingu á skrám sem þarf að klára.",
    "Ég er á sérstakri þjálfunarlotu sem krefst heilveru.",
    "Ég þarf tíma til að fara yfir stefnu í tengslum við verkefnið.",
    "Kerfisvandamál er stórt og þarf aðstoð sérfræðings.",
    "Ég þarf tíma til að ljúka við áætlun sem var umbeðin.",
    "Þýðingarverkefni þarfnast sérstakrar einbeitingar.",
    "Ég þarf tíma til að setja upp nýtt þjónustusamkomulag.",
    "Kerfisvandamál þarfnast tafarlausrar þjónustu.",
    "Ég þarf tíma til að vinna úr gögn sem barst um nóttina.",
    "Sérstök þjálfun þarfnast heilveru dagsins.",
    "Ég þarf tíma til að endurskoða reglur sem breyttust nýlega.",
    "Kerfisvandamál þarfnast sérstakrar þjónustu.",
    "Ég þarf tíma til að ganga frá kröfum sem eru á gjalddaga í dag.",
    "Ég er á sérstöku þjálfunarferli sem krefst heilveru.",
    "Ég þarf tíma til að fara í gegnum nýja skipulagsbreytingu.",
    "Kerfisvandamál þarfnast umhirðu og vandvirkni.",
    "Ég þarf tíma til að ganga frá sérstökum málefnum.",
    "Fjarfundur þarfnast sérstakrar þátttöku minnar.",
    "Ég þarf tíma til að ljúka við sérstaka greiningu.",
    "Kerfisvandamál þarfnast þess að ég sé heima.",
    "Ég þarf tíma til að ganga frá gögnum sem þarf í dag.",
    "Sérstak athugun þarfnast heilveru minnar.",
    "Ég þarf tíma til að fara í gegnum flókin mál.",
    "Kerfisvandamál krefst þess að ég hafi aðgang að heimanetinu.",
    "Ég þarf tíma til að klára mikilvægt verkefni.",
    "Sérstök rannsókn þarfnast einbeitingarinnar.",
    "Ég þarf tíma til að ganga frá kröfum sem er á gjalddaga.",
    "Kerfisvandamál þarfnast sérstakrar þjónustu.",
    "Ég þarf tíma til að ljúka við sérstaka skýrslu.",
    "Fjarfundur þarfnast þátttöku minnar.",
    "Ég þarf tíma til að vinna úr gögn sem barst.",
    "Kerfisvandamál þarfnast sérstakrar vandvirkni.",
    "Ég þarf tíma til að ganga frá sérstökum kröfum.",
    "Sérstakt þjálfunarferli þarfnast heilveru dagsins.",
    "Ég þarf tíma til að fara í gegnum nýja stefnu.",
    "Kerfisvandamál þarfnast sérstakrar þjónustu og tíma.",
    "Ég þarf tíma til að ganga frá flóknum gögnum.",
    "Sérstakur fjarfundur þarfnast þátttöku minnar.",
    "Ég þarf tíma til að klára sérstaka greiningu.",
    "Kerfisvandamál þarfnast þess að ég sé heima.",
    "Ég þarf tíma til að ganga frá mikilvægum skrám.",
    "Sérstök þjálfun þarfnast heilveru dagsins.",
    "Ég þarf tíma til að fara yfir breyttar kröfur.",
    "Kerfisvandamál krefst sérstakrar þjónustu.",
    "Ég þarf tíma til að ljúka við sérstaka úttekt.",
    "Fjarfundur þarfnast sérstakrar þátttöku.",
    "Ég þarf tíma til að vinna úr flóknum gögnum.",
    "Kerfisvandamál þarfnast sérstakrar þjónustu.",
    "Ég þarf tíma til að ganga frá sérstakri skýrslu.",
    "Sérstök rannsókn þarfnast heilveru dagsins.",
    "Ég þarf tíma til að fara í gegnum flókar kröfur.",
    "Kerfisvandamál þarfnast sérstakrar umhirðu.",
    "Ég þarf tíma til að ljúka við sérstökt verkefni.",
    "Fjarfundur þarfnast þátttöku minnar í dag.",
    "Ég þarf tíma til að ganga frá sérstaka málefnum.",
    "Kerfisvandamál krefst þess að ég vinn frá heima.",
    "Ég þarf tíma til að fara yfir nýjar kröfur.",
    "Sérstök þjálfunarlota þarfnast heilveru dagsins.",
    "Ég þarf tíma til að ganga frá sérstaka gögnum.",
    "Kerfisvandamál þarfnast tafarlausrar þjónustu.",
    "Ég þarf tíma til að klára sérstökt verkefni.",
    "Fjarfundur þarfnast sérstakrar þátttöku minnar.",
    "Ég þarf tíma til að vinna úr sérstaka gögnum.",
    "Kerfisvandamál þarfnast sérstakrar þjónustu.",
    "Ég þarf tíma til að ganga frá flóknum kröfum.",
    "Sérstök rannsókn þarfnast heilveru minnar.",
    "Ég þarf tíma til að fara í gegnum breytt skipulag.",
    "Kerfisvandamál krefst þess að ég vinn heima.",
    "Ég þarf tíma til að ljúka við sérstaka úttekt.",
    "Fjarfundur þarfnast þátttöku minnar.",
    "Ég þarf tíma til að ganga frá sérstaka skjölum.",
    "Kerfisvandamál þarfnast sérstakrar þjónustu.",
    "Ég þarf tíma til að vinna úr flóknum gögnum.",
    "Sérstök þjálfun þarfnast heilveru minnar.",
    "Ég þarf tíma til að fara yfir nýja stefnu.",
    "Kerfisvandamál þarfnast sérstakrar vandvirkni.",
    "Ég þarf tíma til að ganga frá sérstökum kröfum.",
    "Sérstakur fjarfundur þarfnast þátttöku minnar.",
    "Ég þarf tíma til að klára sérstaka greiningu.",
    "Kerfisvandamál þarfnast sérstakrar þjónustu.",
    "Ég þarf tíma til að ganga frá flóknum málefnum.",
    "Fjarfundur þarfnast sérstakrar þátttöku.",
    "Ég þarf tíma til að vinna úr sérstaka gögnum.",
    "Kerfisvandamál þarfnast þess að ég sé heima.",
    "Ég þarf tíma til að fara í gegnum sérstaka kröfur.",
    "Sérstök rannsókn þarfnast heilveru dagsins.",
    "Ég þarf tíma til að ljúka við sérstökt mál.",
    "Kerfisvandamál krefst sérstakrar þjónustu.",
    "Ég þarf tíma til að ganga frá breytta gögnum.",
  ],
  tech: [
    "Tölvan mín uppfærði sig og eyðilagði allt sem ég var að vinna að.",
    "Nettengingin mín brotnaði og ISP kemur ekki fyrr en seint í dag.",
    "Sýndarfundarþjónustan min er biluð og ég get ekki mætt á fundi.",
    "Ég þarf að endurstilla alla kerfislykla vegna öryggisbrests.",
    "Leynilykillinn minn á vinnustöðinni brotnaði.",
    "VPN þjónustan brotnaði og ég get ekki komist inn á vinnukerfin.",
    "Gagnasafnið sem ég vinn með gaf upp öll gögnin af gömlum uppfærslu vandamálum.",
    "Tölvan mín er í tímalínu og mun líklega taka heilan dag að laga.",
    "Hugbúnaðurinn sem ég nota er bilaður vegna óvæntrar uppfærslu.",
    "Myndavélarkamerur á þjónustufundi eru bilaðar og við getum ekki haldið fund.",
    "Netþjónninn sem ég er tengdur við bilaði og er niðri.",
    "Ég þarf að uppfæra vinnuumhverfi vegna öryggisbrests.",
    "Gagnageymslan mín er full og ég get ekki unnið.",
    "Kerfislykillinn minn er útrunninn og ég þarf nýjan.",
    "Forritið sem ég vinn með er niðri vegna kerfisuppfærslu.",
    "Nettengingin mín er svo hæg að ég get ekki unnið.",
    "Skjárinn minn brotnaði og ég þarf nýjan.",
    "Tölvan mín er hítuppáöl og kveiknar ekki.",
    "Hugbúnaðaruppfærslan brotnaði alla gagnasöfnin mín.",
    "Ég þarf að uppfæra öryggislykla vegna reglna.",
    "Vinnustraumur minn er bilaður vegna nýrrar útgáfu.",
    "Ég þarf að setja upp nýja vinnutól sem berst í dag.",
    "Netþjónninn minn er ekki að svara og ég þarf aðgang.",
    "Gagnageymslan er í viðhaldi og ég get ekki sótt gögn.",
    "Forritakerfið mitt brotnaði vegna rangrar uppfærslu.",
    "Ég þarf sérstakan aðgang að kerfinu sem er ekki tiltækur.",
    "Nettenging er svo lítil að myndafundur er ómögulegt.",
    "Tölvan mín þarf sérstakan viðhald sem er aðeins í boði í dag.",
    "Kerfið mitt bilaði vegna uppfærslu og þarf endurstillingu.",
    "Ég þarf sérstaka aðstoð við kerfisuppfærsluna.",
    "Nettengingin mín er biluð og þarf viðgerð.",
    "Skjárinn minn fór í draumasvefn og kemur ekki aftur.",
    "Tölvan mín er öll í uppfærslu sem tekur svo langan tíma.",
    "Lykilorðstjórninn minn brotnaði og ég man ekki lykilorðin.",
    "Kerfið mitt er ekki samhæft við nýja hugbúnaðinn.",
    "Ég þarf tíma til að laga stilla umhverfi vinnutólanna.",
    "Netþjónninn minn er niðri vegna kerfisuppfærslu.",
    "Gagnasöfnið mitt þarf sérstaka endurstillingu.",
    "Forritið mitt krefst sérstakrar stillingarinnar til að virka.",
    "Ég þarf sérstaka tíma til að setja upp nýtt vinnuumhverfi.",
    "Kerfið brotnaði og við þurfum tafarlausar lagfæringar.",
    "Ég þarf sérstaka aðstoð við kerfis-stillingu.",
    "Nettengingin mín krefst sérstakrar uppfærslu.",
    "Tölvan mín er í viðhaldi sem tekur heilan dag.",
    "Hugbúnaðaruppfærslan tók niður alla kerfisuppsetningu.",
    "Ég þarf sérstakan aðgang sem er ekki tiltækur nú.",
    "Gagnageymslan mín þarf sérstaka umhirðu.",
    "Kerfið mitt bilaði og þarf sérstaka endurstillingu.",
    "Ég þarf tíma til að vinna úr kerfisuppfærslu.",
    "Netþjónninn þarf sérstaka viðgerð.",
    "Tölvan mín þarf sérstaka viðhald.",
    "Forritið mitt þarf sérstaka stillingu.",
    "Ég þarf sérstakan tíma til að setja upp vinnuumhverfið.",
    "Kerfið krefst sérstakrar endurstillingar.",
    "Nettengingin krefst sérstakrar þjónustu.",
    "Tölvan mín er í sérstöku viðhaldi.",
    "Hugbúnaðurinn krefst sérstakrar uppfærslu.",
    "Ég þarf sérstakan aðgang að kerfinu.",
    "Gagnageymslan krefst sérstakrar umhirðu.",
    "Kerfið brotnaði vegna hugbúnaðarvandamáls.",
    "Ég þarf sérstaka aðstoð við tæknilega vandann.",
    "Netþjónninn krefst sérstakrar þjónustu.",
    "Tölvan mín krefst sérstakrar lagfæringar.",
    "Forritið krefst sérstakrar uppfærslu.",
    "Ég þarf sérstakan tíma til að laga kerfið.",
    "Kerfið krefst sérstakrar þjónustu.",
    "Nettengingin þarf sérstaka viðgerð.",
    "Tölvan mín þarf sérstaka endurstillingu.",
    "Hugbúnaðurinn þarf sérstaka uppfærslu.",
    "Ég þarf sérstakan aðgang til að vinna.",
    "Gagnageymslan þarf sérstaka umhirðu.",
    "Kerfið þarfnast sérstakrar þjónustu.",
    "Netþjónninn þarf sérstaka viðgerð.",
    "Tölvan mín þarf sérstaka stillingu.",
    "Forritið þarf sérstaka lagfæringu.",
    "Ég þarf sérstakan tíma til að setja upp nýtt umhverfi.",
    "Kerfið þarf sérstaka endurstillingu.",
    "Nettengingin þarf sérstaka þjónustu.",
    "Tölvan mín þarf sérstaka viðhald.",
    "Hugbúnaðurinn þarf sérstaka stillingu.",
    "Ég þarf sérstakan aðgang að vinnukerfinu.",
    "Gagnageymslan þarf sérstaka meðhöndlun.",
    "Kerfið krefst sérstakrar endurstillingar.",
    "Netþjónninn krefst sérstakrar umhirðu.",
    "Tölvan mín krefst sérstakrar þjónustu.",
    "Forritið krefst sérstakrar stillingar.",
    "Ég þarf sérstakan tíma til að laga tæknilegan vanda.",
    "Kerfið þarfnast tafarlausrar þjónustu.",
    "Nettengingin krefst sérstakrar viðgerðar.",
    "Tölvan mín krefst sérstakrar lagfæringar.",
    "Hugbúnaðurinn krefst sérstakrar uppfærslu.",
    "Ég þarf sérstakan aðgang þegar í stað.",
    "Gagnageymslan krefst tafarlausrar þjónustu.",
    "Kerfið bilaði og þarf sérstaka endurstillingu.",
    "Netþjónninn bilaði og þarf sérstaka lagfæringu.",
    "Tölvan mín bilaði og þarf sérstaka viðgerð.",
    "Forritið bilaði og þarf sérstaka uppfærslu.",
    "Ég þarf sérstaka þjálfun á nýjum kerfisverkfærum.",
    "Kerfið bilaði og þarf sérstaka þjónustu.",
    "Nettengingin bilaði og þarf sérstaka viðgerð.",
    "Tölvan mín bilaði og þarf sérstaka stillingu.",
    "Hugbúnaðurinn bilaði og þarf sérstaka lagfæringu.",
    "Ég þarf sérstaka aðgang að tæknilega kerfinu.",
    "Gagnageymslan bilaði og þarf sérstaka þjónustu.",
    "Kerfið krefst tafarlausrar endurstillingar.",
    "Netþjónninn krefst tafarlausrar þjónustu.",
    "Tölvan mín krefst tafarlausrar lagfæringar.",
    "Forritið krefst tafarlausrar uppfærslu.",
    "Ég þarf sérstaka tíma til að leysa tæknivandann.",
    "Kerfið þarf tafarlausar lagfæringar.",
    "Nettengingin þarf tafarlausar lagfæringar.",
    "Tölvan mín þarf tafarlausar lagfæringar.",
    "Hugbúnaðurinn þarf tafarlausar lagfæringar.",
    "Ég þarf sérstaka tíma til að laga kerfið.",
    "Gagnageymslan þarf tafarlausar lagfæringar.",
    "Kerfið bilaði vegna hugbúnaðaruppfærslu.",
    "Netþjónninn bilaði vegna kerfisuppfærslu.",
    "Tölvan mín bilaði vegna hugbúnaðarvandamáls.",
    "Forritið bilaði vegna kerfisuppfærslu.",
    "Ég þarf sérstaka aðgang að kerfinu þegar í stað.",
    "Kerfið þarf sérstaka endurstillingu þegar í stað.",
    "Nettengingin þarf sérstaka þjónustu þegar í stað.",
    "Tölvan mín þarf sérstaka viðgerð þegar í stað.",
    "Hugbúnaðurinn þarf sérstaka uppfærslu þegar í stað.",
    "Ég þarf sérstaka þjálfun á nýjum vinnuverkfærum.",
    "Gagnageymslan þarf sérstaka meðhöndlun þegar í stað.",
    "Kerfið krefst sérstakrar þjónustu þegar í stað.",
    "Netþjónninn krefst sérstakrar viðgerðar þegar í stað.",
    "Tölvan mín krefst sérstakrar lagfæringar þegar í stað.",
    "Forritið krefst sérstakrar stillingar þegar í stað.",
    "Ég þarf sérstakan tíma til að setja upp nýja tæki.",
    "Kerfið krefst sérstakrar endurstillingar þegar í stað.",
    "Nettengingin krefst sérstakrar viðgerðar þegar í stað.",
    "Tölvan mín krefst sérstakrar uppfærslu þegar í stað.",
    "Hugbúnaðurinn krefst sérstakrar lagfæringar þegar í stað.",
    "Ég þarf sérstaka aðgang að vinnukerfinu þegar í stað.",
    "Gagnageymslan krefst sérstakrar þjónustu þegar í stað.",
    "Kerfið bilaði og krefst tafarlausrar lagfæringar.",
    "Netþjónninn bilaði og krefst tafarlausrar þjónustu.",
    "Tölvan mín bilaði og krefst tafarlausrar viðgerðar.",
    "Forritið bilaði og krefst tafarlausrar uppfærslu.",
  ],
  motorcycle: [
    "Mótorhjólið mitt neitar að kveikja — rafgeymirinn er dauður.",
    "Hjólbarinn á mótorhjólinu mínu spratt á leiðinni.",
    "Bremsan á mótorhjólinu mínu er laus og þarf viðgerð.",
    "Kveikjulykillinn á mótorhjólinu mínu brotnaði af.",
    "Mótorhjólið mitt er í þjónustu og kemur ekki fyrr en seint í dag.",
    "Ég féll af mótorhjólinu mínu en er blessunarlega lífsönn.",
    "Keðjan á mótorhjólinu mínu brotnaði á miðri leið.",
    "Olían lak úr mótorhjólinu mínu og ég þarf viðgerð.",
    "Mótorhjólið mitt er frosið við í bílskúrnum.",
    "Vélarhjólið mitt fer í villur og þarf greiningu.",
    "Mótorhjólið mitt er í viðhaldi sem tafðist.",
    "Kveikjarinn á mótorhjólinu mínu þarf endurnýjun.",
    "Mótorhjólið mitt hefur rafmagnsbilanir sem þarf að skoða.",
    "Ég þarf sérstaka verkfæri til að laga mótorhjólið sem ég hef ekki.",
    "Mótorhjólið mitt þarf sérstaka smurningu sem er aðeins í boði í verkstæði.",
    "Keðjan er of laus á mótorhjólinu og þarf stillingu.",
    "Stýri á mótorhjólinu er biluð og get ekki stjórnað því.",
    "Hjólabarnar þurfa endurnýjun áður en ég get ekið.",
    "Mótorhjólið mitt þarf sérstakan skoðun vegna einkenna.",
    "Ljósin á mótorhjólinu eru biluð og ég má ekki aka án þeirra.",
    "Mótorhjólið mitt þarf sérstaka viðgerð sem tók lengri tíma.",
    "Bremsuolían á mótorhjólinu þarf endurnýjun.",
    "Mótorhjólið mitt er niðri vegna rafmagnsbilanar.",
    "Hjólbararnir eru of gömlu til að aka örugglega.",
    "Mótorhjólið mitt þarf sérstaka þjónustu í dag.",
    "Keðjan á mótorhjólinu þarf viðgerð.",
    "Mótorhjólið mitt þarf sérstaka stillingu.",
    "Olían á mótorhjólinu þarf endurnýjun.",
    "Mótorhjólið mitt er í þjónustu sem tekur heilan dag.",
    "Vélin á mótorhjólinu gengur ekki sem skyldi.",
    "Mótorhjólið mitt þarf sérstaka skoðun.",
    "Ljósin á mótorhjólinu þarf lagfæringu.",
    "Mótorhjólið mitt þarf sérstaka viðhald.",
    "Keðjan á mótorhjólinu þarf stillingu.",
    "Mótorhjólið mitt þarf sérstaka olíuskipti.",
    "Bremsan á mótorhjólinu þarf lagfæringu.",
    "Mótorhjólið mitt þarf sérstaka rafmagnsviðgerð.",
    "Hjólabarnar á mótorhjólinu þarf endurnýjun.",
    "Mótorhjólið mitt þarf sérstaka skoðun á vélinni.",
    "Kveikjarinn á mótorhjólinu þarf viðgerð.",
    "Mótorhjólið mitt þarf sérstaka þjónustu.",
    "Stýrið á mótorhjólinu þarf lagfæringu.",
    "Mótorhjólið mitt þarf sérstaka viðhald á keðju.",
    "Olían á mótorhjólinu þarf endurnýjun þegar í stað.",
    "Mótorhjólið mitt þarf sérstaka skoðun á rafmagni.",
    "Bremsuolían á mótorhjólinu þarf endurnýjun þegar í stað.",
    "Mótorhjólið mitt þarf sérstaka viðgerð á vélinni.",
    "Keðjan á mótorhjólinu þarf viðgerð þegar í stað.",
    "Mótorhjólið mitt þarf sérstaka þjónustu á stýri.",
    "Ljósin á mótorhjólinu þarf lagfæringu þegar í stað.",
    "Mótorhjólið mitt þarf sérstaka skoðun á bremsum.",
    "Hjólabarnar á mótorhjólinu þarf endurnýjun þegar í stað.",
    "Mótorhjólið mitt þarf sérstaka viðhald á ljósum.",
    "Kveikjarinn á mótorhjólinu þarf viðgerð þegar í stað.",
    "Mótorhjólið mitt þarf sérstaka þjónustu á olíu.",
    "Stýrið á mótorhjólinu þarf lagfæringu þegar í stað.",
    "Mótorhjólið mitt þarf sérstaka viðgerð á bremsum.",
    "Olían á mótorhjólinu þarf sérstaka endurnýjun.",
    "Mótorhjólið mitt þarf sérstaka skoðun á stýri.",
    "Bremsan á mótorhjólinu þarf sérstaka lagfæringu.",
    "Mótorhjólið mitt þarf sérstaka viðhald á kveikjara.",
    "Keðjan á mótorhjólinu þarf sérstaka stillingu.",
    "Mótorhjólið mitt þarf sérstaka þjónustu á vélinni.",
    "Ljósin á mótorhjólinu þarf sérstaka lagfæringu.",
    "Mótorhjólið mitt þarf sérstaka skoðun á olíu.",
    "Hjólabarnar á mótorhjólinu þarf sérstaka endurnýjun.",
    "Mótorhjólið mitt þarf sérstaka viðgerð á keðju.",
    "Kveikjarinn á mótorhjólinu þarf sérstaka viðgerð.",
    "Mótorhjólið mitt þarf sérstaka þjónustu á bremsum.",
    "Stýrið á mótorhjólinu þarf sérstaka lagfæringu.",
    "Mótorhjólið mitt þarf sérstaka viðhald á hjólabörum.",
    "Olían á mótorhjólinu þarf tafarlausar endurnýjun.",
    "Mótorhjólið mitt þarf sérstaka skoðun þegar í stað.",
    "Bremsuolían á mótorhjólinu þarf sérstaka endurnýjun.",
    "Mótorhjólið mitt þarf sérstaka viðgerð þegar í stað.",
    "Keðjan á mótorhjólinu þarf tafarlausar viðgerð.",
    "Mótorhjólið mitt þarf sérstaka þjónustu þegar í stað.",
    "Ljósin á mótorhjólinu þarf tafarlausar lagfæringar.",
    "Mótorhjólið mitt þarf sérstaka viðhald þegar í stað.",
    "Kveikjarinn á mótorhjólinu þarf tafarlausar viðgerð.",
    "Mótorhjólið mitt þarf sérstaka þjónustu á ljósum.",
    "Stýrið á mótorhjólinu þarf tafarlausar lagfæringu.",
    "Mótorhjólið mitt þarf sérstaka viðgerð á stýri.",
    "Hjólabarnar á mótorhjólinu þarf tafarlausar endurnýjun.",
    "Mótorhjólið mitt þarf sérstaka skoðun á keðju.",
    "Olían á mótorhjólinu þarf sérstaka þjónustu.",
    "Mótorhjólið mitt þarf sérstaka viðhald á vélinni.",
    "Bremsan á mótorhjólinu þarf tafarlausar lagfæringu.",
    "Mótorhjólið mitt þarf sérstaka skoðun á kveikjara.",
    "Keðjan á mótorhjólinu þarf tafarlausar stillingu.",
    "Mótorhjólið mitt þarf sérstaka þjónustu á hjólabörum.",
    "Ljósin á mótorhjólinu þarf sérstaka viðgerð.",
    "Mótorhjólið mitt þarf sérstaka skoðun á stýri.",
    "Kveikjarinn á mótorhjólinu þarf sérstaka lagfæringu.",
    "Mótorhjólið mitt þarf sérstaka þjónustu á keðju.",
    "Stýrið á mótorhjólinu þarf sérstaka viðgerð.",
    "Mótorhjólið mitt þarf sérstaka skoðun á ljósum.",
  ],
};

function generateExcuses() {
  const allExcuses = [];
  let id = 1;

  for (const [category, excuses] of Object.entries(categories)) {
    for (const text of excuses) {
      allExcuses.push({ id, category, text });
      id++;
    }
  }

  // Pad to exactly 1001 using round-robin across categories if needed
  const catNames = Object.keys(categories);
  const catArrays = Object.values(categories);
  let fillerCatIdx = 0;
  let fillerItemIdx = 0;

  while (allExcuses.length < 1001) {
    const catName = catNames[fillerCatIdx % catNames.length];
    const catList = catArrays[fillerCatIdx % catArrays.length];
    const text = catList[fillerItemIdx % catList.length];
    allExcuses.push({ id, category: catName, text });
    id++;
    fillerItemIdx++;
    if (fillerItemIdx % catList.length === 0) fillerCatIdx++;
  }

  return allExcuses.slice(0, 1001);
}

const excuses = generateExcuses();
const outputPath = require('path').join(__dirname, '..', 'assets', 'excuses_is.json');

require('fs').writeFileSync(outputPath, JSON.stringify(excuses, null, 2), 'utf8');
console.log(`✅  Generated ${excuses.length} Icelandic excuses → ${outputPath}`);
