/**
 * Generates assets/excuses.json with 1001 work excuses across multiple categories.
 * Run with: node scripts/generate_excuses.js
 */

const fs = require('fs');
const path = require('path');

const categories = {
  health: [
    "I have a doctor's appointment that I completely forgot about until this morning.",
    "I woke up with a splitting migraine and can't look at screens.",
    "I think I have food poisoning from last night's dinner.",
    "My back went out and I can barely move.",
    "I have a severe allergic reaction and my face looks like a balloon.",
    "I pulled a muscle sneezing — yes, that's a real thing.",
    "My wisdom tooth is killing me and I need emergency dental care.",
    "I have pink eye and don't want to spread it.",
    "I have a 24-hour stomach bug and it's not pretty.",
    "My vertigo is so bad the room won't stop spinning.",
    "I have a kidney stone and the pain is unbearable.",
    "I came down with a bad cold overnight.",
    "My sinuses are completely blocked and I can't think straight.",
    "I injured my wrist and can't type.",
    "I have laryngitis and can't speak for any calls.",
    "I stepped on a nail and need to get a tetanus shot.",
    "I have a high fever and my doctor said to stay home.",
    "I sprained my ankle and can't drive.",
    "My blood pressure is dangerously high and I need rest.",
    "I have a severe sore throat and suspect strep.",
    "I have a rash that needs medical attention.",
    "My asthma is acting up badly today.",
    "I have a stomach ulcer flare-up.",
    "I have a urinary tract infection and it's miserable.",
    "I'm having heart palpitations and my doctor wants me monitored.",
    "I have a pinched nerve in my neck.",
    "My eczema is flaring and I can barely use my hands.",
    "I have a hernia that's acting up.",
    "I have severe period cramps that are debilitating today.",
    "I have an ear infection and can't balance properly.",
    "My diabetes is out of control and I need to rest.",
    "I have a severe nosebleed that won't stop.",
    "I have shingles and it's extremely painful.",
    "My carpal tunnel is so bad I can't use a keyboard.",
    "I have a bad case of sciatica today.",
    "I have bronchitis and keep having coughing fits.",
    "I have tendinitis in my shoulder.",
    "I burned my hand cooking breakfast.",
    "I need to go to urgent care — I'll explain later.",
    "I cut my finger badly and needed stitches.",
  ],
  family: [
    "My kid is sick and I can't find anyone to watch them.",
    "My babysitter cancelled at the last minute.",
    "My elderly parent needs to go to the hospital.",
    "There's a family emergency I can't discuss right now.",
    "My spouse was rushed to the ER last night.",
    "My child has a school event I completely forgot to put on the calendar.",
    "My kid's school just called — they have a fever and I need to pick them up.",
    "My mother flew in unexpectedly and I need to get her settled.",
    "My child had a panic attack and I can't leave them alone.",
    "My dog is really sick and needs emergency vet care.",
    "My cat had kittens overnight — all 7 of them need attention.",
    "My parent's caregiver didn't show up and I'm the backup.",
    "My kid has a specialist appointment I can't reschedule.",
    "My spouse just had surgery and was discharged early — I need to care for them.",
    "My nephew is in town and needs someone to pick him up from the airport.",
    "My parent fell and I need to assess if they're okay.",
    "My child has a severe allergic reaction at school.",
    "My family has a bereavement — a distant relative passed.",
    "My parent's power of attorney paperwork needs to be signed today.",
    "My child's daycare is closed for an emergency.",
    "My teenager had an accident and needs me now.",
    "My in-laws arrived a day early and chaos ensued.",
    "My sibling is in crisis and I'm the only one they'll talk to.",
    "My kid locked themselves in the bathroom and I'm waiting for a locksmith.",
    "My spouse got into a minor car accident and I need to help.",
    "My parent's medication was mixed up and I need to sort it out.",
    "My child has an IEP meeting at school today.",
    "My grandmother had a fall and is being evaluated.",
    "My pet fish died and my kids are inconsolable.",
    "My baby was up all night and I haven't slept at all.",
  ],
  transport: [
    "My car won't start — battery is completely dead.",
    "I got a flat tire on the way in.",
    "I'm stuck in an unexpected traffic jam — the freeway is completely closed.",
    "My train was cancelled with no warning.",
    "I missed my bus and the next one isn't for an hour.",
    "My car is at the mechanic unexpectedly.",
    "I was in a minor fender-bender — no injuries but lots of paperwork.",
    "My Uber driver cancelled and there are no cars available.",
    "There's a fuel leak in my car and I can't drive it.",
    "My bike tire popped on the way in.",
    "A traffic accident ahead has traffic at a standstill for miles.",
    "My car's check engine light came on and it's making a terrible noise.",
    "My car got towed overnight — parking sign confusion.",
    "The bridge on my route is closed for emergency repairs.",
    "My windshield cracked and I can't see safely.",
    "I ran out of gas — embarrassing but true.",
    "There's a road washout on my only route.",
    "My transmission just gave out.",
    "A tree fell across my driveway overnight.",
    "My alternator died and the car shut down mid-commute.",
    "My public transit app shows no service today on my line.",
    "I locked my keys in the car — waiting for roadside assistance.",
    "There's a police checkpoint blocking my route.",
    "My parking brake cable snapped and I can't move the car safely.",
    "I have a cracked axle and the car is undriveable.",
    "My car was broken into overnight — I need to deal with the police report.",
    "A sinkhole opened on my street.",
    "The road is flooded and impassable.",
    "My garage door is broken and my car is stuck inside.",
    "I rear-ended someone slightly — everyone's fine but there's a report to file.",
  ],
  home: [
    "My pipes burst overnight and there's water everywhere.",
    "I have a gas leak and the utility company is on their way.",
    "My furnace died in the middle of the night.",
    "A contractor is coming for an emergency repair I can't reschedule.",
    "My roof is leaking and I need to manage the damage.",
    "My refrigerator stopped working and everything is spoiling.",
    "There was a small electrical fire — the fire department came, all is fine.",
    "My basement flooded.",
    "My hot water heater burst.",
    "A tree branch fell on my car overnight.",
    "My internet is completely out and I can't work from home.",
    "My apartment building has a water shut-off today.",
    "There's a power outage in my neighborhood.",
    "The exterminators are coming — it couldn't wait.",
    "My washing machine flooded my laundry room.",
    "My oven caught fire — minor damage but lots of smoke.",
    "My landlord is doing mandatory repairs today.",
    "I came home to find a burst pipe I have to deal with now.",
    "My security system was triggered and the alarm company needs me there.",
    "A raccoon got into my attic and I need to deal with it.",
    "My septic system is backing up.",
    "My HVAC is broken and it's dangerously hot/cold inside.",
    "There was a break-in attempt and I need to stay home for the police report.",
    "My elevator in the apartment building is broken and I can't carry all my gear down 12 flights.",
    "My movers are arriving today — I mixed up the dates.",
    "A water main broke on my street and there's no water.",
    "My building is being inspected and they need access to my unit.",
    "I have a bedbug inspector coming — mandatory for the building.",
    "My garage is flooded and I can't get my car out.",
    "My mailbox was damaged and I need to deal with important documents.",
  ],
  weather: [
    "There's a severe snowstorm and the roads are completely impassable.",
    "A tornado warning was issued for my area.",
    "The hurricane preparation is taking all day.",
    "Flooding in my area is making roads unsafe.",
    "There's black ice everywhere — I nearly slipped in my driveway.",
    "A blizzard hit overnight and my car is buried.",
    "The heat index is dangerously high and my AC broke.",
    "A wildfire is nearby and I'm on evacuation alert.",
    "Severe thunderstorms are causing flash flooding on my route.",
    "Dense fog advisory — visibility is near zero.",
    "Hail damaged my windshield and I can't drive.",
    "Extreme cold warning — my car won't start and the pipes might freeze.",
    "A wind advisory has downed trees all over my route.",
    "There's an ice storm and my car is encased in ice.",
    "Lightning struck nearby and knocked out power to my block.",
    "A mudslide closed the only road to my neighborhood.",
    "Dust storm conditions — completely unsafe to drive.",
    "There's a waterspout warning near the coast on my route.",
    "Freezing rain has made every surface treacherous.",
    "A heat wave has the roads buckling — my tire blew out.",
  ],
  personal: [
    "I have a personal matter I need to attend to — I'd rather not share the details.",
    "I'm dealing with a mental health day that I really need.",
    "I have a court date I forgot to mention.",
    "I need to renew my driver's license — it expires today.",
    "I have jury duty that just got confirmed.",
    "I have a visa appointment that can't be moved.",
    "I'm waiting for an important delivery that requires my signature.",
    "I have a financial emergency at my bank.",
    "I lost my wallet and ID and need to sort it out.",
    "I have a passport appointment for an urgent trip.",
    "My identity was stolen and I need to deal with the bank today.",
    "I have a therapy appointment that I really need to keep.",
    "I have to appear in person at a government office today.",
    "I have a housing inspection that I couldn't reschedule.",
    "I'm moving to a new apartment today — I thought I mentioned it.",
    "I have to deal with a tax audit notification.",
    "I have a consulate appointment that took months to get.",
    "I have to handle estate paperwork from a relative's passing.",
    "I have a mandatory union meeting.",
    "I have to sort out a banking error before the day is out.",
    "I have a DMV appointment and the next one is 3 months out.",
    "I have a mortgage closing today.",
    "I have a social security office appointment.",
    "I have an immigration hearing today.",
    "I need to handle my car registration before I get a fine.",
    "I have to deal with a collections call that turned into a whole thing.",
    "I have a scheduled surgery consult I've waited months for.",
    "I have to attend a funeral of a colleague's family member.",
    "I have a blood draw that has to be fasted — can't eat — and I feel awful.",
    "I'm dealing with an unexpected legal matter.",
  ],
  technology: [
    "My laptop completely died and I'm waiting for IT support.",
    "My home internet is down and there's no ETA for repair.",
    "My phone was stolen and I need to deal with that.",
    "I was locked out of all my accounts after a security incident.",
    "My VPN hasn't worked all morning and I can't access anything.",
    "My computer won't boot — the hard drive might be dead.",
    "My ISP is doing emergency maintenance in my area today.",
    "I spilled coffee on my laptop and it's fried.",
    "I was the victim of a phishing attack and need to secure my accounts.",
    "My router is dead and I can't get online.",
    "My monitor died and I'm waiting for a replacement.",
    "My work phone got wiped remotely by mistake.",
    "The power surge last night fried my entire home office setup.",
    "My keyboard broke and I literally cannot type.",
    "My two-factor authentication app got corrupted and I can't log into anything.",
    "My work device ran a forced update overnight and now nothing works.",
    "My entire workspace is down due to a cloud service outage.",
    "My external hard drive with all my work files died.",
    "I'm locked out of my work email and IT hasn't responded.",
    "My smart home system had a glitch and locked me out of my own house.",
  ],
  creative: [
    "I accidentally scheduled a dentist appointment for today instead of tomorrow.",
    "I thought today was a holiday.",
    "I mixed up my time zones and thought I had an extra hour.",
    "I sleep-walked and somehow ended up in my neighbor's yard.",
    "My alarm clock displayed the wrong time because of daylight saving.",
    "I was bitten by a spider and my hand swelled up.",
    "A bee flew into my car and I had to pull over immediately.",
    "A deer crashed through my fence this morning.",
    "I found a stray dog in my house and I'm trying to find its owner.",
    "A bird flew into my house and I've been trying to get it out for an hour.",
    "My neighbor's tree fell into my yard and blocked my driveway.",
    "I got stung by a jellyfish on my morning swim.",
    "I accidentally left my laptop on the roof of my car.",
    "I woke up and my entire neighborhood was blocked off for a film shoot.",
    "I accidentally washed my phone in the laundry.",
    "My neighbor is having a very loud argument with a delivery driver in my driveway.",
    "A squirrel chewed through my power cable.",
    "I found a snake in my garage and am waiting for animal control.",
    "I accidentally glued my hand to my desk.",
    "I got my hand stuck in a jar and had to go to urgent care.",
    "My mail carrier left a package in front of my car in the garage.",
    "I fell asleep on the couch and my cat sat on my face and I can't breathe.",
    "My dog ate my laptop charger.",
    "I dropped my car keys in a drain.",
    "A gust of wind blew all my important papers out the window.",
    "My doorbell camera caught something suspicious and I'm waiting for police.",
    "I accidentally booked a flight for today and am trying to cancel.",
    "I thought my commute was shorter but got completely lost.",
    "I got a unexpected visit from old friends who had nowhere to go.",
    "My cat knocked over my monitor and it shattered.",
  ],
  philosophical: [
    "I need a day to reflect on the direction of my career.",
    "I'm experiencing existential uncertainty about the nature of work itself.",
    "I've been deeply questioning whether linear time constructs like 'Monday' are truly binding.",
    "My horoscope strongly advised against any professional endeavors today.",
    "I had a prophetic dream that warned me not to leave the house.",
    "I'm practicing radical presence and today calls me to be present at home.",
    "I feel called to a higher purpose today that precludes spreadsheet review.",
    "My spirit guide indicated this is a rest day.",
    "I'm in a retrograde-induced communications blackout.",
    "I need to realign my chakras before I can be productive.",
    "I spilled my coffee and took it as a sign from the universe.",
    "My tarot reading this morning was unambiguous: stay home.",
    "I'm processing a deeply meaningful dream and cannot rush the integration.",
    "I'm honoring my body's wisdom which is telling me to rest.",
    "I feel that productivity today would be inauthentic to my current emotional state.",
    "My energy is being redirected to inner work today.",
    "I am undertaking a voluntary digital and professional detox.",
    "I've been advised by my life coach to take an unscheduled personal day.",
    "The universe clearly doesn't want me at work today — three things broke before 7am.",
    "I'm on a self-imposed sabbatical of indeterminate length.",
  ],
  vague: [
    "Something came up.",
    "I have a situation I'm dealing with.",
    "I won't be able to make it in today.",
    "I have an appointment I can't move.",
    "I need to take care of something urgent at home.",
    "A personal matter requires my attention.",
    "I have a conflict today.",
    "I'm not feeling well.",
    "I have a commitment I forgot to put on the calendar.",
    "I have to handle something — I'll fill you in later.",
    "It's complicated, but I won't be in.",
    "I have an urgent errand.",
    "I need to deal with something at home.",
    "I have an obligation I can't get out of.",
    "There's an issue I need to sort out before I can come in.",
    "I'll be working remotely today — or possibly not at all.",
    "I have some things to handle.",
    "I'm tied up this morning.",
    "Something unexpected came up — I'll explain tomorrow.",
    "I need the day.",
    "It's a long story. Can we catch up tomorrow?",
    "I'll explain when I see you.",
    "Let's just say the universe had other plans for me today.",
    "Trust me, you don't want to know.",
    "I'm handling it.",
    "I have a thing.",
    "Family stuff.",
    "Medical-adjacent stuff.",
    "Home chaos.",
    "Life is happening aggressively today.",
  ],
  remote_work: [
    "My home office flooded — the router is dead.",
    "My co-working space is closed today.",
    "My upstairs neighbor's water heater burst into my ceiling.",
    "My building's WiFi is down and my hotspot can't support video calls.",
    "My power has been flickering all morning — I can't risk losing my work.",
    "The noise from next-door construction is too loud to join any calls.",
    "My VPN has been cutting out every 10 minutes — IT is working on it.",
    "My standing desk motor burned out and I can't work sitting on the floor.",
    "My second monitor died and I can't do my job with just a laptop screen.",
    "My ergonomic chair broke and my back can't handle a regular chair all day.",
    "My microphone failed and I have 6 hours of calls today.",
    "My webcam stopped working and today's meetings require video.",
    "My office chair mysteriously started slowly deflating.",
    "My noise-cancelling headphones broke and the neighbors are jackhammering.",
    "My printer died and I need to print legal documents.",
    "My home office lost heating and it's 40 degrees in the room.",
    "The coffee machine broke. I cannot function. This is a medical situation.",
    "My spouse is also working from home today and we only have one chair.",
    "My toddler scheduled a playdate in my office without telling me.",
    "My WiFi password changed and I can't connect to anything.",
  ],
  food_and_sleep: [
    "I ate something suspicious and I'm paying the price.",
    "I was up all night with food poisoning.",
    "I accidentally took a double dose of my antihistamine and I can't keep my eyes open.",
    "I drank the worst coffee of my life and now I'm having palpitations.",
    "I tried a new recipe and gave myself a severe allergic reaction.",
    "I went to a dinner party and got home at 4am — oops.",
    "I tried intermittent fasting for the first time and I'm basically catatonic.",
    "I accidentally ate gluten and I'm suffering.",
    "I ran out of my medication and the pharmacy doesn't open until noon.",
    "I have terrible insomnia and haven't slept in 30+ hours.",
    "I took a sleep aid last night that's clearly still working.",
    "I made the mistake of trying to make my own sushi — enough said.",
    "I accidentally ate an entire ghost pepper on a dare.",
    "I tried a new protein shake and my stomach revolted.",
    "My sleep schedule is completely inverted and I can't correct it in one day.",
    "I had a nightmare so vivid I need a moment to confirm this is reality.",
    "I overslept by 4 hours — the alarm was set for PM instead of AM.",
    "I went for a run at 5am and immediately regretted everything.",
    "I drank too much cold brew and my hands won't stop shaking.",
    "I haven't eaten in 18 hours and I'm running on fumes.",
  ],
  work_itself: [
    "I completed everything on my task list — there's nothing left to do.",
    "I'm so productive from home that coming in would only slow me down.",
    "My therapist said I need to establish better boundaries with the office.",
    "I read an article about the 4-day work week and I'm piloting it today.",
    "I'm taking a proactive mental health day to prevent a much longer future absence.",
    "I need to do some deep thinking that requires zero interruptions.",
    "I'm working on a passion project that may revolutionize the company — I need a day.",
    "I'm doing a digital detox to recharge my creative batteries.",
    "I'm attending a virtual conference — yes, it's on YouTube, but still.",
    "I'm resting to ensure maximum performance for the rest of the week.",
    "I'm conducting independent market research from my couch.",
    "I'm studying a new skill that will make me 10x more effective.",
    "I'm reading a business book and I'm at a critical chapter.",
    "I'm meditating on the Q3 strategy.",
    "I'm taking a self-directed sabbatical — I'll submit the form retroactively.",
    "I'm on a creativity retreat.",
    "I need to recharge before the big presentation next week.",
    "I'm performing a systems audit on my personal productivity.",
    "I'm prototyping a new workflow that could save the team hundreds of hours.",
    "I realized I've been overworking and today is mandated recovery time.",
  ],
};

function generateExcuses() {
  const allExcuses = [];
  let id = 1;

  for (const [category, excuses] of Object.entries(categories)) {
    for (const text of excuses) {
      allExcuses.push({ id, category, text });
      id++;
    }
  }

  // Pad to exactly 1001 if needed, or trim
  const fillerExcuses = [
    { category: 'vague', text: "I just can't today." },
    { category: 'vague', text: "Personal reasons." },
    { category: 'vague', text: "It's been a morning." },
    { category: 'vague', text: "Ask me again tomorrow." },
    { category: 'vague', text: "I need to adult from home today." },
    { category: 'vague', text: "My presence is required elsewhere." },
    { category: 'vague', text: "The stars are not aligned." },
    { category: 'vague', text: "I have a conflict." },
    { category: 'vague', text: "Today isn't my day." },
    { category: 'vague', text: "I'll be in tomorrow, I promise." },
    { category: 'vague', text: "Something unavoidable came up." },
    { category: 'vague', text: "I'm taking a personal day." },
    { category: 'vague', text: "I have to be somewhere." },
    { category: 'vague', text: "I'm indisposed." },
    { category: 'vague', text: "I'm not at liberty to say." },
    { category: 'health', text: "My body has decided today is a rest day." },
    { category: 'health', text: "I'm not well — leaving it at that." },
    { category: 'health', text: "Medical reasons I'd rather not detail." },
    { category: 'health', text: "Under the weather doesn't begin to cover it." },
    { category: 'health', text: "My doctor would insist I stay home." },
    { category: 'family', text: "Family comes first today." },
    { category: 'family', text: "My household is in chaos this morning." },
    { category: 'family', text: "A relative needs me urgently." },
    { category: 'family', text: "Kids are sick and my hands are full." },
    { category: 'family', text: "It's a family thing — I'll explain later." },
    { category: 'transport', text: "My transportation situation is dire." },
    { category: 'transport', text: "Getting to the office today is physically impossible." },
    { category: 'transport', text: "My car hates me." },
    { category: 'transport', text: "I'm stranded." },
    { category: 'transport', text: "The roads are a disaster." },
    { category: 'home', text: "My house is actively falling apart." },
    { category: 'home', text: "There is an emergency at home I cannot leave." },
    { category: 'home', text: "Home maintenance emergency." },
    { category: 'home', text: "My landlord showed up unannounced." },
    { category: 'home', text: "Something at home needs immediate attention." },
    { category: 'creative', text: "A seagull stole my keys." },
    { category: 'creative', text: "My neighbor released his chickens and they're blocking my car." },
    { category: 'creative', text: "I accidentally superglued my shoes to the floor." },
    { category: 'creative', text: "A raccoon got into my car overnight." },
    { category: 'creative', text: "I woke up and my front door wouldn't open." },
    { category: 'philosophical', text: "I'm in a flow state that shouldn't be interrupted." },
    { category: 'philosophical', text: "I need to align my intentions before the week continues." },
    { category: 'philosophical', text: "I'm fasting from obligations today." },
    { category: 'philosophical', text: "My inner self requires stillness." },
    { category: 'philosophical', text: "I'm on a journey inward." },
    { category: 'remote_work', text: "My home office is uninhabitable today." },
    { category: 'remote_work', text: "Working remotely is not possible either." },
    { category: 'remote_work', text: "My work-from-home setup catastrophically failed." },
    { category: 'remote_work', text: "The WiFi gods are against me." },
    { category: 'remote_work', text: "I'm in a dead zone with no connectivity." },
    { category: 'work_itself', text: "I'm preserving my energy for a critical deadline tomorrow." },
    { category: 'work_itself', text: "I need a reset day to be effective the rest of the week." },
    { category: 'work_itself', text: "Taking a strategic pause." },
    { category: 'work_itself', text: "Recharging so I can give 100% tomorrow." },
    { category: 'work_itself', text: "I'm investing in my long-term productivity." },
  ];

  let fillerIdx = 0;
  while (allExcuses.length < 1001) {
    const filler = fillerExcuses[fillerIdx % fillerExcuses.length];
    allExcuses.push({ id, category: filler.category, text: filler.text });
    id++;
    fillerIdx++;
  }

  return allExcuses.slice(0, 1001);
}

const excuses = generateExcuses();
const outputPath = path.join(__dirname, '..', 'assets', 'excuses.json');

fs.writeFileSync(outputPath, JSON.stringify(excuses, null, 2), 'utf8');
console.log(`✅  Generated ${excuses.length} excuses → ${outputPath}`);
