/**
 * Generates assets/excuses.json with 1001 work excuses across the app categories:
 *   funny | believable | chaotic | dark | office | tech | motorcycle
 * Run with: node scripts/generate_excuses.js
 */

const fs = require('fs');
const path = require('path');

const categories = {
  funny: [
    "My cat sat on my keyboard and submitted my resignation — still trying to undo that.",
    "I sneezed so hard I pulled every muscle in my upper body.",
    "I accidentally superglued my hand to my front door handle.",
    "A seagull stole my car keys and flew away. I'm not joking.",
    "I put my phone in the fridge and my lunch in my pocket. Found both hours later.",
    "My parrot has learned to call in sick on my behalf — unfortunately he did it again.",
    "I sat on my glasses and now I can't find my glasses to look for my glasses.",
    "I fell asleep on the couch and my dog locked the dog door from the outside.",
    "I accidentally signed up for a 5K that starts in my neighborhood this morning.",
    "My breakfast fought back.",
    "I tripped on my own shoelace and slid down a full flight of stairs.",
    "My fish is sick and I've been up all night performing fish CPR.",
    "I got my sweater stuck in the car door and had to cut myself free.",
    "I left my shoes at a friend's house last night and only realized at the bus stop.",
    "My alarm clock displayed a very convincing PM instead of AM.",
    "I tried to make coffee and made soup instead. I don't know how.",
    "A raccoon has barricaded himself in my garage and refuses to negotiate.",
    "I locked myself out while checking the mail in my pajamas.",
    "My dog ate the car registration and the DMV needs it today.",
    "I tried a new hair dye and my hair is now a color not found in nature.",
    "I accidentally replied-all on a very personal email thread this morning.",
    "A squirrel chewed through my only charging cable and my phone is dead.",
    "I walked into a sliding glass door and need a moment.",
    "My neighbor's inflatable pool float escaped into my yard and blocked my car.",
    "I slipped on a banana peel. Yes, that is actually what happened.",
    "My kids put googly eyes on all my work clothes and I didn't notice until the bus.",
    "I accidentally joined a flash mob and couldn't get out.",
    "I woke up to find my car wrapped in toilet paper — neighborhood prank gone far.",
    "I burned my toast so badly the smoke alarm called the fire department.",
    "My automatic garage door has decided today is its day off.",
    "I accidentally wore two different shoes to the bus stop.",
    "My roommate adopted a goat without telling me. The goat is not adjusting well.",
    "I got my tie caught in the printer last night and couldn't reach my phone.",
    "I knocked over my entire wardrobe this morning and need time to process.",
    "I tried to take a shortcut and ended up in a different city.",
    "My doorbell camera caught something I need to report to several authorities.",
    "I accidentally deleted my entire calendar including today's meetings.",
    "My office chair rolled away on a slight incline and I lost it for 45 minutes.",
    "I got my zipper irreparably stuck and I'm still in my coat.",
    "A bird has built a nest in my wing mirror and I don't have the heart to disturb it.",
    "I overloaded my coffee maker and it exploded. The cleanup is ongoing.",
    "I got a sticker stuck to my contact lens.",
    "I answered the door in my sleep. The delivery person left a note.",
    "My microwave door fell off and somehow hit the car keys.",
    "I found out this morning that I'm allergic to my new soap. My face is impressive.",
    "I ordered breakfast delivery and it arrived to the wrong address — my neighbor's.",
    "I accidentally booked my gym session for 4 AM and somehow showed up.",
    "My belt broke in half as I was leaving. I have no backup belt.",
    "I sat in something mysterious on the bus and need to go home to change.",
    "A jar of pasta sauce exploded in my bag and took out my laptop charger.",
  ],
  believable: [
    "I have a doctor's appointment I completely forgot about until this morning.",
    "My child is sick and I couldn't find anyone to watch them.",
    "My car won't start — battery is completely dead.",
    "I have a severe migraine and can't look at screens.",
    "My babysitter cancelled at the last minute.",
    "There's a family emergency I can't discuss right now.",
    "I got a flat tire on the way in.",
    "My elderly parent needs to go to the hospital today.",
    "I woke up with food poisoning and it's not pretty.",
    "My back went out and I can barely move.",
    "I'm stuck in an unexpected traffic jam — the freeway is completely closed.",
    "My train was cancelled with no warning.",
    "My kid's school called — fever, I have to pick them up now.",
    "I have pink eye and don't want to spread it.",
    "My pipes burst overnight and there's water everywhere.",
    "There's a gas leak and the utility company is on their way.",
    "I have jury duty that just got confirmed.",
    "My spouse was rushed to the ER last night.",
    "I pulled a muscle in my back and can barely sit.",
    "I'm having a dental emergency — the pain is unbearable.",
    "I have a 24-hour stomach bug.",
    "My furnace died in the middle of the night.",
    "A contractor is coming for an emergency repair I can't reschedule.",
    "I missed my bus and the next one isn't for an hour.",
    "My car is at the mechanic unexpectedly.",
    "I have a high fever and my doctor said to stay home.",
    "I sprained my ankle and can't drive.",
    "I have a court date I forgot to mention.",
    "I need to renew my driver's license — it expires today.",
    "My roof is leaking and I need to manage the damage.",
    "I was in a minor fender-bender — no injuries but paperwork is required.",
    "My kid has a specialist appointment I've waited months for.",
    "My refrigerator stopped working and everything is spoiling.",
    "My blood pressure is dangerously high and I need rest.",
    "I have vertigo and the room won't stop spinning.",
    "My hot water heater burst.",
    "My parent fell and I need to assess if they're okay.",
    "My child had a severe allergic reaction at school.",
    "I have laryngitis and can't speak for any calls.",
    "I stepped on a nail and need to get a tetanus shot.",
    "There was a small electrical fire — fire department came, all is fine now.",
    "My basement flooded.",
    "I have a kidney stone and the pain is unbearable.",
    "My child has a panic attack and I can't leave them alone.",
    "I have a visa appointment that took months to book.",
    "My power has been out since last night.",
    "I have strep throat — confirmed by urgent care this morning.",
    "My parent's caregiver didn't show up and I'm the backup.",
    "I have asthma and it's badly flaring today.",
    "My teenager had an accident and I need to be there.",
    "My car got towed overnight — parking sign confusion.",
    "The bridge on my route is closed for emergency repairs.",
    "I have a urinary tract infection that's completely debilitating.",
    "My child's daycare is closed due to an emergency.",
    "I lost my wallet, ID and transit card — I'm stuck.",
    "My apartment building has an unscheduled water shut-off.",
    "The exterminators are coming — it couldn't wait.",
    "I'm waiting for an important delivery that requires my signature.",
    "I have a financial emergency at my bank.",
    "My identity was stolen and I need to deal with the bank today.",
    "My washing machine flooded my laundry room.",
    "I have a therapy appointment I really need to keep.",
    "I have to appear in person at a government office today.",
    "My car's check engine light came on and it's making a terrible noise.",
    "There's black ice everywhere — I nearly slipped in my driveway.",
    "My sinuses are completely blocked and I can't think straight.",
    "I have a rash that needs medical attention today.",
    "I have sciatica so bad I can't sit or stand comfortably.",
    "My windshield cracked and I can't see safely.",
    "My parent's medication was mixed up and I need to sort it out.",
    "I have a mandatory union meeting.",
    "I have a mortgage closing today.",
    "My building is being inspected and they need access to my unit.",
    "I have a blood draw that requires fasting and I feel awful.",
    "My dog is really sick and needs emergency vet care.",
    "I need to deal with my car registration before I get a fine.",
    "I have to attend a funeral of a colleague's family member.",
    "I have a housing inspection that I couldn't reschedule.",
    "My sibling is in crisis and I'm the only one they'll talk to.",
    "My oven caught fire — minor damage but lots of smoke.",
    "I ran out of my medication and the pharmacy doesn't open until noon.",
    "I have a shingles outbreak and it's extremely painful.",
    "My child locked themselves in the bathroom and I'm waiting for a locksmith.",
    "I have bronchitis and keep having coughing fits.",
    "My landlord is doing mandatory repairs today.",
    "I have carpal tunnel so bad I can't use a keyboard today.",
    "I have tendinitis in my shoulder and can barely lift my arm.",
    "I need to handle estate paperwork from a relative's passing.",
    "My security system was triggered and I need to be home for the police.",
    "I have a passport appointment for an urgent upcoming trip.",
    "My spouse just had surgery and was discharged early — I need to care for them.",
    "I have a tax audit notification I need to deal with today.",
    "I have period cramps that are completely debilitating today.",
    "I have an IEP meeting at school for my child.",
    "My child has a school event I forgot to put on the calendar.",
    "I have a consulate appointment that took months to get.",
    "I have to deal with a collections issue before end of day.",
    "My car's alternator died mid-commute.",
    "I need to go to urgent care — I'll explain later.",
    "I cut my finger badly and needed stitches this morning.",
    "I burned my hand cooking breakfast.",
    "My parent's power of attorney paperwork needs to be signed today.",
  ],
  chaotic: [
    "My car won't start, the babysitter cancelled, and I stepped on a Lego — all before 7am.",
    "The pipe burst, the dog escaped, and my kid threw my keys somewhere in the garden.",
    "My alarm didn't go off, my coffee exploded, and I'm locked out of the house.",
    "I spilled a full pot of coffee on my laptop while simultaneously burning breakfast.",
    "The cat knocked my phone into the toilet while I was answering a work email.",
    "My car battery died, my Uber got cancelled, and the last bus left two minutes ago.",
    "I overslept, my iron broke mid-shirt, and now I can't find parking anywhere.",
    "Three separate appliances broke this morning in a coordinated attack.",
    "My wifi died, my hotspot is out of data, and my laptop charger snapped in half.",
    "The power went out, my alarm ran on battery but was wrong, and here we are.",
    "I woke up sick, my car has a flat, and my neighbor blocked my driveway again.",
    "My basement flooded, the sump pump failed, and I'm currently knee-deep in this.",
    "I lost my phone, my wallet, and my car keys — all in my own apartment.",
    "The heating failed, the pipes froze, and the plumber has a 4-hour window.",
    "My dog ate my lunch, chewed through my charger, and is now eating my shoe.",
    "I ran over a nail getting milk, the spare is flat too, and I'm stranded.",
    "My kid vomited on my work bag just as I was heading out the door.",
    "I broke my glasses, my contacts are expired, and I literally cannot see.",
    "My laundry is still wet, my only backup shirt is at the dry cleaner, and I'm out of options.",
    "I was in a minor accident, then noticed my registration is expired, then it started raining.",
    "My fridge died, the freezer thawed, and everything needs to be cleaned up immediately.",
    "I fell and twisted my ankle, then dropped my phone screen-first on concrete.",
    "Everything that could go wrong this morning did, in roughly chronological order.",
    "My garage door broke, trapping the car inside — then the locksmith got stuck in traffic.",
    "The babysitter, the backup babysitter, and my partner all called in unavailable today.",
    "I stepped on a bee barefoot, my EpiPen is expired, and I'm waiting for a ride to urgent care.",
    "My toilet overflowed, I slipped cleaning it up, and now I'm icing my knee.",
    "My kid drew on my only clean work clothes with permanent marker.",
    "My router is dead, my phone data is throttled, and there's a city-wide outage too.",
    "I tried to fix a small leak and now there's a larger, more confident leak.",
    "My car stalled on the railway crossing — I got out in time, the car did not.",
    "My umbrella broke, it's raining sideways, and a puddle got me from the knees down.",
    "I dropped my work badge in the gap between the platform and the train.",
    "My cat escaped, I chased it outside without shoes, and then got locked out.",
    "The school called about one child while the other one was having a meltdown at home.",
    "My upstairs neighbor's pipe burst into my ceiling during breakfast.",
    "I went to the gym at 5am, locked my keys inside, and have been here since.",
    "A tree branch fell on my car and also on the path I use to get to the bus.",
    "I attempted to iron one shirt and somehow set off the smoke alarm and fire suppression.",
    "My bike tire punctured, the repair kit was empty, and my phone died on the way back.",
    "The elevator in my building is broken and I live on the 14th floor with a bad knee.",
    "I arrived at the office and realized I'd left my laptop at a coffee shop 3 miles back.",
    "My power went out overnight — fridge defrosted, alarm reset, morning in ruins.",
    "I was half dressed for work when a water main exploded on my street.",
    "My printer jammed while printing a document I need, ate the paper, and now smells.",
    "My ride-share driver drove to my road — the wrong city — and I'm still disputing the charge.",
    "I booked the wrong train, got on anyway, am now 60 miles in the wrong direction.",
    "My dishwasher flooded, the mop handle snapped, and the towels are all in the wash.",
    "I had three things go wrong simultaneously and I need a minute to rank them by urgency.",
    "I genuinely do not know where to start with this morning and that's the problem.",
  ],
  dark: [
    "I've come to question whether commuting is something I can continue to do in good conscience.",
    "I need a day to sit with the crushing weight of mid-week existential dread.",
    "I had a dream where I wasn't tired anymore and I need to grieve the loss of waking up.",
    "My will to participate in society peaked last Friday and has been declining since.",
    "I'm processing some information about the nature of Mondays that I can't ignore.",
    "I stared at my work outfit for 45 minutes and felt nothing.",
    "I have arrived at a philosophical impasse regarding the concept of showing up.",
    "My motivation called in sick and didn't leave a forwarding number.",
    "I looked at my calendar and the meeting at 9am gave me a physical response.",
    "I am deeply, personally exhausted in a way that one more team standup will not fix.",
    "I need to take a day to be sad about things in a productive, horizontal way.",
    "My enthusiasm for this week has reached levels too low to sustain safe operation.",
    "I have been awake since 3am contemplating my career and the conclusions weren't great.",
    "I'm in a period of emotional inventory that requires me to stay home and audit things.",
    "I've hit a wall and the wall has hit back.",
    "I require a day to not be perceived by anyone.",
    "I'm taking a mental health day before I am forced to take a permanent career change.",
    "My inner battery has been at 2% since Sunday and charging is slow.",
    "I need to rest before I say something I cannot unsay in a meeting.",
    "The thought of joining that 8am call filled me with a specific kind of despair.",
    "I reached the limit of my current reserves of patience and professionalism.",
    "I woke up at 4am certain of something I cannot verify and I haven't recovered.",
    "I need the day to process some feelings that are interfering with my typing speed.",
    "My spirit needs a Tuesday to regroup before Wednesday.",
    "I have a case of burnout that I've been reclassifying as 'fine' for too many months.",
    "I have a scheduled breakdown that I can no longer postpone.",
    "I am going through something I am not ready to name but am very ready to feel.",
    "My capacity to perform normalcy today is simply not there.",
    "I keep starting sentences and then stopping and that seems relevant.",
    "I need to take a personal day before I make a decision I can't walk back.",
    "I've been running on fumes, spite, and cold coffee and two of those have run out.",
    "I need to decompress from last week before I'm ready to compress for this one.",
    "I have a deep structural tiredness that one night of sleep didn't address.",
    "Something happened and I'm dealing with it at the speed of someone who needs the day.",
    "I have a thing I need to sit with, and it needs a whole day, not a lunch break.",
    "I am at capacity and taking on anything further would result in overflow.",
    "My resilience is currently offline for scheduled maintenance.",
    "I need to not work today in order to continue to want to work tomorrow.",
    "I'm experiencing a level of internal weather that requires me to stay indoors.",
    "I have a meeting with myself today to discuss some internal feedback I've received.",
    "I have run out of the kind of energy you need for other people.",
    "My sense of humor about all of this has temporarily left the building.",
    "I need to take a rest day or I will take a rest year — I'm choosing the smaller option.",
    "I've been ignoring some warning signs about my own wellbeing and they've escalated.",
    "I have arrived at a junction in my relationship with this week.",
    "I need a day that is entirely mine — no performance, no output, no updates.",
    "I'm recharging so the next version of me that shows up is worth having there.",
    "I am resting preemptively, which is more efficient than resting reactively.",
    "Something is wrong and I don't have the vocabulary for it yet.",
    "I'm taking a day to be a person rather than a function.",
  ],
  office: [
    "I have a conflict with a recurring meeting that I can no longer resolve diplomatically.",
    "I'm experiencing stakeholder fatigue and need 24 hours before the next alignment call.",
    "I'm working from home today to avoid the collaborative open-plan environment.",
    "I need to review my notes from last quarter's all-hands before I can engage with this quarter.",
    "I have reached the weekly limit of meetings during which nothing was decided.",
    "I'm blocked on a dependency and cannot progress until that dependency responds to email.",
    "I'm taking an offline working day — deep work requires zero interruptions.",
    "I'm attending a leadership summit. It's on YouTube. Still counts.",
    "I have a performance review I need to prepare for, which takes all of today.",
    "I'm prototyping a new workflow that could save the team hundreds of hours — needs the day.",
    "I'm doing independent market research from an undisclosed location.",
    "I have an off-site strategy session — the off-site is my living room.",
    "I need to review my OKRs and my OKRs are not going to review themselves.",
    "I have to finalize my Q3 priorities, which are in conflict with my Q2 commitments.",
    "I'm taking a proactive mental health day to prevent a much longer future absence.",
    "I have a networking event I need to prepare for.",
    "I'm conducting a retrospective on my own productivity before proceeding.",
    "I have a 1:1 I need to reschedule — it was scheduled for today and I need to reschedule it.",
    "I have to submit a report that requires data from a system I've been locked out of.",
    "I'm updating my skills to remain competitive in the current market.",
    "I have a conflict of commitment this morning that requires my attention.",
    "I'm taking a creativity day — some of my best ideas have come from not being at my desk.",
    "I need to do some reading that is tangentially but meaningfully work-related.",
    "I have a commitment to a cross-functional initiative that supersedes today's schedule.",
    "I'm in a planning retreat for next month's planning retreat.",
    "I've completed all my deliverables and coming in would only slow others down.",
    "I'm working on a passion project that may change the company — I need just one more day.",
    "I need to complete my mandatory training before the deadline tonight.",
    "I have a professional development workshop — it's self-directed but still.",
    "I have an industry conference call at an inconvenient time that takes the whole morning.",
    "I need to write a business case I've been procrastinating on for three weeks.",
    "I'm preparing for a difficult conversation that requires extensive preparation.",
    "I have a compliance deadline I've only just become aware of.",
    "I'm attending a seminar. The seminar is a podcast. I'm taking notes.",
    "I need to archive three years of email before I can function productively.",
    "I have an urgent deliverable that will go faster without colleagues asking questions.",
    "I need to respond to a client escalation that can only be handled from my home office.",
    "I'm reviewing my job description to see if any of today's tasks are actually mine.",
    "I have a difficult email to compose and I need the full day to get the tone right.",
    "I'm mentoring someone remotely — it's scheduled for today, all day apparently.",
    "I need to finish something that yesterday's me should have finished and didn't.",
    "I have a milestone review that I am not yet ready to milestone.",
    "I need to review a contract with some clauses I need to look into.",
    "I have a hiring panel interview today that I wasn't told about until last night.",
    "I'm managing a supplier relationship that requires my full attention today.",
    "I have an urgent audit request that requires me to gather files for the next few hours.",
    "I need to respond to a legal matter the company's outside counsel flagged.",
    "I have a board deck to review before it goes out and the changes are substantial.",
    "I'm attending a crisis communications training. Timing is apt.",
    "I have a regulatory filing due that I only became aware of this morning.",
  ],
  tech: [
    "My laptop completely died and I'm waiting for IT support.",
    "My home internet is down and the ISP has a 4-hour repair window.",
    "My VPN hasn't worked all morning and I can't access anything.",
    "My computer won't boot — the hard drive might be dead.",
    "I spilled coffee on my laptop and it's fried.",
    "My router is dead and a replacement arrives this afternoon.",
    "My monitor died and I'm waiting for a loaner.",
    "My work phone got wiped remotely by mistake.",
    "The power surge last night fried my entire home office setup.",
    "My keyboard broke and I cannot type.",
    "My two-factor authentication app got corrupted and I'm locked out of everything.",
    "My work device ran a forced update overnight and now nothing works.",
    "My entire workspace is down due to a cloud service outage.",
    "My external hard drive with all my project files died.",
    "I'm locked out of my work email and IT hasn't responded yet.",
    "My webcam failed and I have video calls all day.",
    "My microphone stopped working and I have 5 hours of meetings.",
    "My ISP is doing emergency maintenance in my area today.",
    "My phone was stolen and I'm dealing with the account lockout process.",
    "My company laptop was involved in a liquid incident — I prefer not to specify.",
    "My internet keeps dropping every 10 minutes — IT is working on it.",
    "My GPU failed and I need it for literally everything I do.",
    "My noise-cancelling headphones broke and my neighbors are jackhammering.",
    "My printer died and I need to print legal documents for a meeting.",
    "My second monitor died and I can't do my job on a single 13-inch screen.",
    "My home office UPS failed and took the router down with it.",
    "A Windows update has rendered my machine unable to connect to company servers.",
    "I was the target of a phishing attack and need to secure all my accounts.",
    "My SSH keys got wiped and I can't access any of the servers I maintain.",
    "My development environment is completely broken after an OS update.",
    "My cloud storage hit its limit and I can't sync anything to work.",
    "The shared drive is down and everything I need is on the shared drive.",
    "My company VPN token expired and I can't get a new one without the system I can't access.",
    "My laptop battery died and the charger is at the office. A replacement is coming.",
    "My home NAS is in a RAID rebuild and I'm locked out of all my local files.",
    "My Bluetooth devices stopped pairing and I can't use anything without wires.",
    "My workspace container refuses to start — corrupted after yesterday's update.",
    "My IDE is in a crash loop and factory reset didn't help.",
    "My build system is broken and I can't even check what's broken without the build system.",
    "My local DNS is resolving everything to localhost — I can't reach any external service.",
    "My authentication certificate expired at midnight and renewal is a 2-hour process.",
    "My two monitors have different color profiles and the difference gave me a migraine.",
    "My terminal emulator corrupted its config and now displays everything upside down.",
    "I accidentally deleted a config file and now my entire local environment is unresponsive.",
    "My package manager is broken, the caches are corrupted, and I've been at it since 6am.",
    "My video conferencing app refuses to see my camera even though it's connected.",
    "My Wi-Fi card failed and I'm waiting for a USB adapter to arrive.",
    "My smart home system had a glitch and locked me out of my own house.",
    "My ergonomic keyboard requires a firmware update that takes a full day apparently.",
    "I need to do a full hardware diagnostic before I can use this machine safely.",
  ],
  motorcycle: [
    "My motorcycle won't start and it's my only transport.",
    "I got a flat tire on the bike mid-commute.",
    "My chain snapped two miles from home.",
    "I slid on a wet road this morning — I'm fine, the bike less so.",
    "My throttle cable snapped and the bike is now parked on the verge.",
    "My kickstand broke and the bike tipped over in the driveway.",
    "My motorcycle was hit while parked overnight — waiting for the police report.",
    "My helmet visor cracked and I can't ride without it legally.",
    "My brake pads are metal on metal — discovered this morning, cannot ride.",
    "My battery died and the jump starter is at the shop.",
    "I noticed an oil leak on my way out — riding would make it significantly worse.",
    "My gear is soaked from last night's rain and hypothermia seems like a bad tradeoff.",
    "My clutch cable snapped in my hand as I pulled away from the driveway.",
    "My front fork has a slow leak I need to address before riding.",
    "My indicator stopped working and I can't ride legally without one.",
    "There's a bolt missing from my rear axle. I'm not riding today.",
    "My gloves were eaten by something overnight. I have no backup gloves.",
    "I noticed a crack in my frame that needs immediate assessment before I ride.",
    "My speedo cable disconnected and I can't monitor my speed.",
    "I need to wait for the frost to clear — my bike doesn't have ABS.",
    "My ride partner had a spill this morning and I'm with them at urgent care.",
    "My carb is flooding — the bike won't idle without my hand on the throttle.",
    "My rear shock has collapsed and the bike sits at an angle.",
    "The MOT/inspection expired yesterday — I can't legally take the bike out.",
    "My fuel gauge is broken and I ran out two blocks from home.",
    "My side stand switch is faulty — the engine cuts whenever I put it down.",
    "My handgrips came loose and are spinning — not safe to ride.",
    "I found a nail lodged in my rear tire this morning.",
    "My motorcycle was towed overnight — apparently my parking spot wasn't mine.",
    "My visor fogged up on my first corner of the day and I pulled over safely.",
    "A dog ran in front of me — no injuries, but I need a moment.",
    "My exhaust bracket snapped and the exhaust is dragging. Hard to ride quietly.",
    "My mirrors shook loose on yesterday's ride and I haven't re-adjusted them.",
    "My ignition switch is intermittent — it started once and then didn't.",
    "My seat bolts stripped and the seat moves on acceleration.",
    "My throttle is sticking open — that's a same-day fix I need to prioritize.",
    "My tail light has been out for a few days. Today I got pulled over about it.",
    "The road I commute on is closed for resurfacing and the detour doesn't suit a bike.",
    "My left hand is too sore from a fall last week to operate the clutch safely.",
    "There's a high-wind warning and my bike and I do not get along in high winds.",
    "My footpegs are cracked and I noticed it after the first corner.",
    "My fuel cap lock is jammed and I can't open it to refuel.",
    "I dropped the bike in the driveway and the brake lever snapped clean off.",
    "My riding jacket's CE armour needs replacing — I won't ride without it.",
    "My bike's GPS mount broke and I don't know the route without it.",
    "A wasp flew into my helmet at 40mph. I survived. The wasp did not.",
    "My levers are set for someone with bigger hands and adjustment takes tools I don't have.",
    "My chain guard broke off and is lying in the road.",
    "My coolant warning light came on two blocks from home.",
    "I need to wait for the tyre shop to open — the front tyre is unsafe to ride on.",
  ],
};

// eslint-disable-next-line no-unused-vars
const _OLD_categories = {
  health: [
    "I have a doctor's appointment that I completely forgot about until this morning.",
    "I woke up with a splitting migraine and can't look at screens.",
    "I think I have food poisoning from last night's dinner.",
    "My back went out and I can barely move.",
    "I have a severe allergic reaction and my face looks like a balloon.",
    "I pulled a muscle sneezing — yes, that's a real thing.",
    "My wisdom tooth is killing me and I need emergency dental care.",
    "I have pink eye and don't want to spread it.",
    "I have a 24-hour stomach bug and it's not pretty.",
    "My vertigo is so bad the room won't stop spinning.",
    "I have a kidney stone and the pain is unbearable.",
    "I came down with a bad cold overnight.",
    "My sinuses are completely blocked and I can't think straight.",
    "I injured my wrist and can't type.",
    "I have laryngitis and can't speak for any calls.",
    "I stepped on a nail and need to get a tetanus shot.",
    "I have a high fever and my doctor said to stay home.",
    "I sprained my ankle and can't drive.",
    "My blood pressure is dangerously high and I need rest.",
    "I have a severe sore throat and suspect strep.",
    "I have a rash that needs medical attention.",
    "My asthma is acting up badly today.",
    "I have a stomach ulcer flare-up.",
    "I have a urinary tract infection and it's miserable.",
    "I'm having heart palpitations and my doctor wants me monitored.",
    "I have a pinched nerve in my neck.",
    "My eczema is flaring and I can barely use my hands.",
    "I have a hernia that's acting up.",
    "I have severe period cramps that are debilitating today.",
    "I have an ear infection and can't balance properly.",
    "My diabetes is out of control and I need to rest.",
    "I have a severe nosebleed that won't stop.",
    "I have shingles and it's extremely painful.",
    "My carpal tunnel is so bad I can't use a keyboard.",
    "I have a bad case of sciatica today.",
    "I have bronchitis and keep having coughing fits.",
    "I have tendinitis in my shoulder.",
    "I burned my hand cooking breakfast.",
    "I need to go to urgent care — I'll explain later.",
    "I cut my finger badly and needed stitches.",
  ],
  family: [
    "My kid is sick and I can't find anyone to watch them.",
    "My babysitter cancelled at the last minute.",
    "My elderly parent needs to go to the hospital.",
    "There's a family emergency I can't discuss right now.",
    "My spouse was rushed to the ER last night.",
    "My child has a school event I completely forgot to put on the calendar.",
    "My kid's school just called — they have a fever and I need to pick them up.",
    "My mother flew in unexpectedly and I need to get her settled.",
    "My child had a panic attack and I can't leave them alone.",
    "My dog is really sick and needs emergency vet care.",
    "My cat had kittens overnight — all 7 of them need attention.",
    "My parent's caregiver didn't show up and I'm the backup.",
    "My kid has a specialist appointment I can't reschedule.",
    "My spouse just had surgery and was discharged early — I need to care for them.",
    "My nephew is in town and needs someone to pick him up from the airport.",
    "My parent fell and I need to assess if they're okay.",
    "My child has a severe allergic reaction at school.",
    "My family has a bereavement — a distant relative passed.",
    "My parent's power of attorney paperwork needs to be signed today.",
    "My child's daycare is closed for an emergency.",
    "My teenager had an accident and needs me now.",
    "My in-laws arrived a day early and chaos ensued.",
    "My sibling is in crisis and I'm the only one they'll talk to.",
    "My kid locked themselves in the bathroom and I'm waiting for a locksmith.",
    "My spouse got into a minor car accident and I need to help.",
    "My parent's medication was mixed up and I need to sort it out.",
    "My child has an IEP meeting at school today.",
    "My grandmother had a fall and is being evaluated.",
    "My pet fish died and my kids are inconsolable.",
    "My baby was up all night and I haven't slept at all.",
  ],
  transport: [
    "My car won't start — battery is completely dead.",
    "I got a flat tire on the way in.",
    "I'm stuck in an unexpected traffic jam — the freeway is completely closed.",
    "My train was cancelled with no warning.",
    "I missed my bus and the next one isn't for an hour.",
    "My car is at the mechanic unexpectedly.",
    "I was in a minor fender-bender — no injuries but lots of paperwork.",
    "My Uber driver cancelled and there are no cars available.",
    "There's a fuel leak in my car and I can't drive it.",
    "My bike tire popped on the way in.",
    "A traffic accident ahead has traffic at a standstill for miles.",
    "My car's check engine light came on and it's making a terrible noise.",
    "My car got towed overnight — parking sign confusion.",
    "The bridge on my route is closed for emergency repairs.",
    "My windshield cracked and I can't see safely.",
    "I ran out of gas — embarrassing but true.",
    "There's a road washout on my only route.",
    "My transmission just gave out.",
    "A tree fell across my driveway overnight.",
    "My alternator died and the car shut down mid-commute.",
    "My public transit app shows no service today on my line.",
    "I locked my keys in the car — waiting for roadside assistance.",
    "There's a police checkpoint blocking my route.",
    "My parking brake cable snapped and I can't move the car safely.",
    "I have a cracked axle and the car is undriveable.",
    "My car was broken into overnight — I need to deal with the police report.",
    "A sinkhole opened on my street.",
    "The road is flooded and impassable.",
    "My garage door is broken and my car is stuck inside.",
    "I rear-ended someone slightly — everyone's fine but there's a report to file.",
  ],
  home: [
    "My pipes burst overnight and there's water everywhere.",
    "I have a gas leak and the utility company is on their way.",
    "My furnace died in the middle of the night.",
    "A contractor is coming for an emergency repair I can't reschedule.",
    "My roof is leaking and I need to manage the damage.",
    "My refrigerator stopped working and everything is spoiling.",
    "There was a small electrical fire — the fire department came, all is fine.",
    "My basement flooded.",
    "My hot water heater burst.",
    "A tree branch fell on my car overnight.",
    "My internet is completely out and I can't work from home.",
    "My apartment building has a water shut-off today.",
    "There's a power outage in my neighborhood.",
    "The exterminators are coming — it couldn't wait.",
    "My washing machine flooded my laundry room.",
    "My oven caught fire — minor damage but lots of smoke.",
    "My landlord is doing mandatory repairs today.",
    "I came home to find a burst pipe I have to deal with now.",
    "My security system was triggered and the alarm company needs me there.",
    "A raccoon got into my attic and I need to deal with it.",
    "My septic system is backing up.",
    "My HVAC is broken and it's dangerously hot/cold inside.",
    "There was a break-in attempt and I need to stay home for the police report.",
    "My elevator in the apartment building is broken and I can't carry all my gear down 12 flights.",
    "My movers are arriving today — I mixed up the dates.",
    "A water main broke on my street and there's no water.",
    "My building is being inspected and they need access to my unit.",
    "I have a bedbug inspector coming — mandatory for the building.",
    "My garage is flooded and I can't get my car out.",
    "My mailbox was damaged and I need to deal with important documents.",
  ],
  weather: [
    "There's a severe snowstorm and the roads are completely impassable.",
    "A tornado warning was issued for my area.",
    "The hurricane preparation is taking all day.",
    "Flooding in my area is making roads unsafe.",
    "There's black ice everywhere — I nearly slipped in my driveway.",
    "A blizzard hit overnight and my car is buried.",
    "The heat index is dangerously high and my AC broke.",
    "A wildfire is nearby and I'm on evacuation alert.",
    "Severe thunderstorms are causing flash flooding on my route.",
    "Dense fog advisory — visibility is near zero.",
    "Hail damaged my windshield and I can't drive.",
    "Extreme cold warning — my car won't start and the pipes might freeze.",
    "A wind advisory has downed trees all over my route.",
    "There's an ice storm and my car is encased in ice.",
    "Lightning struck nearby and knocked out power to my block.",
    "A mudslide closed the only road to my neighborhood.",
    "Dust storm conditions — completely unsafe to drive.",
    "There's a waterspout warning near the coast on my route.",
    "Freezing rain has made every surface treacherous.",
    "A heat wave has the roads buckling — my tire blew out.",
  ],
  personal: [
    "I have a personal matter I need to attend to — I'd rather not share the details.",
    "I'm dealing with a mental health day that I really need.",
    "I have a court date I forgot to mention.",
    "I need to renew my driver's license — it expires today.",
    "I have jury duty that just got confirmed.",
    "I have a visa appointment that can't be moved.",
    "I'm waiting for an important delivery that requires my signature.",
    "I have a financial emergency at my bank.",
    "I lost my wallet and ID and need to sort it out.",
    "I have a passport appointment for an urgent trip.",
    "My identity was stolen and I need to deal with the bank today.",
    "I have a therapy appointment that I really need to keep.",
    "I have to appear in person at a government office today.",
    "I have a housing inspection that I couldn't reschedule.",
    "I'm moving to a new apartment today — I thought I mentioned it.",
    "I have to deal with a tax audit notification.",
    "I have a consulate appointment that took months to get.",
    "I have to handle estate paperwork from a relative's passing.",
    "I have a mandatory union meeting.",
    "I have to sort out a banking error before the day is out.",
    "I have a DMV appointment and the next one is 3 months out.",
    "I have a mortgage closing today.",
    "I have a social security office appointment.",
    "I have an immigration hearing today.",
    "I need to handle my car registration before I get a fine.",
    "I have to deal with a collections call that turned into a whole thing.",
    "I have a scheduled surgery consult I've waited months for.",
    "I have to attend a funeral of a colleague's family member.",
    "I have a blood draw that has to be fasted — can't eat — and I feel awful.",
    "I'm dealing with an unexpected legal matter.",
  ],
  technology: [
    "My laptop completely died and I'm waiting for IT support.",
    "My home internet is down and there's no ETA for repair.",
    "My phone was stolen and I need to deal with that.",
    "I was locked out of all my accounts after a security incident.",
    "My VPN hasn't worked all morning and I can't access anything.",
    "My computer won't boot — the hard drive might be dead.",
    "My ISP is doing emergency maintenance in my area today.",
    "I spilled coffee on my laptop and it's fried.",
    "I was the victim of a phishing attack and need to secure my accounts.",
    "My router is dead and I can't get online.",
    "My monitor died and I'm waiting for a replacement.",
    "My work phone got wiped remotely by mistake.",
    "The power surge last night fried my entire home office setup.",
    "My keyboard broke and I literally cannot type.",
    "My two-factor authentication app got corrupted and I can't log into anything.",
    "My work device ran a forced update overnight and now nothing works.",
    "My entire workspace is down due to a cloud service outage.",
    "My external hard drive with all my work files died.",
    "I'm locked out of my work email and IT hasn't responded.",
    "My smart home system had a glitch and locked me out of my own house.",
  ],
  creative: [
    "I accidentally scheduled a dentist appointment for today instead of tomorrow.",
    "I thought today was a holiday.",
    "I mixed up my time zones and thought I had an extra hour.",
    "I sleep-walked and somehow ended up in my neighbor's yard.",
    "My alarm clock displayed the wrong time because of daylight saving.",
    "I was bitten by a spider and my hand swelled up.",
    "A bee flew into my car and I had to pull over immediately.",
    "A deer crashed through my fence this morning.",
    "I found a stray dog in my house and I'm trying to find its owner.",
    "A bird flew into my house and I've been trying to get it out for an hour.",
    "My neighbor's tree fell into my yard and blocked my driveway.",
    "I got stung by a jellyfish on my morning swim.",
    "I accidentally left my laptop on the roof of my car.",
    "I woke up and my entire neighborhood was blocked off for a film shoot.",
    "I accidentally washed my phone in the laundry.",
    "My neighbor is having a very loud argument with a delivery driver in my driveway.",
    "A squirrel chewed through my power cable.",
    "I found a snake in my garage and am waiting for animal control.",
    "I accidentally glued my hand to my desk.",
    "I got my hand stuck in a jar and had to go to urgent care.",
    "My mail carrier left a package in front of my car in the garage.",
    "I fell asleep on the couch and my cat sat on my face and I can't breathe.",
    "My dog ate my laptop charger.",
    "I dropped my car keys in a drain.",
    "A gust of wind blew all my important papers out the window.",
    "My doorbell camera caught something suspicious and I'm waiting for police.",
    "I accidentally booked a flight for today and am trying to cancel.",
    "I thought my commute was shorter but got completely lost.",
    "I got a unexpected visit from old friends who had nowhere to go.",
    "My cat knocked over my monitor and it shattered.",
  ],
  philosophical: [
    "I need a day to reflect on the direction of my career.",
    "I'm experiencing existential uncertainty about the nature of work itself.",
    "I've been deeply questioning whether linear time constructs like 'Monday' are truly binding.",
    "My horoscope strongly advised against any professional endeavors today.",
    "I had a prophetic dream that warned me not to leave the house.",
    "I'm practicing radical presence and today calls me to be present at home.",
    "I feel called to a higher purpose today that precludes spreadsheet review.",
    "My spirit guide indicated this is a rest day.",
    "I'm in a retrograde-induced communications blackout.",
    "I need to realign my chakras before I can be productive.",
    "I spilled my coffee and took it as a sign from the universe.",
    "My tarot reading this morning was unambiguous: stay home.",
    "I'm processing a deeply meaningful dream and cannot rush the integration.",
    "I'm honoring my body's wisdom which is telling me to rest.",
    "I feel that productivity today would be inauthentic to my current emotional state.",
    "My energy is being redirected to inner work today.",
    "I am undertaking a voluntary digital and professional detox.",
    "I've been advised by my life coach to take an unscheduled personal day.",
    "The universe clearly doesn't want me at work today — three things broke before 7am.",
    "I'm on a self-imposed sabbatical of indeterminate length.",
  ],
  vague: [
    "Something came up.",
    "I have a situation I'm dealing with.",
    "I won't be able to make it in today.",
    "I have an appointment I can't move.",
    "I need to take care of something urgent at home.",
    "A personal matter requires my attention.",
    "I have a conflict today.",
    "I'm not feeling well.",
    "I have a commitment I forgot to put on the calendar.",
    "I have to handle something — I'll fill you in later.",
    "It's complicated, but I won't be in.",
    "I have an urgent errand.",
    "I need to deal with something at home.",
    "I have an obligation I can't get out of.",
    "There's an issue I need to sort out before I can come in.",
    "I'll be working remotely today — or possibly not at all.",
    "I have some things to handle.",
    "I'm tied up this morning.",
    "Something unexpected came up — I'll explain tomorrow.",
    "I need the day.",
    "It's a long story. Can we catch up tomorrow?",
    "I'll explain when I see you.",
    "Let's just say the universe had other plans for me today.",
    "Trust me, you don't want to know.",
    "I'm handling it.",
    "I have a thing.",
    "Family stuff.",
    "Medical-adjacent stuff.",
    "Home chaos.",
    "Life is happening aggressively today.",
  ],
  remote_work: [
    "My home office flooded — the router is dead.",
    "My co-working space is closed today.",
    "My upstairs neighbor's water heater burst into my ceiling.",
    "My building's WiFi is down and my hotspot can't support video calls.",
    "My power has been flickering all morning — I can't risk losing my work.",
    "The noise from next-door construction is too loud to join any calls.",
    "My VPN has been cutting out every 10 minutes — IT is working on it.",
    "My standing desk motor burned out and I can't work sitting on the floor.",
    "My second monitor died and I can't do my job with just a laptop screen.",
    "My ergonomic chair broke and my back can't handle a regular chair all day.",
    "My microphone failed and I have 6 hours of calls today.",
    "My webcam stopped working and today's meetings require video.",
    "My office chair mysteriously started slowly deflating.",
    "My noise-cancelling headphones broke and the neighbors are jackhammering.",
    "My printer died and I need to print legal documents.",
    "My home office lost heating and it's 40 degrees in the room.",
    "The coffee machine broke. I cannot function. This is a medical situation.",
    "My spouse is also working from home today and we only have one chair.",
    "My toddler scheduled a playdate in my office without telling me.",
    "My WiFi password changed and I can't connect to anything.",
  ],
  food_and_sleep: [
    "I ate something suspicious and I'm paying the price.",
    "I was up all night with food poisoning.",
    "I accidentally took a double dose of my antihistamine and I can't keep my eyes open.",
    "I drank the worst coffee of my life and now I'm having palpitations.",
    "I tried a new recipe and gave myself a severe allergic reaction.",
    "I went to a dinner party and got home at 4am — oops.",
    "I tried intermittent fasting for the first time and I'm basically catatonic.",
    "I accidentally ate gluten and I'm suffering.",
    "I ran out of my medication and the pharmacy doesn't open until noon.",
    "I have terrible insomnia and haven't slept in 30+ hours.",
    "I took a sleep aid last night that's clearly still working.",
    "I made the mistake of trying to make my own sushi — enough said.",
    "I accidentally ate an entire ghost pepper on a dare.",
    "I tried a new protein shake and my stomach revolted.",
    "My sleep schedule is completely inverted and I can't correct it in one day.",
    "I had a nightmare so vivid I need a moment to confirm this is reality.",
    "I overslept by 4 hours — the alarm was set for PM instead of AM.",
    "I went for a run at 5am and immediately regretted everything.",
    "I drank too much cold brew and my hands won't stop shaking.",
    "I haven't eaten in 18 hours and I'm running on fumes.",
  ],
  work_itself: [
    "I completed everything on my task list — there's nothing left to do.",
    "I'm so productive from home that coming in would only slow me down.",
    "My therapist said I need to establish better boundaries with the office.",
    "I read an article about the 4-day work week and I'm piloting it today.",
    "I'm taking a proactive mental health day to prevent a much longer future absence.",
    "I need to do some deep thinking that requires zero interruptions.",
    "I'm working on a passion project that may revolutionize the company — I need a day.",
    "I'm doing a digital detox to recharge my creative batteries.",
    "I'm attending a virtual conference — yes, it's on YouTube, but still.",
    "I'm resting to ensure maximum performance for the rest of the week.",
    "I'm conducting independent market research from my couch.",
    "I'm studying a new skill that will make me 10x more effective.",
    "I'm reading a business book and I'm at a critical chapter.",
    "I'm meditating on the Q3 strategy.",
    "I'm taking a self-directed sabbatical — I'll submit the form retroactively.",
    "I'm on a creativity retreat.",
    "I need to recharge before the big presentation next week.",
    "I'm performing a systems audit on my personal productivity.",
    "I'm prototyping a new workflow that could save the team hundreds of hours.",
    "I realized I've been overworking and today is mandated recovery time.",
  ],
};

function generateExcuses() {
  const allExcuses = [];
  let id = 1;

  for (const [category, excuses] of Object.entries(categories)) {
    for (const text of excuses) {
      allExcuses.push({ id, category, text });
      id++;
    }
  }

  // Pad to exactly 1001 using round-robin across categories if needed
  const catNames = Object.keys(categories);
  const catArrays = Object.values(categories);
  let fillerCatIdx = 0;
  let fillerItemIdx = 0;

  while (allExcuses.length < 1001) {
    const catName = catNames[fillerCatIdx % catNames.length];
    const catList = catArrays[fillerCatIdx % catArrays.length];
    const text = catList[fillerItemIdx % catList.length] + ' (alternate)';
    allExcuses.push({ id, category: catName, text });
    id++;
    fillerItemIdx++;
    if (fillerItemIdx % catList.length === 0) fillerCatIdx++;
  }

  return allExcuses.slice(0, 1001);
}

const excuses = generateExcuses();
const outputPath = path.join(__dirname, '..', 'assets', 'excuses.json');

fs.writeFileSync(outputPath, JSON.stringify(excuses, null, 2), 'utf8');
console.log(`✅  Generated ${excuses.length} excuses → ${outputPath}`);

