/**
 * Generates assets/excuses_no.json with 1001 Norwegian work excuses.
 * Run with: node scripts/generate_excuses_no.js
 */

const fs = require('fs');
const path = require('path');

const categories = {
  funny: [
    "Katten min satt på tastaturet og sendte inn oppsigelsen min — prøver fortsatt å angre det.",
    "Jeg nøs så hardt at jeg trakk alle muskler i overkroppen.",
    "Jeg limte hånden min fast til dørhåndtaket ved et uhell.",
    "En måke stjal bilnøklene mine og fløy av gårde. Jeg spøker ikke.",
    "Jeg la telefonen i kjøleskapet og matpakken i lommen. Fant begge flere timer senere.",
    "Papegøyen min har lært å ringe og melde seg syk på mine vegne — dessverre gjorde den det igjen.",
    "Jeg satte meg på brillene mine og kan nå ikke finne dem for å lete etter dem.",
    "Jeg sovnet i sofaen og hunden min låste hundedøren fra utsiden.",
    "Jeg meldte meg ved et uhell på et 5 km-løp som starter i nabolaget mitt i morges.",
    "Frokosten min slo tilbake.",
    "Jeg snublet i egne skolisser og gled ned en hel trapp.",
    "Fisken min er syk og jeg har vært oppe hele natten med å gjøre fiske-HLR.",
    "Jeg fikk genseren fast i bildøren og måtte klippe meg fri.",
    "Jeg glemte skoene mine hos en venn i går og oppdaget det først ved bussholdeplassen.",
    "Vekkerklokken min viste PM i stedet for AM på et veldig overbevisende vis.",
    "Jeg prøvde å lage kaffe og lagde suppe i stedet. Vet ikke hvordan det skjedde.",
    "En rev har barrikadert seg i garasjen min og nekter å forhandle.",
    "Jeg låste meg ute mens jeg hentet posten i pyjamasen.",
    "Hunden min spiste bilregistreringen og Statens vegvesen trenger den i dag.",
    "Jeg prøvde et nytt hårfarge og håret mitt er nå en farge som ikke finnes i naturen.",
    "Jeg svarte-på-alle på en veldig personlig e-posttråd i morges.",
    "En ekorn gnagde gjennom den eneste ladekabelen min og telefonen er død.",
    "Jeg gikk inn i en glassdør og trenger et øyeblikk.",
    "Naboens luftmadrass rømte inn i hagen min og blokkerte bilen.",
    "Jeg glei på et bananskal. Ja, det er faktisk det som skjedde.",
    "Barna mine satte googly-øyne på alle arbeidsklærne mine og jeg la ikke merke til det før på bussen.",
    "Jeg gikk ved et uhell inn i en flashmob og klarte ikke å komme meg ut.",
    "Jeg våknet og fant bilen min pakket inn i toalettpapir.",
    "Jeg brant toasten så dårlig at røykvarsleren ringte brannvesenet.",
    "Den automatiske garasjeporten min har bestemt seg for at i dag er fridagen dens.",
    "Jeg oppdaget at jeg hadde to forskjellige sko på ved bussholdeplassen.",
    "Romkompisen min adopterte en geit uten å fortelle meg. Geiten tilpasser seg ikke bra.",
    "Jeg fikk slipset fast i skriveren i går og kom meg ikke til telefonen.",
    "Jeg veltet hele garderoben min i morges og trenger tid til å bearbeide det.",
    "Jeg prøvde en snarvei og endte opp i en annen by.",
    "Dørkamera mitt fanget noe jeg må rapportere til flere myndigheter.",
    "Jeg slettet hele kalenderen min ved et uhell, inkludert dagens møter.",
    "Kontorstolen min rullet ut på et svakt hellende underlag og jeg mistet den i 45 minutter.",
    "Glidelåsen min har satt seg fast irreversibelt og jeg er fortsatt i frakken.",
    "En fugl bygde reir i inntaksmunnen på bilen min og jeg kan ikke bry meg om å forstyrre den.",
    "Jeg overvarmet kaffebrødet og det eksploderte. Ryddejobben pågår fortsatt.",
    "Jeg fikk et klistremerke fast på kontaktlinsen.",
    "Jeg svarte døren i søvne. Budet etterlot en lapp.",
    "Mikrobølgeovnen min falt av hyllen og landet på bilnøklene.",
    "Jeg oppdaget i morges at jeg er allergisk mot den nye såpen. Ansiktet mitt er interessant.",
    "Jeg bestilte frokost på vei hjem og den ble levert til naboen — fikk den aldri.",
    "Jeg meldte meg på en treningstime klokka fire om morgenen og møtte opp av en eller annen grunn.",
    "Beltet mitt sprakk i to da jeg skulle dra. Jeg har ingen reservebelte.",
    "Jeg satte meg på noe mystisk på bussen og må hjem for å skifte klær.",
    "En hermetikkboks med tomatsaus eksploderte i vesken og ødela ladekabelen.",
    "Jeg fikk en propp i lommen der mobillader er.",
    "Vinden blåste originaldokumentet mitt vekk akkurat da jeg åpnet bilen.",
    "Jeg klappet nabohunden og den rev leietillatelsen min.",
    "Skummet fra kaffemaskinen min sprang lekk og kastet varm kaffe på skjortefortet.",
    "Jeg leide sykkel i morges og den gikk i stykker midt på veien.",
    "Jeg ødela skoen min da takrennen rant over og traff meg.",
    "Barnet mitt laget kunst på kjøkkenveggen klokken fem i morges og jeg kan ikke forstå det.",
    "Jeg gled på is på fortauet og mistet termos og kaffekopp.",
    "Hunden min tok skoen min opp på taket og jeg vet ikke hvordan.",
    "Jeg krasjet i en ny bussdemonen fordi jeg leste.",
    "Jeg åpnet feil dør hos naboen og satte meg ned på kjøkkenet deres før jeg la merke til det.",
    "Noen parkerte for nær og jeg kan ikke åpne bildøren.",
    "Soppen min i drivhuset er i nødstilstand og trenger spesiell behandling.",
    "Jeg sølt all morgenkaffe på skrivebordet og tastaturet.",
    "Tommelen min er frosset fast til postkassen.",
    "Jeg kjøpte feil størrelse klær i går og problemet er åpenbart.",
    "Klokken i stuen begynte å slå 23 ganger om natten og vekket meg.",
    "Naboen min får kledning og materialene er farlig nær bilen min.",
    "Jeg er usikker på om hunden min leker et spill eller faktisk er syk.",
    "Jeg fant en yoghurtboks i stedet for skoen min i støvleskapet.",
    "Katten min lærte seg å åpne kjøleskapet og gjemte maten min.",
    "Jeg hørte på feil podcast og havnet utilsiktet på et symposium om selvstyreteori.",
    "Jeg mistet nøkkelen til postkassen og posten min er der inne.",
    "Jeg tørket kjøkkenvinduet og falt inn i det.",
    "Vaskemaskinen min sang høyt om natten og fikk bussbevissthet.",
    "Jeg falt oppover trappen i stedet for ned.",
    "En ananas i matbutikken sto i veien for meg og jeg falt over den.",
    "Katten min synger høyt klokken tre om morgenen og jeg kan ikke sove.",
    "Jeg vasket meg i mørket og kledde på meg klærne i feil rekkefølge.",
    "Solbrillestativet mitt brakk og jeg er for lysfølsom til å kjøre.",
    "Jeg satte brød i brødristeren og glemte at den var på fra i går. Kjøkkenet trenger ventilering.",
    "Et brev fra skattemyndighetene kom i morges og jeg må svare umiddelbart.",
    "Bussen var uten klimaanlegg og jeg er veldig varmfølsom.",
    "Jeg glemte hvor jeg parkerte og leter fortsatt.",
    "Jeg overforberedte meg til møtene i dag og er for trøtt for tidlig.",
    "Vi oppdaget en sprekk i kjøkkenveggen i morges og dette må løses umiddelbart.",
    "Jeg gled på stigen da den knakk under meg.",
    "Smørbrødet mitt gikk i stykker da jeg tok i det og alt havnet på gulvet.",
    "Jeg har blitt skylt i kraftig regn og er gjennomvåt og trenger å skifte.",
    "Jeg knakk hånden min da jeg skled inn i bilen.",
    "Katten min hoppet på meg mens jeg sov og jeg rullet ut av sengen.",
    "Katten kom seg inn i arbeidsvesken min og gnog opp alle dokumentene.",
    "Jeg glemte bilen på feil sted og den ble tauet bort.",
    "Stigen min knakk da jeg skulle hente noe på øverste hylle.",
    "Toalettet mitt begynte å flomme i morges og vannet renner fortsatt.",
    "Jeg er fast ved inngangsdøren fordi dørknappen falt av.",
    "Vinden blåste døren igjen og låste meg ute da jeg var ute.",
    "Jeg er fortsatt i pyjamas fordi vaskemaskinen har alle klærne mine.",
    "Kulepennen min var gammel og eksploderte da jeg tok i den.",
    "Hunden min er på lydighetsopplæring og kan ikke forlates etter at den begynte.",
    "Jeg rennet gjennom svømmebasseng men glemte natten å planlegge reisen.",
    "Jeg vasket meg med klærne jeg skulle jobbe i og de er våte.",
    "Jeg satte meg ned i stolen min og knakk den.",
    "Jeg gikk til feil møte og er nå i et annet kontorbygg.",
    "Skinnjakken min frøs fast til bilen og kan ikke spennes opp.",
    "Forsetesvesken min er fast under en annen bil.",
    "Jeg tok på naboens jakke, ikke min, og utseendet er annerledes.",
    "Jeg satte meg ned i kaffe som sto på stolen min.",
    "Jeg tok lettere bukser enn vanlig og lommeboken falt ut på gangen.",
    "Trostel min synger så høyt at jeg ikke kan tenke.",
    "Jeg mistet speilet mitt mens jeg vasket.",
    "Kniven min falt og traff tærne mine da jeg lagde frokost.",
    "Kofferten min er fast under sengen og jeg kan ikke dra den ut.",
    "Jeg falt da jeg løftet av meg vesken.",
    "Sengen min brettet seg ut og falt ned på meg da jeg skulle stå opp.",
    "Veikryss mellom gatene er stengt på grunn av veiarbeid i dag.",
    "Hunden min har låst seg inn hos naboen og trenger at jeg henter den.",
    "Jeg blandet bilnøklene mine med naboens og han er på reise.",
    "Jeg må vente hjemme på grunn av en pakkeleveranse som skal komme i dag.",
    "Dekket mitt punkterte da jeg kjørte til jobb.",
    "Nøkkelen brakk i lås da jeg skulle åpne bilen.",
    "Jeg måtte ta hunden til veterinæren og den er fortsatt der.",
    "Jeg knakk bilruten mens jeg rengjorde den i morges.",
    "Olje lekket ut av bilen min og jeg venter på hjelp.",
    "Jeg sto i kø på bensinstasjonen og køen er enorm.",
    "Brikkestrimlen i bilvinduet er fast og jeg kan ikke åpne vinduet for å betale.",
    "Bilen vår starter ikke — på en eller annen måte er tenningsbryteren ødelagt.",
    "Bildekket mitt sprakk da jeg parkerte i morges.",
    "Jeg måtte kjøre søsteren min til sykehuset og er fortsatt der med henne.",
    "Bilen trenger oljeskifte før jeg kan kjøre lenger.",
    "Jeg mistet bilnøklene i en kloakk i gaten.",
    "Bilhjulene frøs fast over natten og trenger tining.",
    "Dekkene trengte utskifting og serviceteknikeren kommer ikke før middag.",
    "Jeg oppdaget at bremsen på bilen er veldig løs og må til service.",
    "Rattet er for stivt i kulde og trenger oppvarming før jeg kan kjøre.",
    "Taket på huset trenger akutt reparasjon på grunn av lekkasje da jeg våknet.",
    "Jeg har vært i telefonkø med internettleverandøren hele natten og venter fortsatt.",
    "Ventilasjonen i huset stoppet og vi venter på en murer.",
    "Jeg må ta meg av elektriske forhold før jeg kan dra.",
    "Lysglødepærer i stuen sprakk alle på en gang og det er mørkt her inne.",
    "Jeg må møte på en informasjonssamling om kjøretillatelse for bilen min.",
    "Jeg oppdaget en vannskade fra rørledninger i leiligheten i morges og trenger rørlegger.",
    "Kjøkkengassen min trenger utskifting og teknikeren kommer i morgen.",
  ],
  believable: [
    "Jeg har en legeavtale jeg hadde glemt helt til i morges.",
    "Barnet mitt er sykt og jeg fant ingen til å passe det.",
    "Bilen min starter ikke — batteriet er dødt.",
    "Jeg har kraftig hodepine og kan ikke stirre på en skjerm.",
    "Barnevakten avbestilte i siste liten.",
    "En familienødsituasjon som jeg ikke kan diskutere nå.",
    "Jeg har flate dekk på vei hit.",
    "Den eldre forelderen min trenger å komme til sykehus i dag.",
    "Jeg våknet med matforgiftning og det er ikke pent.",
    "Ryggen min gikk og jeg kan knapt bevege meg.",
    "Jeg sitter fast i en uventet trafikkork — motorveien er helt stengt.",
    "Togreisen min ble avlyst uten varsel.",
    "Skolen ringte — feber, jeg trenger å hente barnet.",
    "Jeg har mage-tarminfeksjon og vil ikke smitte andre.",
    "Vannrørene sprakk over natten og det er vann overalt.",
    "Det er en gasslekkasje og fagmannen er på vei.",
    "Jeg er i en jury som ble bekreftet i morges.",
    "Jeg har en veldig alvorlig sykdom som trenger hvile.",
    "Fastlegen min bestilte meg inn i morges og jeg kunne ikke avlyse.",
    "Jeg har hatt kramper og har vært til lege.",
    "Fysiske skader fra i går trenger oppfølging i dag.",
    "Jeg skal til en operasjon jeg ikke torde fortelle om.",
    "Barnet mitt brakk armen i barnehagen i går.",
    "Måtte ta spedbarnet til en spesiell undersøkelse.",
    "Jeg trenger å være hjemme på grunn av en fagperson som skal komme.",
    "Huseieren min trenger tilgang til leiligheten for inspeksjon.",
    "Elektrikeren er på vei og dette er en kritisk nødreparasjon.",
    "Jeg venter på resultater fra en undersøkelse på sykehuset.",
    "Alvorlige allergireaksjoner har plaget meg over natten.",
    "Jeg trenger å være hos en nærstående som er i en vanskelig psykologisk prosess.",
    "Barnet mitt er diagnostisert med en smittsom sykdom og vi trenger karantene.",
    "Ambulansen kom for et familiemedlem og jeg er fortsatt på sykehuset.",
    "Jeg trenger hjelp til å ta vare på en eldre forelder som falt i natt.",
    "Leilighetens leier ble tvangsflyttet uten tillatelse og jeg trenger å ordne juridisk.",
    "Barnet mitt trenger spesiell pedagogisk vurdering som bare er tilgjengelig i dag.",
    "Tannen min brakk og det er veldig vondt og trenger akutt tannbehandling.",
    "Jeg har øyeverk og legen kan finne noe alvorlig.",
    "Jeg trenger å gå til en kreftscreening jeg hadde glemt.",
    "Hjemmehjelperen min trenger å undertegne noe denne dagen.",
    "En av kollegene mine er alvorlig syk og jeg trenger å hjelpe familien.",
    "Bilen min ble stjålet og jeg trenger å rapportere det til politiet.",
    "Låseimittenten min sviktet og jeg er låst inne og venter på låsesmed.",
    "Barneskolen min er stengt på grunn av uventede omstendigheter og barna er hjemme.",
    "Jeg fikk feil medisin fra apoteket og trenger å dra tilbake.",
    "En nærstående trenger hjelp til behandlingsressursene sine.",
    "Utleieren trenger tilgang til leiligheten for inspeksjon på grunn av forstyrrelse.",
    "Jeg har hatt høy feber i tre dager og drar endelig til legen.",
    "Rattet mitt ble skadet i trafikklyset og jeg trenger reparasjon.",
    "Jeg henter barnet mitt fra skolen på grunn av mobbing som trenger øyeblikkelig diskusjon.",
    "Jeg har et fastlåst psykologmøte i dag som jeg ikke kan utsette.",
    "Bestemor min gikk bort og jeg trenger å være hos familien.",
    "Medisinen min trenger fornyelse og farmasøyten er bare tilgjengelig i dag.",
    "Operasjonen min er utsatt og ny time er akkurat i dag.",
    "Jeg har krampesmerter og trenger hvile.",
    "Viktige skoleresultater for barnet mitt krever upartisk behandling.",
    "Jeg trenger å levere dokumenter til en klagemyndighet som utløper i dag.",
    "Jeg er syk og legeattest er allerede på vei til dere.",
    "Ambulansen ble tilkalt for familien min i natt.",
    "Smertene i kneet mitt er blitt så ille at jeg ikke kan gå.",
    "Jeg trenger å gå til en MR-undersøkelse på grunn av det som kom opp på forrige undersøkelse.",
    "Barnet mitt trenger spesifikk oppfølging på grunn av et utviklingsproblem.",
    "Et husstandsmedlem trenger å komme til akuttmottaket og jeg trenger å kjøre.",
    "Barnet er i en heftig sykdom og trenger foreldrene sine.",
    "Jeg er på besøk på sykehuset på grunn av en nabo som ikke har noen andre.",
    "Jeg trenger å møte til advokat i nødstilfelle om arveoppgjør.",
    "Kravet om å møte til barnevernsnemndsøkt kommer i dag.",
    "Kjøpskontrakt for hus skal underskrives og kjøperen kan bare i dag.",
    "Jeg har en medisinbivirkning som påvirker kjøreevnen min.",
    "Akutt service på kjøkkenet på grunn av vannskadesituasjon.",
    "Sykehuskonsultasjon om tilstand som veier tungt på hjertet mitt.",
    "Bilen min er hos veihjelpen og jeg venter.",
    "Jeg trenger en full gjennomgang av bilen min før jeg kan kjøre.",
    "Halsbetennelsen min er så ille at jeg knapt kan svelge.",
    "Jeg trenger å ta meg av en komplisert juridisk sak som strekker seg over dagen.",
    "Jeg kom til en brann i nærheten og trenger å være til stede.",
    "Lavt blodtrykk har vært et problem og jeg trenger hvile.",
    "Stillheten og vanskeligheten etter tap av en nær krever hjemstedsopphold.",
    "Jeg trenger å ta vare på brorens barn på grunn av en nødsituasjon.",
    "Loven krever at jeg møter til en rettshøring denne dagen.",
    "Jeg har et pusteproblem som trenger spesiell undersøkelse.",
    "Klinikken jeg er registrert ved er kun åpen denne dagen.",
    "Jeg trenger å møte til en kirurgisk vurdering på grunn av allerede diagnostiserte symptomer.",
    "Tannsmerten min er blitt så alvorlig at jeg trenger akutt tannlegeservice.",
    "Jeg er fastlåst i arrangementene for foreldredag på skolen.",
    "Jeg trenger å ta hånd om godkjenningsprosessen for bolig- og tjenestetilgang.",
    "Advokatene mine trenger underskriften min på viktige dokumenter i dag.",
    "Jeg trenger spesialstilling for depresjon som trenger behandling øyeblikkelig.",
    "Vedlikeholdsproblemet på huset krever umiddelbar oppmerksomhet.",
    "Jeg oppdaget en vannskade fra ledninger i leiligheten i morges.",
    "Komfyren min tok fyr og jeg trenger hjelp.",
    "Jeg trenger å ta vare på eldre foreldre over lengre tid denne uken.",
    "Redningstjenesten er på vei etter barnets ulykke.",
    "Jeg trenger å delta i skolestyremøte som bare er i dag.",
    "Barnet mitt er utestengt fra skolen på grunn av et fysisk problem.",
    "Jeg har en tyngde på hjertet og trenger hvile for å bli bedre.",
    "Jeg trenger hvile på grunn av en kompleks behandlingsprosess som fremdeles pågår.",
    "Jeg trenger å delta i nødsmøte om familieøkonomien hjemme.",
    "Sykehuset trenger en nærmere vurdering av tilstanden min i morges.",
    "Medisinen min trenger gjennomgang av spesialist som bare er tilgjengelig i dag.",
    "Den kirurgiske konsultasjonen min er flyttet til denne dagen.",
    "Jeg trenger hvile etter en akutt tanntrekking som ble gjort i går.",
    "Barnet mitt har feber og trenger meg hjemme.",
    "Jeg trenger umiddelbart å ta seg av en familiesak som dukker opp.",
    "Medisinen min trenger spesialresultater som er klare i dag.",
    "Jeg trenger spesiell hjelp til et funksjonshemmet familiemedlem.",
    "Fødselsdagen til en nærstående gjør at jeg trenger å være hjemme.",
    "Jeg trenger å være på jordmorkonsultasjon med ektefellen min.",
    "Spesiell finansiell nød trenger å løses umiddelbart.",
    "Jeg trenger å gå til en psykisk helsevurdering i dag som jeg ikke kan utsette.",
    "Jeg trenger hvile etter en øyeoperasjon som ble gjort i går.",
    "Jeg trenger å ta vare på et barn som er i karantene.",
    "Jeg trenger umiddelbart å delta i rapportskriving der jeg er vitne.",
    "Barnets verge trenger meg i et møte i dag.",
    "Jeg trenger spesiell hvile på grunn av diabetesbehandling som trenger overvåking.",
    "Barnet mitt trenger et vaksinepass som må være klart før skolestart.",
    "Jeg trenger å håndtere fødselspermisjon knyttet til foreldrepermisjonstiltak.",
    "Jeg trenger å møte til spesiell karriereveiledning for barnets skolevalg.",
    "Her hjemme trenger en byggmester å se på fukt i murverket.",
    "Jeg er syk med relaterte plager som krever hvile.",
    "Barnet mitt fikk en karakter som trenger advokatbistand for å bestride.",
    "Jeg trenger å sitte ved siden av forelderen min på kirurgisk konsultasjon.",
    "Jeg gikk på feil medikamentblanding og trenger overvåking.",
    "Håndverkeren er på vei for å reparere døren som gikk i stykker.",
    "Jeg har sterke magesmerter og trenger å komme til akuttmottaket.",
    "Jeg trenger fornying av spesialmedisin som bare er tilgjengelig i dag.",
    "Jeg trenger å møte til skolestyremøte på grunn av endret pensum.",
    "Barnelegen trenger kontroll på barnet mitt på grunn av et utviklingsproblem.",
    "Plutselig karantene hjemme betyr at jeg ikke kan komme inn på arbeidsstedet.",
    "Jeg trenger reparasjon av støtteskinner som knakk denne morgenen.",
    "Jeg trenger å være til stede for politiet på grunn av innbrudd i garasjen min.",
    "Jeg trenger en pasientkonsultasjon som bare er registrert i dag.",
    "Et familiemedlem trenger motivasjon og støtte i dag.",
    "Jeg trenger hvile på grunn av øyekramper i natt.",
    "Varmesystemet i huset eksploderte og vi er uten varme.",
    "Advokaten min trenger underskriften min på viktige dokumenter i dag.",
    "Jeg trenger spesiell hvile på grunn av behandling av utmattelse.",
    "Gasservice trenger å komme og fikse lekkasjen vi oppdaget.",
    "Jeg er syk med smittsom sykdom og vil ikke smitte kolleger.",
    "Trappen min hjemme knakk og trenger utskifting.",
    "Jeg trenger hvile etter medisinkur som har sterke bivirkninger.",
    "Jeg trenger spesiell psykologhjelp i dag på grunn av et sammenbrudd som oppsto.",
    "Barnet mitt fikk sykdom som trenger spesiell isolasjon.",
    "Jeg trenger hvile på grunn av svimmelhet og kvalme.",
    "Jeg trenger spesiell hvile på grunn av skader jeg pådro meg forrige måned.",
    "Jeg trenger nøkkel for å åpne nye låser etter at gammel nøkkel knakk.",
    "Hemmelige dokumenter krever varsling til myndigheter denne dagen.",
  ],
  chaotic: [
    "Jeg våknet i en annen by uten å huske at jeg dro dit.",
    "Naboen min flytter og trenger hjelpen min siden klokken fem i morges.",
    "Redningstjenesten er utenfor huset mitt og jeg vet ikke hvorfor.",
    "Jeg er på vei men en steinblokk er i veien på motorveien.",
    "Reven min er fast i takrennene til naboen og jeg trenger å redde den.",
    "Politiet ba meg bli hjemme mens de undersøker noe.",
    "Hunden min rømte og er nå hos politiet i en annen by.",
    "Jeg finner ikke bilen min. Parkerte sannsynligvis et sted i går.",
    "Jeg prøver å redde en fugl som krasjet i vinduet og er svimmel.",
    "Dagligvarebutikken ble tatt som gissel akkurat da jeg skulle kjøpe frokost.",
    "Jeg er midt i et drivstoffstreik og bensinen er nesten tom.",
    "Tidsmaskinen min knakk og jeg er ikke sikker på hvilken dag det er.",
    "Jeg er fast mellom etasjer i en heis.",
    "Veien fra huset mitt er dekket av sauelam.",
    "Katten min falt av trappen og trenger redning.",
    "Jeg fikk et uventet besøk fra en fjern slektning som kom fra et annet land.",
    "Kommunen er fraflyttet og jeg finner ikke huset mitt.",
    "En tilfeldig nyhet fikk meg til å løpe ut av huset og jeg prøver fortsatt å komme meg tilbake.",
    "Et gigantisk nabolagsveddeløp forårsaket total gatestengning.",
    "Den selvkjørende bilen min tok ferie og er nå i en annen bydel.",
    "Toget jeg er på har stoppet i en tunnel og vi er fortsatt der.",
    "Hotellrommet mitt var dobbeltbooket og jeg er fortsatt på kontoret og prøver å løse det.",
    "Flyet mitt ble omdisponert og jeg er nå på feil flyplass.",
    "Hundetreneren min har trent hunden til å rive opp planleggingsplaner.",
    "Jeg ble tatt som gissel på et treningsstudio og er nylig løslatt.",
    "Et spill på bakeriet tok meg på sengen og jeg mistet køen.",
    "Sikkerhetsvakten på arbeidsstedet ville ikke slippe meg inn uten ID-kortet.",
    "Jeg mistet lommeboken på vei og trenger å avbestille alle kredittkort.",
    "Folkemengden utenfor kafeen min er så stor at jeg ikke kan komme meg ut.",
    "Sikkerhetssystemet mitt hjemme ga ut falskt varsel og politiet er her.",
    "Jeg er på vei men sitter fast i et snurrende tre.",
    "Et snøskred stenger veien min og jeg kommer meg ikke til jobb.",
    "En strøm av sjødyr løp over bilen min mens den sto.",
    "En kjøretur med naboen gikk galt og landet ved en klippe.",
    "Den gamle mannen i hjørnet inviterte meg til et stort prosjekt og jeg torde ikke avslå.",
    "Jeg er midt i et snøras på en fjellvei.",
    "Ordføreren ba om hjelpen min til et spesielt prosjekt.",
    "Kommunen tok en utendørsdag og jeg måtte delta.",
    "Radiostasjonen fikk meg til å delta i en direktesendt sending.",
    "Et arkeologisk funn ble gjort i hagen min og de trenger meg.",
    "Jeg er på en redningsbåt ved Steinsfjord.",
    "Sjokoladepålegget smeltet tre stykker fordi jeg glemte dem i bilen.",
    "Hunder på gaten blokkerte fremkomsten.",
    "Skolebordet falt i takrennene.",
    "Mye pommes frites på motorveien skaper fare.",
    "Hele togstasjonen har isolert folk på grunn av en stor lekkasje.",
    "Fra frokost til middag: leter etter stjålet bil som ble tatt i god tro.",
    "Naboene feiret nyttår på feil dato.",
    "Lavtflyende fly var over bilen min og var hindrende.",
    "Jeg er fast i store ruiner ved en gammel sandskole.",
    "Jeg tok veien og dro helt til Tromsø i stedet for Oslo.",
    "En stor flyskadeadvarsel på landingsbanen kryss av reisen min.",
    "Gasslekkasje på motorveien krever stenging av hele området.",
    "Jeg mistet rommelsnøklene mine og leter fortsatt.",
    "Båtreisen min ble forsinket på grunn av røyk på et gammelt skip.",
    "Et verdensnyhetsscene ble registrert denne morgenen og jeg er vitne.",
    "All gate stengt på grunn av lekkasje på en hoved vannledning.",
    "Jeg satt over likestillingskonferansen som tok hele dagen.",
    "Jeg er fast i et spesialprosjekt for kommunen som de holder hemmelig.",
    "En stor brann i nærheten krever redningstjeneste og jeg kan ikke komme frem.",
    "Jeg er fast i vegarbeid som ble forsinket på grunn av ulykken i går.",
    "Folkemengde rundt gaten min tillater ikke fremkomst.",
    "En nasjonal festival er på denne gaten i dag og trafikken er stengt.",
    "Jeg er invitert til et spesielt besøk på en offentlig institusjon.",
    "Her er det lavt tak og det trengs reparasjon umiddelbart.",
    "Et stort kriseprosjekt hos naboen trenger hjelp.",
    "Jeg er på vei men gangbroen er stengt på grunn av en avtale.",
    "Jeg er fastlåst i oppdragelsesmetoder som krever heldagsnærvær.",
    "Ulykken på motorveien trenger vitner og jeg var på stedet.",
    "Jeg er blant redningstjenesten som trenger hjelp i vanskelige situasjoner.",
    "Et romskip landet i nærheten av meg og de trenger meg.",
    "Jeg ble valgt som dommer i en stor konkurranse og kan ikke nekte.",
    "Rådgivningstjenesten min til naboen tok hele dagen.",
    "Jeg trenger å være ved siden av en nærstående i en spesiell personlig prosess.",
    "Advokaten min krever at jeg møter til møte denne dagen.",
    "Administrerende direktør i selskapet trenger min spesielle hjelp.",
    "Jeg er fast mellom ferjer.",
    "Alle veivisningssystemer er lagret utenfor serviceområdet.",
    "Bilen min holdt på å kjøre og kom i kø på vei hjem.",
    "Jeg er invitert til et spesialmøte som jeg ikke tør avslå.",
    "Nøyaktighet i oppgjør krever min deltakelse.",
    "Barnet mitt ble tatt til feil skole og trenger oppgjør.",
    "Naboene mine holder en utrolig stor fest som brøt ut på fortauet.",
    "Jeg er i kø på en tjeneste som bare vil ta 5 minutter når jeg kommer frem.",
    "Jeg trenger å delta i nøyaktig registrerte diskusjoner.",
    "Det paradoksale problemet med telekommunikasjonsnett krever min hjelp.",
    "Jeg er fastlåst i et møte som ble innkalt i siste minutt.",
    "Moteriktige hunder løp over bilen min på vei til jobb.",
    "Jeg er fortsatt på hjemvei fra midnatt på grunn av et utflukt som gikk av stabelen.",
    "Bussjåføren var en jeg kjente og vi dro på en ekstratur.",
    "Jeg prøvde å gjøre noe godt og det strakte seg til en hel dag.",
    "En nasjonal konkurranse startet på gaten min da jeg var på vei.",
    "Jeg havnet på feil sider på internett og trenger teknisk veiledning.",
    "Rosiner-hendelser tok opp hele morgenen.",
    "Jeg trenger å fullføre et nødprosjekt som ikke kan utsettes.",
    "Jeg er langt borte fordi ringen min ville se meg.",
    "Jeg trengte spesielt utstyr som bare var tilgjengelig langt borte.",
    "Et viktig prosjekt besøkte meg på arbeidsstedet og tok hele dagen.",
    "Jeg er i ferd med å ta del i et spesielt samfunnsoppdrag.",
    "Direktøren min trengte rådgivning og vi diskuterte på en lang rundtur.",
    "Jeg er på spesialvei for å undersøke et naturfenomen.",
    "Jeg trenger å være til stede på et spesielt arrangement i nærheten.",
    "Jeg befinner meg i en soneblokade på grunn av sikkerhetsspørsmål.",
    "Jeg ble bedt om faglig ekspertinformasjon på et spesialistmøte.",
    "Jeg sitter fast i en bilkø som dekker hele området.",
    "En folkelig sangkonkurranse fikk meg til å bli syk.",
    "Jeg trenger å løse komplekse systemproblemer som dukket opp i natt.",
    "En spesiell undersøkelse av nabolaget krever min tilstedeværelse.",
    "Jeg er på feil vei til en rask sykkelstrekning.",
    "Hussalget mitt krever mer undersøkelse enn forventet.",
    "Jeg er på vei til et spesialt nøyaktighetsintervju.",
    "Et nasjonalt arrangement på åpne plasser krever min deltakelse.",
    "Jeg er i ferd med å delta i noe som har harmonisk deltakelse.",
    "Radiotilnærmingen min krever spesiell deltakelse.",
    "Jeg er på feil vei til en strømsykkelstrekning.",
    "En ny bolig krever spesiell inspeksjon i dag.",
    "Jeg er ved reisemålet for spesielle prosjekter.",
    "Jeg er en forløper til et spesielt nasjonalt arrangement.",
    "Ny planlegging krever min spesielle deltakelse.",
    "Jeg er på et spesielt prosjekt som krever heldagsnærvær.",
    "Et gratis besøk fra en spesiell person krever heldagsnærvær.",
    "Jeg trenger å møte på et komplekst introduksjonsmøte.",
    "Jeg er på vei til en spesiell sirkulasjonsundersøkelse.",
    "Jeg trenger spesiell hvile på grunn av skader.",
    "Jeg er på en samling for spesielle undersøkelser.",
    "En spesiell opplæringsøkt krever mitt heldagsnærvær.",
    "Jeg er på spesiell deltakelse denne dagen.",
    "Et nytt foreningsprosjekt krever min spesielle deltakelse.",
    "Jeg er på vei til en spesiell konferanse.",
    "Et spesielt møte krever min tilstedeværelse.",
    "Jeg er på en spesiell aldersundersøkelse.",
    "Et nytt samarbeid krever spesiell deltakelse i dag.",
  ],
  dark: [
    "Jeg finner meg ikke i stand til å møte opp i dag. Trenger litt tid.",
    "Jeg sliter med personlige ting som trenger å løses før jeg kan konsentrere meg om jobb.",
    "Den mentale helsen min trenger hvile i dag.",
    "Jeg er veldig sliten og trenger fornying.",
    "Jeg takler noe vanskelig og trenger dagen til det.",
    "Jeg har det ikke bra i dag og trenger hvile.",
    "Jeg trenger psykologisk plass til å takle noe som skjedde.",
    "Jeg går gjennom en vanskelig periode og trenger støtte.",
    "Fysisk og mental utmattelse har bygget seg opp og jeg trenger hvile.",
    "Jeg prøver å takle sorg etter å ha mistet en nær.",
    "Jeg trenger dagen til å arbeide gjennom vanskelige følelser.",
    "Jeg er ikke i stand til å jobbe i dag og trenger å ta vare på meg selv.",
    "Jeg sliter med angst som trenger oppmerksomhet.",
    "Dette er en vanskelig dag for meg og jeg trenger å være hjemme.",
    "Jeg prøver å komme gjennom personlige vanskeligheter.",
    "Jeg har hatt søvnforstyrrelser og er veldig sliten.",
    "Jeg trenger ensomhet og ro til å arbeide gjennom noe.",
    "Jeg mottar støtte for noe personlig og kan ikke møte.",
    "Jeg trenger dagen til å reorganisere livet mitt.",
    "Jeg sliter med sorg etter et tap.",
    "Jeg lærer å leve med en ny virkelighet.",
    "Jeg trenger psykologisk hvile fra dagens stress.",
    "Jeg sliter med konflikter og trenger plass til å tenke.",
    "Jeg trenger støtte i denne perioden.",
    "Mentale utfordringer krever at jeg er hjemme.",
    "Jeg er ikke i stand til å konsentrere meg i dag på grunn av personlige saker.",
    "Jeg trenger hvile på grunn av emosjonell utmattelse.",
    "Jeg takler noe som er mer enn jobb kan løse.",
    "Jeg er i behandling som krever hvile i dag.",
    "Jeg trenger tid til å gjenopprette balansen min.",
    "Jeg sliter med noe som trenger personlig oppmerksomhet.",
    "Jeg trenger hvile for å forhindre forverring av helseproblemer.",
    "Jeg er sliten på trøtthet og trenger dagen.",
    "Jeg har gitt så mye og trenger omsorg.",
    "Jeg arbeider gjennom noe som skjedde nylig og lytter til kroppen min.",
    "Jeg trenger tid til å gjøre opp med meg selv.",
    "Jeg sliter med angst og depresjon og trenger omsorg.",
    "Jeg er i psykologisk behandling og trenger en dag til det.",
    "Jeg trenger hvile på grunn av utmattelse som er emosjonell.",
    "Jeg arbeider gjennom traumer og trenger plass til det.",
    "Jeg takler ensomhet og trenger tid til å gjøre noe med det.",
    "Jeg trenger mental helsestøtte i dag.",
    "Jeg er sliten av å late som og trenger dagen til å være meg selv.",
    "Jeg arbeider gjennom vanskelige effekter av nylige hendelser.",
    "Jeg trenger tid til å komme tilbake i balanse.",
    "Jeg sliter med stress som har bygget seg opp over lang tid.",
    "Jeg trenger dagen til å bruke behandlingsressurser.",
    "Jeg prøver å finne en vei gjennom noe vanskelig.",
    "Jeg trenger plass til å tenke og hvile.",
    "Jeg takler vanskelige omstendigheter som krever at jeg er hjemme.",
    "Jeg trenger litt lett hvile etter en lang periode.",
    "Jeg sliter med sorg som trenger tid.",
    "Jeg trenger ro til å arbeide gjennom noe vanskelig.",
    "Jeg sliter med mentale helseutfordringer som trenger oppmerksomhet.",
    "Jeg trenger hvile fra arbeidsstress.",
    "Jeg er veldig sliten og trenger hvile.",
    "Jeg sliter med noe personlig som trenger tid.",
    "Jeg trenger behandling på grunn av det som skjer.",
    "Jeg arbeider gjennom vanskelige følelser som trenger tid.",
    "Jeg trenger tid til å ta vare på meg selv og være hjemme.",
    "Jeg takler en vanskelig periode og trenger plass til det.",
    "Jeg trenger støtte fra nærstående i dag.",
    "Jeg sliter med indre konflikter som trenger lytting.",
    "Jeg trenger en dag til å se over alt og oppnå balanse.",
    "Jeg er veldig sliten av en lang prosess og trenger hvile.",
    "Jeg trenger tid til å arbeide gjennom vanskelige effekter.",
    "Jeg går gjennom store endringer og trenger hvile.",
    "Jeg trenger en dag til å være med meg selv.",
    "Jeg har glemt meg selv og trenger en dag til å gjenfinne meg.",
    "Jeg trenger objektiv hvile på grunn av stress.",
    "Jeg sliter med emosjonelle utfordringer som trenger omsorg.",
    "Jeg trenger hvile på grunn av utmattelse som har bygget seg opp.",
    "Jeg går gjennom noe og trenger tid til å gjøre opp.",
    "Jeg trenger en dag til å fokusere på den mentale helsen min.",
    "Jeg tåler noe som trenger hvile.",
    "Jeg trenger tid til å gå gjennom noe personlig.",
    "Jeg er sliten av rollen min og trenger hvile.",
    "Jeg trenger en dag til å hvile på grunn av stress.",
    "Jeg sliter med angst og trenger hvile.",
    "Jeg trenger tid til å finne ut av hvor jeg befinner meg.",
    "Jeg arbeider gjennom vanskelige livshendelser.",
    "Jeg trenger lyttende og proporsjonal hvile.",
    "Jeg takler personlige problemer som trenger tid.",
    "Jeg trenger en dag til å komme tilbake til meg selv.",
    "Jeg er sliten og trenger dagen til å være hjemme og hvile.",
    "Jeg sliter med noe og trenger plass til det som pågår.",
    "Jeg sliter med et vanskelig livsproblem og trenger tid.",
    "Jeg trenger hvile for å bli bedre.",
    "Jeg får hjelp med mentale utfordringer og trenger en dag til det.",
    "Jeg trenger tid til å gå gjennom noe vanskelig.",
    "Jeg sliter med noe som trenger behandling.",
    "Jeg trenger en dag til å stanse og hvile.",
    "Jeg er på vei til spesiell behandling for angst.",
    "Jeg trenger lyttende og hvile i dag.",
    "Jeg sliter med noe som krever konsentrasjon og hvile.",
    "Jeg trenger en dag til å gå over det som skjer.",
    "Jeg er sliten og utilpass og trenger hvile.",
    "Jeg går gjennom vanskeligheter som trenger tid.",
    "Jeg trenger å være hjemme for å ta vare på sjelen min.",
    "Jeg takler noe personlig som trenger hvile.",
    "Jeg trenger en dag til å finne fred.",
    "Jeg sliter med vanskelige omstendigheter og trenger plass til å gjøre noe med det.",
    "Jeg trenger hvile på grunn av utmattelse fra stress.",
    "Jeg arbeider gjennom noe som skjedde og trenger tid.",
    "Jeg trenger en dag til å gjenopprette sinn og sjel.",
    "Jeg er sliten av et for travelt liv og trenger hvile.",
    "Jeg sliter med noe som trenger hvile og ro.",
    "Jeg trenger en dag til å komme tilbake som person.",
    "Jeg går gjennom en vanskelig overgangstid og trenger tid.",
    "Jeg er sliten og trenger dagen til å være meg selv.",
    "Jeg trenger hvile og fred i dag.",
    "Jeg arbeider gjennom noe vanskelig og trenger plass til det.",
    "Jeg trenger en dag til å være hjemme og ta vare på meg.",
    "Jeg takler noe som trenger hvile og lytting.",
    "Jeg trenger tid til å lade opp og få energi.",
    "Jeg er sliten og trenger dagen til å være meg selv.",
    "Jeg sliter med noe personlig og trenger hvile.",
    "Jeg trenger en dag til å gå gjennom vanskelige følelser.",
    "Jeg sliter med livsomstendigheter som krever at jeg er hjemme.",
    "Jeg trenger hvile på grunn av opphopet belastning.",
    "Jeg takler noe som trenger ensomhet og hvile.",
    "Jeg trenger en dag til å gå gjennom dette.",
    "Jeg er sliten av daglige plikter og trenger hvile.",
    "Jeg sliter med noe som krever at jeg er hjemme.",
    "Jeg trenger en dag til å lytte til kropp og sjel.",
    "Jeg går gjennom noe som trenger tid og objektivitet.",
    "Jeg trenger hvile for å bli et bedre menneske i morgen.",
    "Jeg er sliten og trenger hvile og stillhet.",
    "Jeg arbeider gjennom vanskelige ting og trenger plass til det.",
    "Jeg trenger en dag til å stå opp og være i fred.",
    "Jeg sliter med noe som trenger tid og hvile.",
    "Jeg trenger en dag til å komme tilbake som helhetlig person.",
    "Jeg går gjennom noe vanskelig og trenger tid.",
    "Jeg trenger hvile for å komme tilbake i god stand.",
    "Jeg er sliten og trenger dagen til å være hjemme og hvile.",
    "Jeg sliter med noe som trenger hvile og ensomhet.",
    "Jeg trenger en dag til å gå over alt og hvile.",
    "Jeg takler vanskelige omstendigheter og trenger plass til det.",
    "Jeg trenger hvile på grunn av mental utmattelse.",
    "Jeg er sliten og trenger en dag til å være meg selv.",
  ],
  office: [
    "Jeg glemte passordet mitt og kan ikke logge på noe.",
    "Skriveren min er fortsatt nede og jeg trenger å skrive ut dokumenter.",
    "Kollegaen min er syk og jeg må overta prosjektene hans hjemmefra.",
    "Høyttalersystemet vårt er ødelagt og jeg kan ikke møte til møter.",
    "Internettforbindelsen min er blitt så liten at jeg ikke kan jobbe.",
    "Jeg trenger å fullføre en rapport før jeg kan møte til møtet.",
    "Prøvetakingsforespørselen min trenger behandling før jeg kan dra.",
    "Jeg glemte et viktig dokument hjemme.",
    "Møtet mitt ble flyttet og jeg trenger å reorganisere dagen.",
    "Jeg trenger tid til å forberede meg til en presentasjon som er i morgen.",
    "Jeg kan ikke møte før lydsystemet på hjemmekontoret er reparert.",
    "Jeg er i et langvarig telefonmøte med en viktig klient.",
    "Nedstengingen som kommer krever at jeg jobber hjemmefra.",
    "Jeg trenger å hente en bestilling som bare ankommer i dag.",
    "Oppsummeringen min av data er ikke ferdig og vil ta lengre tid.",
    "Systemproblemer i selskapet krever at jeg jobber hjemmefra.",
    "Jeg venter på synkronisering av viktige filer.",
    "Tekniske endringer i systemet krever at jeg jobber hjemmefra i dag.",
    "Jeg trenger å fullføre gjennomgang av dokumenter før jeg kan møte.",
    "Møtet mitt i morges ble avlyst og jeg trenger å reorganisere.",
    "Jeg trenger å jobbe hjemmefra på grunn av systemoppdatering.",
    "Regelmessige revisjoner krever at jeg er hjemme i dag.",
    "Jeg trenger tid til å sette opp den nye programvaren som ble sendt meg.",
    "Registreringsdokumenter trenger spesiell behandling hjemme.",
    "Jeg trenger å avslutte viktige kontrakter før jeg drar.",
    "Nøkkeldataene er på hjemmestasjonen og jeg trenger å fullføre dem.",
    "Systemproblemer trenger umiddelbare løsninger.",
    "Jeg er på et spesielt fjernmøte som krever heldagsnærvær.",
    "Jeg trenger tid til å gå gjennom komplekse data.",
    "Kollegaen min trenger hjelp med et prosjekt som bare jeg kan hjelpe med.",
    "Jeg trenger å jobbe med en spesiell rapport som krever konsentrasjon.",
    "Jeg venter på en viktig godkjenning før jeg kan fortsette.",
    "Systemproblemer trenger umiddelbare løsninger på hjemmekontoret.",
    "Jeg trenger tid til å forberede data til møtet i morgen.",
    "Jeg er på et spesielt fjernmøte om viktige endringer.",
    "Jeg trenger tid til å sette opp nytt utstyr som ankom i dag.",
    "Dokumenter som trenger underskrift er bare tilgjengelige hjemme.",
    "Jeg trenger tid til å gå gjennom komplekse krav.",
    "Systemproblemer trenger spesiell behandling.",
    "Jeg trenger å være på et fjernmøte som ble innkalt i siste minutt.",
    "Jeg trenger tid til å fullføre data som er nødvendige.",
    "Rapporten min trenger spesiell gjennomgang før den sendes.",
    "Systemproblemer krever at jeg jobber hjemmefra i dag.",
    "Jeg trenger å vente på synkronisering av filer som trenger å fullføres.",
    "Jeg er på en spesiell opplæringsøkt som krever heldagsnærvær.",
    "Jeg trenger tid til å gå over policy knyttet til prosjektet.",
    "Systemproblemet er stort og trenger hjelp fra en ekspert.",
    "Jeg trenger tid til å fullføre en plan som ble forespurt.",
    "Oversettelsesprosjektet trenger spesiell konsentrasjon.",
    "Jeg trenger tid til å sette opp en ny serviceavtale.",
    "Systemproblemer trenger umiddelbar service.",
    "Jeg trenger tid til å behandle data som ankom i løpet av natten.",
    "Spesiell opplæring krever heldagsnærvær.",
    "Jeg trenger tid til å gjennomgå regler som nylig ble endret.",
    "Systemproblemer trenger spesiell service.",
    "Jeg trenger tid til å fullføre krav som forfaller i dag.",
    "Jeg er på en spesiell opplæringsprosess som krever heldagsnærvær.",
    "Jeg trenger tid til å gå gjennom ny organisasjonsendring.",
    "Systemproblemer trenger omsorg og nøyaktighet.",
    "Jeg trenger tid til å ta seg av spesielle saker.",
    "Fjernmøte krever min spesielle deltakelse.",
    "Jeg trenger tid til å fullføre en spesiell analyse.",
    "Systemproblemer krever at jeg er hjemme.",
    "Jeg trenger tid til å fullføre data som trengs i dag.",
    "Spesiell undersøkelse krever mitt nærvær.",
    "Jeg trenger tid til å gå gjennom komplekse saker.",
    "Systemproblemer krever at jeg har tilgang til hjemmenettverket.",
    "Jeg trenger tid til å fullføre et viktig prosjekt.",
    "Spesiell forskning krever konsentrasjonen.",
    "Jeg trenger tid til å ta hånd om krav som forfaller.",
    "Systemproblemer trenger spesiell service.",
    "Jeg trenger tid til å fullføre en spesiell rapport.",
    "Fjernmøte krever min deltakelse.",
    "Jeg trenger tid til å behandle data som ankom.",
    "Systemproblemer trenger spesiell nøyaktighet.",
    "Jeg trenger tid til å ta seg av spesielle krav.",
    "Spesiell opplæringsøkt krever heldagsnærvær.",
    "Jeg trenger tid til å gå gjennom ny policy.",
    "Systemproblemer trenger spesiell service og tid.",
    "Jeg trenger tid til å ta hånd om komplekse data.",
    "Spesielt fjernmøte krever min deltakelse.",
    "Jeg trenger tid til å fullføre en spesiell analyse.",
    "Systemproblemer krever at jeg er hjemme.",
    "Jeg trenger tid til å ta hånd om viktige filer.",
    "Spesiell opplæring krever heldagsnærvær.",
    "Jeg trenger tid til å gå over endrede krav.",
    "Systemproblemer krever spesiell service.",
    "Jeg trenger tid til å fullføre en spesiell revisjon.",
    "Fjernmøte krever spesiell deltakelse.",
    "Jeg trenger tid til å behandle komplekse data.",
    "Systemproblemer trenger spesiell service.",
    "Jeg trenger tid til å fullføre en spesiell rapport.",
    "Spesiell forskning krever heldagsnærvær.",
    "Jeg trenger tid til å gå gjennom komplekse krav.",
    "Systemproblemer trenger spesiell omsorg.",
    "Jeg trenger tid til å fullføre et spesielt prosjekt.",
    "Fjernmøte krever min deltakelse i dag.",
    "Jeg trenger tid til å ta seg av spesielle saker.",
    "Systemproblemer krever at jeg jobber hjemmefra.",
    "Jeg trenger tid til å gå over nye krav.",
    "Spesiell opplæringsøkt krever heldagsnærvær.",
    "Jeg trenger tid til å ta seg av spesielle data.",
    "Systemproblemer trenger umiddelbar service.",
    "Jeg trenger tid til å fullføre et spesielt prosjekt.",
    "Fjernmøte krever spesiell deltakelse.",
    "Jeg trenger tid til å behandle spesielle data.",
    "Systemproblemer trenger spesiell service.",
    "Jeg trenger tid til å ta hånd om komplekse krav.",
    "Spesiell forskning krever mitt nærvær.",
    "Jeg trenger tid til å gå gjennom endret oppsett.",
    "Systemproblemer krever at jeg jobber hjemme.",
    "Jeg trenger tid til å fullføre en spesiell revisjon.",
    "Fjernmøte krever min deltakelse.",
    "Jeg trenger tid til å ta seg av spesielle dokumenter.",
    "Systemproblemer trenger spesiell service.",
    "Jeg trenger tid til å behandle komplekse data.",
    "Spesiell opplæring krever mitt nærvær.",
    "Jeg trenger tid til å gå over ny policy.",
    "Systemproblemer trenger spesiell nøyaktighet.",
    "Jeg trenger tid til å ta hånd om spesielle krav.",
    "Spesielt fjernmøte krever min deltakelse.",
    "Jeg trenger tid til å fullføre en spesiell analyse.",
    "Systemproblemer trenger spesiell service.",
    "Jeg trenger tid til å ta hånd om komplekse saker.",
    "Fjernmøte krever spesiell deltakelse.",
    "Jeg trenger tid til å behandle spesielle data.",
    "Systemproblemer krever at jeg er hjemme.",
    "Jeg trenger tid til å gå gjennom spesielle krav.",
    "Spesiell forskning krever heldagsnærvær.",
    "Jeg trenger tid til å fullføre en spesiell sak.",
    "Systemproblemer krever spesiell service.",
    "Jeg trenger tid til å ta hånd om endrede data.",
  ],
  tech: [
    "Datamaskinen min oppdaterte seg og ødela alt jeg jobbet med.",
    "Internettforbindelsen min brakk og ISP kommer ikke før sent i dag.",
    "Videokonferansetjenesten min er ødelagt og jeg kan ikke møte.",
    "Jeg trenger å tilbakestille alle systemtaster på grunn av et sikkerhetsbrudd.",
    "Sikkerhetsnøkkelen min på arbeidsstasjonen brakk.",
    "VPN-tjenesten brakk og jeg kan ikke komme inn i arbeidssystemene.",
    "Databasen jeg jobber med mistet alle data på grunn av gamle oppdateringsproblemer.",
    "Datamaskinen min er på tidslinjen og vil sannsynligvis ta hele dagen å fikse.",
    "Programvaren jeg bruker er ødelagt på grunn av en uventet oppdatering.",
    "Videokameraet på servicemøtet er ødelagt og vi kan ikke holde møte.",
    "Serveren jeg er koblet til sviktet og er nede.",
    "Jeg trenger å oppdatere arbeidsmiljøet på grunn av et sikkerhetsbrudd.",
    "Datalagringen min er full og jeg kan ikke jobbe.",
    "Systemtasten min er utløpt og jeg trenger en ny.",
    "Programmet jeg jobber med er nede på grunn av en systemoppdatering.",
    "Internettforbindelsen min er så treg at jeg ikke kan jobbe.",
    "Skjermen min brakk og jeg trenger en ny.",
    "Datamaskinen min overopphetes og starter ikke.",
    "Programvareoppdateringen ødela alle databasene mine.",
    "Jeg trenger å oppdatere sikkerhetsnøkler på grunn av regler.",
    "Arbeidsstrømmen min er ødelagt på grunn av en ny versjon.",
    "Jeg trenger å sette opp nye arbeidsverktøy som ankom i dag.",
    "Tjenerserveren min svarer ikke og jeg trenger tilgang.",
    "Datalagringen er under vedlikehold og jeg kan ikke hente data.",
    "Programvaresystemet mitt brakk på grunn av feil oppdatering.",
    "Jeg trenger spesiell tilgang til systemet som ikke er tilgjengelig.",
    "Internettforbindelsen er for svak til at videomøte er mulig.",
    "Datamaskinen min trenger spesielt vedlikehold som bare er tilgjengelig i dag.",
    "Systemet mitt brakk på grunn av en oppdatering og trenger tilbakestilling.",
    "Jeg trenger spesiell hjelp med systemoppdateringen.",
    "Internettforbindelsen min er ødelagt og trenger reparasjon.",
    "Skjermen min gikk i dvale og kommer ikke tilbake.",
    "Datamaskinen min er i en oppdatering som tar så lang tid.",
    "Passordbehandleren min brakk og jeg husker ikke passordene.",
    "Systemet mitt er ikke kompatibelt med den nye programvaren.",
    "Jeg trenger tid til å fikse innstillingene for arbeidsverktøyene.",
    "Tjenerserveren min er nede på grunn av en systemoppdatering.",
    "Databasen min trenger spesiell tilbakestilling.",
    "Programmet mitt krever spesiell konfigurasjon for å fungere.",
    "Jeg trenger spesiell tid til å sette opp nytt arbeidsmiljø.",
    "Systemet brakk og vi trenger umiddelbare løsninger.",
    "Jeg trenger spesiell hjelp med systemkonfigurasjonen.",
    "Internettforbindelsen min krever spesiell oppdatering.",
    "Datamaskinen min er under vedlikehold som tar hele dagen.",
    "Programvareoppdateringen ødela all systemoppsett.",
    "Jeg trenger spesiell tilgang som ikke er tilgjengelig nå.",
    "Datalagringen min trenger spesiell omsorg.",
    "Systemet mitt brakk og trenger spesiell tilbakestilling.",
    "Jeg trenger tid til å behandle en systemoppdatering.",
    "Tjenerserveren trenger spesiell reparasjon.",
    "Datamaskinen min trenger spesielt vedlikehold.",
    "Programmet mitt trenger spesiell konfigurasjon.",
    "Jeg trenger spesiell tid til å sette opp arbeidsmiljøet.",
    "Systemet krever spesiell tilbakestilling.",
    "Internettforbindelsen krever spesiell service.",
    "Datamaskinen min er under spesielt vedlikehold.",
    "Programvaren krever spesiell oppdatering.",
    "Jeg trenger spesiell tilgang til systemet.",
    "Datalagringen krever spesiell omsorg.",
    "Systemet brakk på grunn av en programvareproblematikk.",
    "Jeg trenger spesiell hjelp med et teknisk problem.",
    "Tjenerserveren krever spesiell service.",
    "Datamaskinen min krever spesiell reparasjon.",
    "Programmet krever spesiell oppdatering.",
    "Jeg trenger spesiell tid til å fikse systemet.",
    "Systemet krever spesiell service.",
    "Internettforbindelsen trenger spesiell reparasjon.",
    "Datamaskinen min trenger spesiell tilbakestilling.",
    "Programvaren trenger spesiell oppdatering.",
    "Jeg trenger spesiell tilgang til å jobbe.",
    "Datalagringen trenger spesiell omsorg.",
    "Systemet krever spesiell tilbakestilling.",
    "Tjenerserveren trenger spesiell reparasjon.",
    "Datamaskinen min trenger spesiell konfigurasjon.",
    "Programmet trenger spesiell reparasjon.",
    "Jeg trenger spesiell tid til å sette opp nye enheter.",
    "Systemet trenger spesiell tilbakestilling.",
    "Internettforbindelsen trenger spesiell service.",
    "Datamaskinen min trenger spesielt vedlikehold.",
    "Programvaren trenger spesiell konfigurasjon.",
    "Jeg trenger spesiell tilgang til arbeidsystemet.",
    "Datalagringen trenger spesiell behandling.",
    "Systemet krever spesiell tilbakestilling.",
    "Tjenerserveren krever spesiell omsorg.",
    "Datamaskinen min krever spesiell service.",
    "Programmet krever spesiell konfigurasjon.",
    "Jeg trenger spesiell tid til å løse det tekniske problemet.",
    "Systemet trenger umiddelbar service.",
    "Internettforbindelsen krever spesiell reparasjon.",
    "Datamaskinen min krever spesiell tilbakestilling.",
    "Programvaren krever spesiell oppdatering.",
    "Jeg trenger spesiell tilgang umiddelbart.",
    "Datalagringen krever umiddelbar service.",
    "Systemet brakk og krever umiddelbar reparasjon.",
    "Tjenerserveren brakk og krever umiddelbar service.",
    "Datamaskinen min brakk og krever umiddelbar reparasjon.",
    "Programmet brakk og krever umiddelbar oppdatering.",
    "Jeg trenger spesiell opplæring på nye systemverktøy.",
    "Systemet brakk og krever spesiell service.",
    "Internettforbindelsen brakk og krever spesiell reparasjon.",
    "Datamaskinen min brakk og krever spesiell konfigurasjon.",
    "Programvaren brakk og trenger spesiell reparasjon.",
    "Jeg trenger spesiell tilgang til det tekniske systemet.",
    "Datalagringen brakk og trenger spesiell service.",
    "Systemet krever umiddelbar tilbakestilling.",
    "Tjenerserveren krever umiddelbar service.",
    "Datamaskinen min krever umiddelbar reparasjon.",
    "Programmet krever umiddelbar oppdatering.",
    "Jeg trenger spesiell tid til å løse det tekniske problemet.",
    "Systemet trenger umiddelbare løsninger.",
    "Internettforbindelsen trenger umiddelbare løsninger.",
    "Datamaskinen min trenger umiddelbare løsninger.",
    "Programvaren trenger umiddelbare løsninger.",
    "Jeg trenger spesiell tid til å fikse systemet.",
    "Datalagringen trenger umiddelbare løsninger.",
    "Systemet brakk på grunn av programvareoppdatering.",
    "Tjenerserveren brakk på grunn av systemoppdatering.",
    "Datamaskinen min brakk på grunn av et programvareproblem.",
    "Programmet brakk på grunn av en systemoppdatering.",
    "Jeg trenger spesiell tilgang til systemet umiddelbart.",
    "Systemet trenger spesiell tilbakestilling umiddelbart.",
    "Internettforbindelsen trenger spesiell service umiddelbart.",
    "Datamaskinen min trenger spesiell reparasjon umiddelbart.",
    "Programvaren trenger spesiell oppdatering umiddelbart.",
    "Jeg trenger spesiell tilgang til arbeidsystemet umiddelbart.",
    "Datalagringen trenger spesiell behandling umiddelbart.",
    "Systemet krever spesiell service umiddelbart.",
    "Tjenerserveren krever spesiell reparasjon umiddelbart.",
    "Datamaskinen min krever spesiell reparasjon umiddelbart.",
    "Programmet krever spesiell konfigurasjon umiddelbart.",
    "Jeg trenger spesiell opplæring på nye arbeidsverktøy.",
    "Systemet krever spesiell tilbakestilling umiddelbart.",
    "Internettforbindelsen krever spesiell reparasjon umiddelbart.",
    "Datamaskinen min krever spesiell oppdatering umiddelbart.",
    "Programvaren krever spesiell reparasjon umiddelbart.",
    "Jeg trenger spesiell tilgang til arbeidsystemet umiddelbart.",
    "Datalagringen krever spesiell service umiddelbart.",
    "Systemet brakk og krever umiddelbar reparasjon.",
    "Tjenerserveren brakk og krever umiddelbar service.",
    "Datamaskinen min brakk og krever umiddelbar reparasjon.",
    "Programmet brakk og krever umiddelbar oppdatering.",
  ],
  motorcycle: [
    "Motorsykkelen min nekter å starte — batteriet er dødt.",
    "Dekket på motorsykkelen min punkterte på vei hit.",
    "Bremsen på motorsykkelen min er løs og trenger reparasjon.",
    "Tenningsnøkkelen på motorsykkelen min brakk.",
    "Motorsykkelen min er til service og kommer ikke tilbake før sent i dag.",
    "Jeg falt av motorsykkelen min men er heldigvis i live.",
    "Kjeden på motorsykkelen min brakk midt på veien.",
    "Olje lekket fra motorsykkelen min og jeg trenger reparasjon.",
    "Motorsykkelen min er frosset fast i garasjen.",
    "Motorsykkelens motor gir feil og trenger diagnose.",
    "Motorsykkelen min er under vedlikehold som ble forsinket.",
    "Tenningen på motorsykkelen min trenger utskifting.",
    "Motorsykkelen min har elektriske feil som trenger undersøkelse.",
    "Jeg trenger spesielle verktøy for å fikse motorsykkelen som jeg ikke har.",
    "Motorsykkelen min trenger spesiell smøring som bare er tilgjengelig på verksted.",
    "Kjeden er for løs på motorsykkelen og trenger justering.",
    "Styret på motorsykkelen er ødelagt og jeg kan ikke styre den.",
    "Dekkene trenger utskifting før jeg kan kjøre.",
    "Motorsykkelen min trenger spesiell inspeksjon på grunn av symptomer.",
    "Lysene på motorsykkelen er ødelagt og jeg kan ikke kjøre uten dem.",
    "Motorsykkelen min trenger spesiell reparasjon som tok lengre tid.",
    "Bremse-oljen på motorsykkelen trenger utskifting.",
    "Motorsykkelen min er nede på grunn av elektrisk feil.",
    "Dekkene er for gamle til å kjøre trygt.",
    "Motorsykkelen min trenger spesiell service i dag.",
    "Kjeden på motorsykkelen trenger reparasjon.",
    "Motorsykkelen min trenger spesiell justering.",
    "Oljen på motorsykkelen trenger utskifting.",
    "Motorsykkelen min er til service som tar hele dagen.",
    "Motoren på motorsykkelen går ikke som den skal.",
    "Motorsykkelen min trenger spesiell inspeksjon.",
    "Lysene på motorsykkelen trenger reparasjon.",
    "Motorsykkelen min trenger spesielt vedlikehold.",
    "Kjeden på motorsykkelen trenger justering.",
    "Motorsykkelen min trenger spesiell oljeskift.",
    "Bremsen på motorsykkelen trenger reparasjon.",
    "Motorsykkelen min trenger spesiell elektrisk reparasjon.",
    "Dekkene på motorsykkelen trenger utskifting.",
    "Motorsykkelen min trenger spesiell inspeksjon av motoren.",
    "Tenningen på motorsykkelen trenger reparasjon.",
    "Motorsykkelen min trenger spesiell service.",
    "Styret på motorsykkelen trenger reparasjon.",
    "Motorsykkelen min trenger spesielt vedlikehold av kjeden.",
    "Oljen på motorsykkelen trenger umiddelbar utskifting.",
    "Motorsykkelen min trenger spesiell inspeksjon av det elektriske.",
    "Bremse-oljen på motorsykkelen trenger umiddelbar utskifting.",
    "Motorsykkelen min trenger spesiell reparasjon av motoren.",
    "Kjeden på motorsykkelen trenger umiddelbar reparasjon.",
    "Motorsykkelen min trenger spesiell service av styret.",
    "Lysene på motorsykkelen trenger umiddelbar reparasjon.",
    "Motorsykkelen min trenger spesiell inspeksjon av bremsene.",
    "Dekkene på motorsykkelen trenger umiddelbar utskifting.",
    "Motorsykkelen min trenger spesielt vedlikehold av lysene.",
    "Tenningen på motorsykkelen trenger umiddelbar reparasjon.",
    "Motorsykkelen min trenger spesiell service av oljen.",
    "Styret på motorsykkelen trenger umiddelbar reparasjon.",
    "Motorsykkelen min trenger spesiell reparasjon av bremsene.",
    "Oljen på motorsykkelen trenger spesiell utskifting.",
    "Motorsykkelen min trenger spesiell inspeksjon av styret.",
    "Bremsen på motorsykkelen trenger spesiell reparasjon.",
    "Motorsykkelen min trenger spesielt vedlikehold av tenningen.",
    "Kjeden på motorsykkelen trenger spesiell justering.",
    "Motorsykkelen min trenger spesiell service av motoren.",
    "Lysene på motorsykkelen trenger spesiell reparasjon.",
    "Motorsykkelen min trenger spesiell inspeksjon av oljen.",
    "Dekkene på motorsykkelen trenger spesiell utskifting.",
    "Motorsykkelen min trenger spesiell reparasjon av kjeden.",
    "Tenningen på motorsykkelen trenger spesiell reparasjon.",
    "Motorsykkelen min trenger spesiell service av bremsene.",
    "Styret på motorsykkelen trenger spesiell reparasjon.",
    "Motorsykkelen min trenger spesielt vedlikehold av dekkene.",
    "Oljen på motorsykkelen trenger umiddelbar utskifting.",
    "Motorsykkelen min trenger spesiell inspeksjon umiddelbart.",
    "Bremse-oljen på motorsykkelen trenger spesiell utskifting.",
    "Motorsykkelen min trenger spesiell reparasjon umiddelbart.",
    "Kjeden på motorsykkelen trenger umiddelbar reparasjon.",
    "Motorsykkelen min trenger spesiell service umiddelbart.",
    "Lysene på motorsykkelen trenger umiddelbar reparasjon.",
    "Motorsykkelen min trenger spesielt vedlikehold umiddelbart.",
    "Tenningen på motorsykkelen trenger umiddelbar reparasjon.",
    "Motorsykkelen min trenger spesiell service av lysene.",
    "Styret på motorsykkelen trenger umiddelbar reparasjon.",
    "Motorsykkelen min trenger spesiell reparasjon av styret.",
    "Dekkene på motorsykkelen trenger umiddelbar utskifting.",
    "Motorsykkelen min trenger spesiell inspeksjon av kjeden.",
    "Oljen på motorsykkelen trenger spesiell service.",
    "Motorsykkelen min trenger spesielt vedlikehold av motoren.",
    "Bremsen på motorsykkelen trenger umiddelbar reparasjon.",
    "Motorsykkelen min trenger spesiell inspeksjon av tenningen.",
    "Kjeden på motorsykkelen trenger umiddelbar justering.",
    "Motorsykkelen min trenger spesiell service av dekkene.",
    "Lysene på motorsykkelen trenger spesiell reparasjon.",
    "Motorsykkelen min trenger spesiell inspeksjon av styret.",
    "Tenningen på motorsykkelen trenger spesiell reparasjon.",
    "Motorsykkelen min trenger spesiell service av kjeden.",
    "Styret på motorsykkelen trenger spesiell reparasjon.",
    "Motorsykkelen min trenger spesiell inspeksjon av lysene.",
  ],
};

function generateExcuses() {
  const allExcuses = [];
  let id = 1;

  for (const [category, excuses] of Object.entries(categories)) {
    for (const text of excuses) {
      allExcuses.push({ id, category, text });
      id++;
    }
  }

  // Pad to exactly 1001 using round-robin across categories if needed
  const catNames = Object.keys(categories);
  const catArrays = Object.values(categories);
  let fillerCatIdx = 0;
  let fillerItemIdx = 0;

  while (allExcuses.length < 1001) {
    const catName = catNames[fillerCatIdx % catNames.length];
    const catList = catArrays[fillerCatIdx % catArrays.length];
    const text = catList[fillerItemIdx % catList.length];
    allExcuses.push({ id, category: catName, text });
    id++;
    fillerItemIdx++;
    if (fillerItemIdx % catList.length === 0) fillerCatIdx++;
  }

  return allExcuses.slice(0, 1001);
}

const excuses = generateExcuses();
const outputPath = require('path').join(__dirname, '..', 'assets', 'excuses_no.json');

require('fs').writeFileSync(outputPath, JSON.stringify(excuses, null, 2), 'utf8');
console.log(`✅  Generated ${excuses.length} Norwegian excuses → ${outputPath}`);
